### ISSUE TITLE
Identity Server 502 Bad Gateway Error

### ISSUE THREAD

**Issue by emelendezARI** [DuendeSoftware/Support#230] opened 2022-09-23 21:49 UTC
**Which version of Duende IdentityServer are you using?**
v5.2.1

**Which version of .NET are you using?**
v6

We are running IdentityServer on an AWS EC2 instance (IIS v10), with AWS application load balancers in front. We previously started getting HTTP 400 errors (Bad Request - Request Too Long) and resolved this by increasing the MaxFieldLength and MaxRequestBytes registry keys to 32k.

Recently, we started getting 502 Bad Gateway Errors with error messages that were similar to the former, so we tried increasing the same values to 64k, but this did not resolved the issue. From the logs, it appears that the load balancers are rejecting large HTTP header fields and closing the connections.

Has anyone had this issue, and what was done to resolve?

**Comment by brockallen** [comment] 2022-09-24 02:36
Sorry, not sure. Can you record the HTTP traffic for the failed requests? That way you'd see what headers are too large to start to track this down. Also, you can check your IdentityServer logs to see if there's any recent new logs that hint at the cause (e.g. errors for example)?

**Comment by emelendezARI** [comment] 2022-09-26 15:26
@brockallen Is there a way to send you our logs privately? We'd prefer not to make them publicly available.

**Comment by brockallen** [comment] 2022-09-26 15:48
Only if you have Priority Support. But you don't have to send them -- I was suggesting that you have a look for something that hints at the issue.

**Comment by brockallen** [comment] 2022-10-03 16:08
Any update here?

**Comment by emelendezARI** [comment] 2022-10-03 16:58
Unfortunately, we are still struggling to get enough information to determine the exact cause. AWS support has stated the following:

> Analyzing the packet captures/internal logs & discussing with the internal service team I suspect that the load balancer is dropping the packet since the response from the target has a header size of more than Application Load Balancer hard limits.
> 
> The following size limits for Application Load Balancers are hard limits that cannot be changed, Please refer [1] to understand ALB HTTP Header limits.
> 
> HTTP/1.x headers
> Request line: 16 K
> Single header: 16 K
> Entire header: 64 K
> 
> HTTP/2 headers
> Request line: 16 K
> Single header: 16 K
> Entire header: 64 K

We don't have a way to validate this since we're uncertain on how to confirm this through the IdServer. This is the only system that we have full control over in this process, but are unable to isolate the transaction in question.

**Comment by brockallen** [comment] 2022-10-03 17:20
Well, that does help isolate it a bit more, I think.

**Comment by emelendezARI** [comment] 2022-10-03 21:30
We suspect that the end user is a member of a lot of groups, causing an increased header size in the authentication process, but we don't know for sure. How might we see if that's the case? Is there a method for reviewing header sizes?

**Comment by brockallen** [comment] 2022-10-04 12:47
> Is there a method for reviewing header sizes?

That I assumed would be some feature of the proxy. But in ASP.NET Core you can write middleware to log whatever info you need/want.

**Comment by brockallen** [comment] 2022-10-11 14:46
Closing. If you still have issues, feel free to reopen.

**Closed by brockallen** 2022-10-11 14:46 UTC
Labels: IdentityServer, question
