### ISSUE TITLE
Need Maximum Token Lifetime Values in 

### ISSUE THREAD

**Issue by PriyankaTalapaneni** [DuendeSoftware/Support#1042] opened 2023-12-26 18:01 UTC
**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment] 2023-12-27 02:56
This seemed to be a duplicate of #1043.

**Closed** 2023-12-27 02:56 UTC
Labels: IdentityServer
