### ISSUE TITLE
Exceptions in tokens in version 7.0.1

### ISSUE THREAD

**Issue by hedzerjan** [DuendeSoftware/Support#1178] opened 2024-03-21 07:55 UTC
Identity server 7.01, .Net 8.0.3.

About 30% of our customers ran into the two exceptions below and could not log in. This has caused us to revert to a build using IdentityServer 6.3.6 which uses .Net 7.

We can not reproduce this ourselves. We also do not see anything that distinguishes the customers experiencing the problem to those that don't.

```
Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login. 
---> Microsoft.IdentityModel.Tokens.SecurityTokenException: No token validator or token handler was found for the given token. 
---> System.AggregateException: One or more errors occurred. (IDX10204: Unable to validate issuer. validationParameters.ValidIssuer is null or whitespace AND validationParameters.ValidIssuers is null or empty.) (IDX30011: Unable to read XML. Expecting XmlReader to be at ns.element: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.].[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', found: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.].[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.) (IDX14100: JWT is not well formed, there are no dots (.).The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.) 
---> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10204: Unable to validate issuer. validationParameters.ValidIssuer is null or whitespace AND validationParameters.ValidIssuers is null or empty.   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuerAsync(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateSignature(Saml2SecurityToken samlToken, String token, TokenValidationParameters validationParameters)   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateTokenAsync(String token, TokenValidationParameters validationParameters)   --- End of inner exception stack trace --- 
---> (Inner Exception #1) Microsoft.IdentityModel.Xml.XmlReadException: IDX30011: Unable to read XML. Expecting XmlReader to be at ns.element: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.].[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', found: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.].[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.   at Microsoft.IdentityModel.Xml.XmlUtil.CheckReaderOnEntry(XmlReader reader, String element, String namespace)   at Microsoft.IdentityModel.Tokens.Saml.SamlSerializer.ReadAssertion(XmlReader reader)   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ReadSamlToken(String token)   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateTokenAsync(String token, TokenValidationParameters validationParameters)<--- 
---> (Inner Exception #2) Microsoft.IdentityModel.Tokens.SecurityTokenMalformedException: IDX14100: JWT is not well formed, there are no dots (.).The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'. 
---> Microsoft.IdentityModel.Tokens.SecurityTokenMalformedException: IDX14122: JWT is not a well formed JWE, there are more than four dots (.) a JWE can have at most 4 dots.The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.   at Microsoft.IdentityModel.JsonWebTokens.JsonWebToken.ReadToken(String encodedJson)   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ReadToken(String token, TokenValidationParameters validationParameters)   --- End of inner exception stack trace ---<---   --- End of inner exception stack trace ---   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.HandleRemoteAuthenticateAsync()   --- End of inner exception stack trace ---   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 51   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27   at TriasMVC.WebCommon.Middleware.IPFiltering.Invoke(HttpContext httpContext, IIdentityTenantService identityTenantService, ITenantRepository tenantRepository) in /_/src/WebCommon/Middleware/IPFiltering.cs:line 61   at AuthServer.MiddleWare.TenantCookieSelector.Invoke(HttpContext httpContext, IIdentityTenantService tenantProvider, ILogger`1 logger) in D:\a\1\s\src\MiddleWare\TenantCookieSelector.cs:line 48   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```
```
Microsoft.IdentityModel.Tokens.SecurityTokenException: No token validator or token handler was found for the given token. 
---> System.AggregateException: One or more errors occurred. (IDX10204: Unable to validate issuer. validationParameters.ValidIssuer is null or whitespace AND validationParameters.ValidIssuers is null or empty.) (IDX30011: Unable to read XML. Expecting XmlReader to be at ns.element: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.].[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', found: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.].[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.) (IDX14100: JWT is not well formed, there are no dots (.).The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.) 
---> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10204: Unable to validate issuer. validationParameters.ValidIssuer is null or whitespace AND validationParameters.ValidIssuers is null or empty.   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuerAsync(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateSignature(Saml2SecurityToken samlToken, String token, TokenValidationParameters validationParameters)   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)   at Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityTokenHandler.ValidateTokenAsync(String token, TokenValidationParameters validationParameters)   --- End of inner exception stack trace --- 
---> (Inner Exception #1) Microsoft.IdentityModel.Xml.XmlReadException: IDX30011: Unable to read XML. Expecting XmlReader to be at ns.element: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.].[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', found: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.].[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.   at Microsoft.IdentityModel.Xml.XmlUtil.CheckReaderOnEntry(XmlReader reader, String element, String namespace)   at Microsoft.IdentityModel.Tokens.Saml.SamlSerializer.ReadAssertion(XmlReader reader)   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ReadSamlToken(String token)   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateTokenAsync(String token, TokenValidationParameters validationParameters)<--- 
---> (Inner Exception #2) Microsoft.IdentityModel.Tokens.SecurityTokenMalformedException: IDX14100: JWT is not well formed, there are no dots (.).The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'. 
---> Microsoft.IdentityModel.Tokens.SecurityTokenMalformedException: IDX14122: JWT is not a well formed JWE, there are more than four dots (.) a JWE can have at most 4 dots.The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.   at Microsoft.IdentityModel.JsonWebTokens.JsonWebToken.ReadToken(String encodedJson)   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ReadToken(String token, TokenValidationParameters validationParameters)   --- End of inner exception stack trace ---<---   --- End of inner exception stack trace ---   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.HandleRemoteAuthenticateAsync()
```

**Comment by hedzerjan** [comment] 2024-04-05 08:38
Any update on this? We're now having apply some really ugly patches to have our identityserver keep up with the rest of the software.

**Comment by AndersAbel** [comment] 2024-04-05 11:11
This looks like requests are handled by the WS-Federation authentication handler. Do you have a path for the request where this happends?

Could you please share some more information about your authentication setup? What external authentication schemes do you have enabled?

**Comment by hedzerjan** [comment] 2024-04-08 06:56
We have two main applications that use IdentityServer, one of which is the old one and thats uses WS-Federation to authenticate with IdentityServer. The new application uses OIDC. To support WS-Federation we use Rsk.WsFederation.DuendeIdentityServer version 8.0.0. 

The external schemes that we use are OIDC, WS-Federation and Google (OAuth). We did not see a pattern of external schemes or settings that corresponded with the error happening.

The requestpath where the error occurs is the callbackpath (`RemoteAuthenticationOptions.CallbackPath`).

**Comment by AndersAbel** [comment] 2024-04-10 11:55
And what is the value of `RemoteAuthenticationOptions.CallbackPath` in this case? What scheme is it that has that path configured?

**Comment by hedzerjan** [comment] 2024-04-11 05:57
The callback path is different for every customer. The customers that were affected all had different paths and schemes.

**Comment by hedzerjan** [comment] 2024-04-11 07:46
Here are two examples, different handlers, different paths:
```json
{
    "Properties": {
        "EventId": {
            "Id": 3,
            "Name": "ExceptionProcessingMessage"
        },
        "SourceContext": "Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler",
        "RequestId": "800003a4-0000-7400-b63f-84710c7967bb",
        "RequestPath": "/Visio_ADFS",
        "MachineName": "TRIASAPP102",
        "Application": "AuthServer"
    }
}
```
```json
{
    "Properties": {
        "EventId": {
            "Id": 17,
            "Name": "ExceptionProcessingMessage"
        },
        "SourceContext": "Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler",
        "RequestId": "8000039c-0000-7400-b63f-84710c7967bb",
        "RequestPath": "/siza/signin-oidc",
        "MachineName": "TRIASAPP102",
        "Application": "AuthServer"
    }
}```

**Comment by hedzerjan** [comment] 2024-04-11 07:50
I just noticed, for OIDC the root exception seems to be:
```
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10503: Signature validation failed. Token does not have a kid. Keys tried: '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Number of keys in TokenValidationParameters: '1'. Number of keys in Configuration: '0'. Exceptions caught: '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.token: '[PII of type 'Microsoft.IdentityModel.JsonWebTokens.JsonWebToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. See https://aka.ms/IDX10503 for details.   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateTokenUsingHandlerAsync(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters)   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
```

**Comment by AndersAbel** [comment] 2024-04-11 11:51
This looks like it might be caused by Microsoft.IdentityModel.* package version mismatch. Could you please validate the versions used by following the steps on  https://github.com/DuendeSoftware/docs.duendesoftware.com/blob/d99ac7960f62bd82ddbb542ec1416cc37d29f6c5/IdentityServer/v7/docs/content/troubleshooting/wilson.md? (this will be published on the docs site soon, this is a preview link).

**Comment by hedzerjan** [comment] 2024-04-12 11:09
This is the output of the branch that was affected, which shows one faulty version. It'll take some time to try the fix, since we dan't reproduce it ourselves.
```

   > Microsoft.IdentityModel.Abstractions                                               7.1.2
   > Microsoft.IdentityModel.JsonWebTokens                                              7.1.2
   > Microsoft.IdentityModel.Logging                                                    7.1.2
   > Microsoft.IdentityModel.Protocols                                                  7.1.2
   > Microsoft.IdentityModel.Protocols.OpenIdConnect                                    7.0.3
   > Microsoft.IdentityModel.Protocols.WsFederation                                     7.1.2
   > Microsoft.IdentityModel.Tokens                                                     7.1.2
   > Microsoft.IdentityModel.Tokens.Saml                                                7.1.2
   > Microsoft.IdentityModel.Xml                                                        7.1.2
   > System.IdentityModel.Tokens.Jwt                                                    7.1.2
```

**Comment by RolandGuijt** [comment] 2024-04-17 13:14
In .NET 8 the code that handles tokens has been rewritten. So it might be that you use some kind of configuration that was working before but in .NET 8 doesn't work anymore.
The next step would be to check your client configuration. Can you please share the code where you configure the OpenID Connect handler on the client (services.AddOpenIdConnect..) and the configuration of the client in IdentityServer?

**Comment by RolandGuijt** [comment] 2024-04-26 14:20
It seems that the exceptions your getting now that the IdentityModel version mismatch is fixed have to do with the IssuerSigningKey you're using. The signing should be done using asymetric encryption instead of the symetric encryption you're using here with the client secret as a key which isn't meant for that.

Can you please remove the line setting IssuerSigningKey and any other logic for that you might have elsewhere and then see if it works as expected?

**Comment by hedzerjan** [comment] 2024-05-02 08:58
Hi Roland, we've removed the line
```csharp
options.TokenValidationParameters.IssuerSigningKey = new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(System.Text.Encoding.ASCII.GetBytes(metaUrl.ClientSecret.ToString()));
```
But that caused lots of these exceptions:
```
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateTokenUsingHandlerAsync(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters)   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
```
```
Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login. ---> Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateTokenUsingHandlerAsync(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters)   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()   --- End of inner exception stack trace ---   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 51   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27   at TriasMVC.WebCommon.Middleware.IPFiltering.Invoke(HttpContext httpContext, IIdentityTenantService identityTenantService, ITenantRepository tenantRepository) in /_/src/WebCommon/Middleware/IPFiltering.cs:line 61   at AuthServer.MiddleWare.TenantCookieSelector.Invoke(HttpContext httpContext, IIdentityTenantService tenantProvider, ILogger`1 logger) in D:\a\1\s\src\MiddleWare\TenantCookieSelector.cs:line 48   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by RolandGuijt** [comment] 2024-05-09 07:12
Do you have something special configured in IdentityServer for token signing? Can you share the configuration code for that? (the part starting with AddIdentityServer).

The way JWT signing works out of the box is as follows:
- The identity provider holds a private/public key pair.
- When a token is issued it is signed using the private key
- To verify the token's signature the client or API needs the public key
- The public part of the key is published in the discovery document so it is just downloaded

We recommend to not deviate from this mechanism, especially not by replacing it with symmetric encryption which is unsafe.

Hopefully with this info you can figure out what's going wrong.

**Comment by hedzerjan** [comment] 2024-05-13 09:17
Hi Roland, thanks for your patience. This is de line of code you mentioned, I think:
```csharp
            var builder = services.AddIdentityServer(options =>
            {
                options.KeyManagement.Enabled = false;
                options.KeyManagement.SigningAlgorithms = new[] {
                    new SigningAlgorithmOptions("RS256") {UseX509Certificate = true}
                };
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;
                options.Authentication.CookieLifetime = TimeSpan.FromHours(10);
                options.LicenseKey =  "***";
            })
                // this adds the config data from DB (clients, resources, CORS)
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(Configuration.GetConnectionString(Constants.ConnectionKeys.Identity),
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(Configuration.GetConnectionString(Constants.ConnectionKeys.Identity),
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 86400; // interval in seconds (default is 3600)
                })
                .AddAspNetIdentity<ApplicationUser>();
```

**Comment by khamza85** [comment] 2024-05-16 23:42
sorry to jump in, but I checked the jwks endpoint from the discovery endpoint and it returns an empty JSON. Might be related

https://siza.helloid.com/oauth2/v2/66bc8852-279c-428c-b8d6-3030a29bcfbb/.well-known/openid-configuration/jwks

**Comment by AndersAbel** [comment] 2024-05-22 12:14
I just want to check that I understand the flow right here, does it look like this?

Client (triasweb.nl) <---- OIDC ----> IdentityServer <---- OIDC -----> siza.helloid.com

If I read the error messages right, it looks like the problem is with the OIDC communication between IdentityServer and siza.helloid.com, where size.helloid.com acts as an OIDC Provider?

**Comment by hedzerjan** [comment] 2024-05-23 06:25
The flow is probably different, there are two possible flows and this might be the first one. In this case WSFed is handled by the RSK WSFed plugin:
Client (gz.triasweb.nl or a different subdomain) <---WSFed ---> IdentityServer <--- OIDC ---> siza.helloid.com
The second situation:
Client (triasweb.nl) <---OIDC ---> IdentityServer <--- OIDC ---> siza.helloid.com

**Comment by RolandGuijt** [comment] 2024-05-29 07:28
@hedzerjan Would you like to add something to this issue? If not I'd like to close it.

**Comment by hedzerjan** [comment] 2024-05-29 15:29
Hi Roland, you can close it, thanks

**Closed** 2024-05-29 16:23 UTC
Labels: IdentityServer
