### ISSUE TITLE
"connect/authorize" request redirect_uri parameter does not set https 

### ISSUE THREAD

**Issue by gundogduhasan** [DuendeSoftware/Support#333] opened 2022-11-15 09:27 UTC
**Which version of Duende BFF are you using?**
V6
**Which version of .NET are you using?**
6
Hi,
I m trying to simulate BFF frame work with angular client in my local development environment. First I tried with http but always keep getting "System.Exception: Correlation failed" error. I thougth problem is using http, instead of https. And then I tried same thing with https. This time, "connect/authorize" request redirect_uri parameter does not set https. My redirect uri https://localhost:44460 but it's sets with out https, like this http://localhost:44460.

I solved the issue using https request scheme in my client app backend side. Like this;
```
app.Use((context, next) =>
{
    context.Request.Scheme = "https";
    return next(context);
});
```
And everything work as should be.

My question is, I just want to know, are my solutions are correct for these issues? 
Solution 1 : Using https instead of http for "System.Exception: Correlation failed" error.
Solution 2 : Setting correctly redirect_uri parameter with previous code (request https scheme).

Is there any harm in using them like this?

**Comment by gundogduhasan** [comment] 2022-11-16 06:59
Yes. I already clone these apps. And, for example reactjs works in my local too. But all of these samples are http, not https. When I tried with http I am getting the error I mentioned. And then I had to returned to https and the workaround solution.

**Comment by gundogduhasan** [comment] 2022-11-16 09:17
Here is my client project program.cs codes;


```
using Duende.Bff.Yarp;
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllersWithViews();
builder.Services.AddBff().AddRemoteApis(); ;

builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "cookie";
    options.DefaultChallengeScheme = "oidc";
    options.DefaultSignOutScheme = "oidc";
}).AddCookie("cookie", options =>
{
    options.Cookie.Name = "__Host-bff";
    options.Cookie.SameSite = SameSiteMode.Strict;
}).AddOpenIdConnect("oidc", options =>
{
    options.Authority = "https://localhost:5200";
    options.ClientId = "bff";
    options.ClientSecret = "bff";
    options.ResponseType = "code";
    options.ResponseMode = "query";

    options.GetClaimsFromUserInfoEndpoint = true;
    options.MapInboundClaims = false;
    options.SaveTokens = true;

    options.Scope.Clear();
    options.Scope.Add("openid");
    options.Scope.Add("profile");
    options.Scope.Add("role");

    options.TokenValidationParameters = new()
    {
        NameClaimType = "name",
        RoleClaimType = "role"
    };
});
var app = builder.Build();

app.Use((context, next) =>
{
    context.Request.Scheme = "https";
    return next(context);
});
app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseBff();
app.UseAuthorization();
app.MapBffManagementEndpoints();

app.MapControllers()
    .RequireAuthorization()
    .AsBffApiEndpoint();

 app.MapRemoteBffApiEndpoint("/UserApi", "https://localhost:5200/UserApi")
     .RequireAccessToken(Duende.Bff.TokenType.User);

app.MapFallbackToFile("index.html"); ;

app.Run();

```

if I remove the following part of code
 ```
app.Use((context, next) =>
{
    context.Request.Scheme = "https";
    return next(context);
});
```
And click login, identity returns with this error
"Sorry, there was an error : invalid_request
Invalid redirect_uri"

And when I look to the identity server logs, I see this log "Invalid redirect_uri: http://localhost:44460/signin-oidc"
As you can see https missing redirect_uri should be "https://localhost:44460/signin-oidc"

**Comment by josephdecock** [comment] 2022-11-16 17:28
Try changing the client config in IdentityServer to specify that http://localhost:44460/sigin-oidc is an allowed redirect_uri.

**Comment by gundogduhasan** [comment] 2022-11-16 17:49
> Try changing the client config in IdentityServer to specify that http://localhost:44460/sigin-oidc is an allowed redirect_uri.

With http, I am getting error. Error I mentioned my question.

**Comment by josephdecock** [comment] 2022-11-16 19:39
Oh, now I see the problem - your bff auth cookie is named __host.  The __host prefeix on cookie name tells the browser to enforce rules on the cookie to make them more secure, including the requirement that the cookie set the secure attribute - in other words, that cookie requires https.

**Comment by gundogduhasan** [comment] 2022-11-16 19:51
Ohh. Okay. I think that is why I have to use https right? Then what about the code block I used, request scheme https. Is there any harm using it?

**Comment by josephdecock** [comment] 2022-11-16 20:05
You either need to use https or change the name of the cookie to not start with __host. I don't think changing the scheme of the request is a good idea - anything that relies on the scheme value is going to get something inaccurate now. I don't actually know what that might break, but I would avoid it.

**Comment by gundogduhasan** [comment] 2022-11-16 20:44
I understand that. But I am little confused about not setting to https in redirect_uri parameter. Right now I am already using https. That's okay. But without the request scheme https, redirect_uri does not set https. If I understand correctly with that cookie nameI have to use https. But why does not set the https in the redirect_uri parameter without changing request scheme? This "__host..." cookie name, Is this the reason for this issue too?

**Comment by josephdecock** [comment] 2022-11-17 16:58
The cookie name shouldn't be involved in how the redirect_uri gets set. My advice is to use https even in local development, and not include the middleware that changes the scheme. With that as our goal, can you please remove that middleware and try again to do a fresh authentication, beginning at http**s**://localhost:44460 with your browser dev tools open so you capture the network requests. Then could you please
1. Share the network traffic, 
2. Say how you are hosting this application (kestrel, IIS, etc)
3. Share your Properties/LaunchSettings.json?

**Comment by gundogduhasan** [comment] 2022-11-17 18:31
Thank you very much @josephdecock I will try these steps and let you know.

**Comment by gundogduhasan** [comment] 2022-11-17 20:54
I removed request scheme middleware but since bff login end point it's a redirect I couldn't capture network tab. But I captured the logs.

Here what you want's
--I am using iis express for hosting
--launchSettings; 
```
{
  "profiles": {
    "Project2": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5183",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.SpaProxy"
      }
    }
  }
}
```
Error screenshot
![err1](https://user-images.githubusercontent.com/28599201/202556838-bcd2416c-a1de-46dc-a138-71d604bc3d8e.PNG)

Identity server log screenshot
![err2](https://user-images.githubusercontent.com/28599201/202556926-3fcfdbfa-ea64-437c-8daf-3cef6369461f.png)

And finally identity server detailed logs
```


[23:43:45 Debug] Duende.IdentityServer.Hosting.EndpointRouter
Request path /.well-known/openid-configuration matched to endpoint type Discovery

[23:43:45 Debug] Duende.IdentityServer.Hosting.EndpointRouter
Endpoint enabled: Discovery, successfully created handler: Duende.IdentityServer.Endpoints.DiscoveryEndpoint

[23:43:45 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration

[23:43:45 Verbose] Duende.IdentityServer.Endpoints.DiscoveryEndpoint
Processing discovery request.

[23:43:45 Debug] Duende.IdentityServer.Endpoints.DiscoveryEndpoint
Start discovery request

[23:43:45 Verbose] Duende.IdentityServer.Endpoints.DiscoveryEndpoint
Calling into discovery response generator: Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Getting all the keys.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Cache miss when loading all keys.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Loading keys from store.

[23:43:45 Error] Duende.IdentityServer.Services.KeyManagement.KeyManager
Error unprotecting key with kid 55F912C2D3F554FE2A5642E74A008BEC.
System.Security.Cryptography.CryptographicException: The key {faebf6ef-52ab-4d13-86d9-a7c82d5d3418} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Loaded keys from store: CEED7A9EC0651A15916C54932D360FCE

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Remaining keys after filter: CEED7A9EC0651A15916C54932D360FCE

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Keys with allowed alg from store: CEED7A9EC0651A15916C54932D360FCE

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Keys successfully returned from store.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Caching keys with KeyCacheDuration for 1.00:00:00

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Looking for active signing keys.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Looking for an active signing key for alg RS256.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (respecting activation delay).

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is inactive: the current time is prior to its activation delay.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
No active signing key found (respecting the activation delay).

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (ignoring activation delay).

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is active.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Active signing key found (ignoring the activation delay) with kid: CEED7A9EC0651A15916C54932D360FCE.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Found active signing key for alg RS256 with kid CEED7A9EC0651A15916C54932D360FCE.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (respecting activation delay).

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is inactive: the current time is prior to its activation delay.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
No active signing key found (respecting the activation delay).

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (ignoring activation delay).

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is active.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Active signing key found (ignoring the activation delay) with kid: CEED7A9EC0651A15916C54932D360FCE.

[23:43:45 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key rotation not required for alg RS256; New key expected to be created in 72.14:38:52

[23:43:45 Debug] Duende.IdentityServer.EntityFramework.Stores.ResourceStore
Found ["openid", "profile", "role", "api1"] as all scopes, and [] as API resources

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Getting the current key.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Cache hit when loading all keys.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Looking for active signing keys.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Looking for an active signing key for alg RS256.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (respecting activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is inactive: the current time is prior to its activation delay.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
No active signing key found (respecting the activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (ignoring activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is active.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Active signing key found (ignoring the activation delay) with kid: CEED7A9EC0651A15916C54932D360FCE.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Found active signing key for alg RS256 with kid CEED7A9EC0651A15916C54932D360FCE.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (respecting activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is inactive: the current time is prior to its activation delay.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
No active signing key found (respecting the activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (ignoring activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is active.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Active signing key found (ignoring the activation delay) with kid: CEED7A9EC0651A15916C54932D360FCE.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key rotation not required for alg RS256; New key expected to be created in 72.14:38:51

[23:43:46 Information] Duende.IdentityServer.Services.KeyManagement.KeyManager
Active signing key found with kid CEED7A9EC0651A15916C54932D360FCE for alg RS256. Expires in 86.14:38:51. Retires in 100.14:38:51

[23:43:46 Verbose] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking result: Duende.IdentityServer.Endpoints.Results.DiscoveryDocumentResult

[23:43:46 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /.well-known/openid-configuration responded 200 in 1082.2389 ms

[23:43:46 Debug] Duende.IdentityServer.Hosting.EndpointRouter
Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery

[23:43:46 Debug] Duende.IdentityServer.Hosting.EndpointRouter
Endpoint enabled: Discovery, successfully created handler: Duende.IdentityServer.Endpoints.DiscoveryKeyEndpoint

[23:43:46 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks

[23:43:46 Verbose] Duende.IdentityServer.Endpoints.DiscoveryKeyEndpoint
Processing discovery request.

[23:43:46 Debug] Duende.IdentityServer.Endpoints.DiscoveryKeyEndpoint
Start key discovery request

[23:43:46 Verbose] Duende.IdentityServer.Endpoints.DiscoveryKeyEndpoint
Calling into discovery response generator: Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Getting all the keys.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Cache hit when loading all keys.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Looking for active signing keys.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Looking for an active signing key for alg RS256.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (respecting activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is inactive: the current time is prior to its activation delay.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
No active signing key found (respecting the activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (ignoring activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is active.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Active signing key found (ignoring the activation delay) with kid: CEED7A9EC0651A15916C54932D360FCE.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Found active signing key for alg RS256 with kid CEED7A9EC0651A15916C54932D360FCE.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (respecting activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is inactive: the current time is prior to its activation delay.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
No active signing key found (respecting the activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Checking if key with kid CEED7A9EC0651A15916C54932D360FCE is active (ignoring activation delay).

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key with kid CEED7A9EC0651A15916C54932D360FCE is active.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Active signing key found (ignoring the activation delay) with kid: CEED7A9EC0651A15916C54932D360FCE.

[23:43:46 Verbose] Duende.IdentityServer.Services.KeyManagement.KeyManager
Key rotation not required for alg RS256; New key expected to be created in 72.14:38:51

[23:43:46 Verbose] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking result: Duende.IdentityServer.Endpoints.Results.JsonWebKeysResult

[23:43:46 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /.well-known/openid-configuration/jwks responded 200 in 171.9545 ms

[23:43:46 Debug] Duende.IdentityServer.Hosting.EndpointRouter
Request path /connect/authorize matched to endpoint type Authorize

[23:43:46 Debug] Duende.IdentityServer.Hosting.EndpointRouter
Endpoint enabled: Authorize, successfully created handler: Duende.IdentityServer.Endpoints.AuthorizeEndpoint

[23:43:46 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.AuthorizeEndpoint for /connect/authorize

[23:43:46 Debug] Duende.IdentityServer.Endpoints.AuthorizeEndpoint
Start authorize request

[23:43:46 Debug] Duende.IdentityServer.Endpoints.AuthorizeEndpoint
No user present in authorize request

[23:43:46 Debug] Duende.IdentityServer.Validation.AuthorizeRequestValidator
Start authorize request protocol validation

[23:43:46 Debug] Duende.IdentityServer.EntityFramework.Stores.ClientStore
bff found in database: True

[23:43:46 Verbose] Duende.IdentityServer.Stores.ValidatingClientStore
Calling into client configuration validator: Duende.IdentityServer.Validation.DefaultClientConfigurationValidator

[23:43:46 Debug] Duende.IdentityServer.Stores.ValidatingClientStore
client configuration validation for client bff succeeded.

[23:43:46 Error] Duende.IdentityServer.Validation.AuthorizeRequestValidator
Invalid redirect_uri: http://localhost:44460/signin-oidc
{"ClientId": "bff", "ClientName": "test bff", "RedirectUri": null, "AllowedRedirectUris": ["https://localhost:44460/signin-oidc"], "SubjectId": "anonymous", "ResponseType": null, "ResponseMode": null, "GrantType": null, "RequestedScopes": "", "State": null, "UiLocales": null, "Nonce": null, "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": "", "MaxAge": null, "LoginHint": null, "SessionId": null, "Raw": {"client_id": "bff", "redirect_uri": "http://localhost:44460/signin-oidc", "response_type": "code", "scope": "openid profile role api1", "code_challenge": "nwqTm-vB3p39tOd-MGvwBLigILm3pqHgltE-lYw5cE0", "code_challenge_method": "S256", "nonce": "638043146265425402.ZmUwNDVjNTUtMzk0YS00YjJiLWJjMTUtOGI4YTY4MjY3OTY5MTRiYjIxMDUtYzQ4YS00ZGI0LThhN2EtODYyMDQwODRiNDk4", "state": "CfDJ8GjV4rteP2NCot0f0GPOVydPu1Wk5fn_fo1j2qAo_31oep1EIa9kCEvj37lYaNjQf1dwOQlSfBfQuWAHXU7h3z7vg9ByIFuy7ljx4dkjowIai_XzlKe-Ix2HNwb6HSOrVDQj8GUYtGRDy97K_ueGpO9sF0x6lbr6qDqBqte8OTwvG8hTFPL9KmLf09NXBfaJcI8GQgmk7V_74mGvCMP2ylV5Wwu0xPByKgRi4HvAyqEJ09vpBMvpeB0MGmuewMloEDvGU3TVGcAdn7kuStaHZskol40M130XxjE5O1EqESAWOSr8855h5g-eCfvaU8KIrQlB8X1NIJ1RCwiZ0d_bINZrKRHbGImxyoZUXYXNMX1HkXPNdkZtbkGhKvF3zYyNLw", "x-client-SKU": "ID_NETSTANDARD2_0", "x-client-ver": "6.10.0.0"}, "$type": "AuthorizeRequestValidationLog"}
[23:43:46 Error] Duende.IdentityServer.Endpoints.AuthorizeEndpoint
Request validation failed

[23:43:46 Information] Duende.IdentityServer.Endpoints.AuthorizeEndpoint
{"ClientId": "bff", "ClientName": "test bff", "RedirectUri": null, "AllowedRedirectUris": ["https://localhost:44460/signin-oidc"], "SubjectId": "anonymous", "ResponseType": null, "ResponseMode": null, "GrantType": null, "RequestedScopes": "", "State": null, "UiLocales": null, "Nonce": null, "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": "", "MaxAge": null, "LoginHint": null, "SessionId": null, "Raw": {"client_id": "bff", "redirect_uri": "http://localhost:44460/signin-oidc", "response_type": "code", "scope": "openid profile role api1", "code_challenge": "nwqTm-vB3p39tOd-MGvwBLigILm3pqHgltE-lYw5cE0", "code_challenge_method": "S256", "nonce": "638043146265425402.ZmUwNDVjNTUtMzk0YS00YjJiLWJjMTUtOGI4YTY4MjY3OTY5MTRiYjIxMDUtYzQ4YS00ZGI0LThhN2EtODYyMDQwODRiNDk4", "state": "CfDJ8GjV4rteP2NCot0f0GPOVydPu1Wk5fn_fo1j2qAo_31oep1EIa9kCEvj37lYaNjQf1dwOQlSfBfQuWAHXU7h3z7vg9ByIFuy7ljx4dkjowIai_XzlKe-Ix2HNwb6HSOrVDQj8GUYtGRDy97K_ueGpO9sF0x6lbr6qDqBqte8OTwvG8hTFPL9KmLf09NXBfaJcI8GQgmk7V_74mGvCMP2ylV5Wwu0xPByKgRi4HvAyqEJ09vpBMvpeB0MGmuewMloEDvGU3TVGcAdn7kuStaHZskol40M130XxjE5O1EqESAWOSr8855h5g-eCfvaU8KIrQlB8X1NIJ1RCwiZ0d_bINZrKRHbGImxyoZUXYXNMX1HkXPNdkZtbkGhKvF3zYyNLw", "x-client-SKU": "ID_NETSTANDARD2_0", "x-client-ver": "6.10.0.0"}, "$type": "AuthorizeRequestValidationLog"}
[23:43:47 Information] Duende.IdentityServer.Events.DefaultEventService
{"ClientId": "bff", "ClientName": "test bff", "RedirectUri": null, "Endpoint": "Authorize", "SubjectId": null, "Scopes": "", "GrantType": null, "Error": "invalid_request", "ErrorDescription": "Invalid redirect_uri", "Category": "Token", "Name": "Token Issued Failure", "EventType": "Failure", "Id": 2001, "Message": null, "ActivityId": "0HMM8RFVMCE0J:00000005", "TimeStamp": "2022-11-17T20:43:46.9979686Z", "ProcessId": 32160, "LocalIpAddress": "::1:5200", "RemoteIpAddress": "::1", "$type": "TokenIssuedFailureEvent"}

[23:43:47 Verbose] Duende.IdentityServer.Endpoints.AuthorizeEndpoint
End authorize request. result type: Duende.IdentityServer.Endpoints.Results.AuthorizeResult

[23:43:47 Verbose] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking result: Duende.IdentityServer.Endpoints.Results.AuthorizeResult

[23:43:47 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /connect/authorize?client_id=bff&redirect_uri=http%3A%2F%2Flocalhost%3A44460%2Fsignin-oidc&response_type=code&scope=openid%20profile%20role%20api1&code_challenge=nwqTm-vB3p39tOd-MGvwBLigILm3pqHgltE-lYw5cE0&code_challenge_method=S256&nonce=638043146265425402.ZmUwNDVjNTUtMzk0YS00YjJiLWJjMTUtOGI4YTY4MjY3OTY5MTRiYjIxMDUtYzQ4YS00ZGI0LThhN2EtODYyMDQwODRiNDk4&state=CfDJ8GjV4rteP2NCot0f0GPOVydPu1Wk5fn_fo1j2qAo_31oep1EIa9kCEvj37lYaNjQf1dwOQlSfBfQuWAHXU7h3z7vg9ByIFuy7ljx4dkjowIai_XzlKe-Ix2HNwb6HSOrVDQj8GUYtGRDy97K_ueGpO9sF0x6lbr6qDqBqte8OTwvG8hTFPL9KmLf09NXBfaJcI8GQgmk7V_74mGvCMP2ylV5Wwu0xPByKgRi4HvAyqEJ09vpBMvpeB0MGmuewMloEDvGU3TVGcAdn7kuStaHZskol40M130XxjE5O1EqESAWOSr8855h5g-eCfvaU8KIrQlB8X1NIJ1RCwiZ0d_bINZrKRHbGImxyoZUXYXNMX1HkXPNdkZtbkGhKvF3zYyNLw&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.0.0 responded 302 in 438.1225 ms

[23:43:47 Verbose] Duende.IdentityServer.Hosting.EndpointRouter
No endpoint entry found for request path: /home/error

[23:43:47 Verbose] Duende.IdentityServer.Services.DefaultIdentityServerInteractionService
Error context loaded

[23:43:47 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /home/error?errorId=CfDJ8GjV4rteP2NCot0f0GPOVydCHqhbLo4uSpO0YYXvITdQKGyB0s4pXapROSL0CvT7PA2qcY3P5_2CEsha14s1HZLNQOaVsGxj9vAU8V9b3hJY67MukhJxer9hO0XY4AwZat5Ncu5M9afp1-x8AkkD1dPHFCoZveV8-i2dAQnHFgVgLVmNU7_J7JAy8ICzMnl0XYQSatrQibO2aK3NfSVnElx76XaXnLyHSVkKidFkV0ceuRSLWY1zchwRWrgxYXhkjzFwITfPEheybRfRQBSJXsmKjh_rPDs3cH4IXTwbirE6MEWsqU2HX5lBuAckkRhmM9nbvRX8bBlRctq0SNzeKAw responded 200 in 58.9206 ms

[23:43:47 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /lib/bootstrap/dist/css/bootstrap.min.css.map responded 200 in 45.9021 ms

[23:43:47 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /lib/bootstrap/dist/js/bootstrap.bundle.min.js.map responded 200 in 36.6562 ms
```

**Comment by gundogduhasan** [comment] 2022-11-21 08:20
Any update about this question?

**Comment by gundogduhasan** [comment] 2022-11-21 21:39
BFF is already running on https://localhost:44460. And my entaire login operation runs on https.

**Comment by josephdecock** [comment] 2022-11-21 21:49
Can you try again to capture the network trace during the login process? In chrome, you need to check the "Preserve log" option to see requests on page loads and redirects:
![image](https://user-images.githubusercontent.com/1145533/203164927-cb05b148-6996-453e-abb9-1f7bd2db1053.png)

**Comment by gundogduhasan** [comment] 2022-11-22 09:14
Hi @josephdecock. I did what you said. I saved all login process via "Save all as HAR with content". Log file is too large to added as comment here. I added as zip. I hope that's what you want.
[localhost.zip](https://github.com/DuendeSoftware/Support/files/10065851/localhost.zip)

**Comment by josephdecock** [comment] 2022-11-29 00:29
I recommend that you try removing IIS Express and running directly in kestrel. If that works, then you know that the problem is related to the way that IIS Express handles the HTTPS connection - I suspect that somehow IIS Express isn't passing along the right information to kestrel for it to know that the request is using HTTPS.

**Comment by josephdecock** [comment] 2022-12-10 06:11
Any more updates here? Can we close this issue?

**Comment by gundogduhasan** [comment] 2022-12-10 11:17
Hi @josephdecock, unfortunately I didn't try your advice yet. After I tried, if I still the same issue can I reopen? If that's okay we can close this issue.

**Comment by josephdecock** [comment] 2022-12-10 18:52
That's quite all right. I will close this issue for now, but feel free to reopen if you need more help.

**Closed** 2022-12-10 18:53 UTC
Labels: BFF, question
