### ISSUE TITLE
Identity Server Signout - not redirecting to the redirect url

### ISSUE THREAD

**Issue by fdagdagan** [DuendeSoftware/Support#843] opened 2023-08-21 15:08 UTC
**Which version of Duende IdentityServer are you using? 6.1.7

**Which version of .NET are you using? 6.0.11

User click on "Logout"
The client application initiates a logout to make sure all the session are closed. This will initiate the call to the endsession endpoint as per the OIDC flow.
In most cases endsession endpoint lands the user in sign in screen with appropriate redirect uri "
[https://xxxxxxxxxxxxxxx/#/dashboard/home]". 
But in this session time out case though GPEL 2.0 sends the proper client name, for some reason Identity Server is not attaching the redirect uri.

Redirect URL = https%3A%2f%XXX-XXX-XXX.XXXX%2f%23%2fdashboard

1.Client frontend redirects the user to below end point when user click on sign in the popup 
Request URL: [https://xxxx-xxxxxx/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IjJGNDM1NUJDNjJGNUM1NEE2RjgwRjM3QUQxRjE0NjBDQ0REQzdBNERSUzI1NiIsIng1dCI6IkwwTlZ2R0wxeFVwdmdQTjYwZkZHRE0zY2VrMCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2lkZW50aXR5LXVhdC5pbnQubnAuZGFsLTIub3NzMi5tcnNobWMuY29tIiwibmJmIjoxNjkxNjgzMTM1LCJpYXQiOjE2OTE2ODMxMzUsImV4cCI6MTY5MTY4MzQzNSwiYXVkIjoiR1BFTEZyb250RW5kIiwiYW1yIjpbInB3ZCJdLCJub25jZSI6IlJHMHpZbTVHWm0xR1JWSnhiMkpYYkZoamQyOHhNbkp6TW5sRlVTMDVaeTFPY1g1UlQzZGZXbmd1VWpSNSIsImF0X2hhc2giOiJqY0VRcTdISTZwZWJaMnZSbzNXMzR3Iiwic2lkIjoiMTI0QTMwNkRGNjY5OUU0ODE5MUNENTcwRjZDOUY0RUYiLCJzdWIiOiI2NmEzNGJiOC1iOTZjLTQwOWQtODUxMi00ZWRjNTg3M2I4MDQiLCJhdXRoX3RpbWUiOjE2OTE2ODI5MDQsImlkcCI6ImxvY2FsIn0.D6QnlUrrXrAon0fME5KaxSTTOPGlW_6caBMRYqVUIQmUfzqzefHGDeaBd55oDC6ybKOXf70g7vxWCYFbGcqL7gRr7keY-CNRlT4RP2zCc-M04XSHSZcXLN5YjszHMT2kSgUcSId3B3HKOszr37y-KH7fEqGF1PiQleqIblPJQOi5pWSs_j8egQzk2iSPECwUuAeZZJVdAfc2y7asGPYpO9RKW1QfwNkdSV9ELtNidl4aTwg4Bx0y1b280hI_Y-MHKYKuUxLQRQXRfFCOa4ffBXGmYFOLFVLkHKlELeOA10jDT1h034mbz66jAf3z8NEPxSRFvPzwTvNVi8vi3n7uaQ&post_logout_redirect_uri=https%3A%2f%2fxxxx-xxx-xxxxxx%2f%23%2fdashboard](https://xxxxx-xxxxxxxxx/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IjJGNDM1NUJDNjJGNUM1NEE2RjgwRjM3QUQxRjE0NjBDQ0REQzdBNERSUzI1NiIsIng1dCI6IkwwTlZ2R0wxeFVwdmdQTjYwZkZHRE0zY2VrMCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2lkZW50aXR5LXVhdC5pbnQubnAuZGFsLTIub3NzMi5tcnNobWMuY29tIiwibmJmIjoxNjkxNjgzMTM1LCJpYXQiOjE2OTE2ODMxMzUsImV4cCI6MTY5MTY4MzQzNSwiYXVkIjoiR1BFTEZyb250RW5kIiwiYW1yIjpbInB3ZCJdLCJub25jZSI6IlJHMHpZbTVHWm0xR1JWSnhiMkpYYkZoamQyOHhNbkp6TW5sRlVTMDVaeTFPY1g1UlQzZGZXbmd1VWpSNSIsImF0X2hhc2giOiJqY0VRcTdISTZwZWJaMnZSbzNXMzR3Iiwic2lkIjoiMTI0QTMwNkRGNjY5OUU0ODE5MUNENTcwRjZDOUY0RUYiLCJzdWIiOiI2NmEzNGJiOC1iOTZjLTQwOWQtODUxMi00ZWRjNTg3M2I4MDQiLCJhdXRoX3RpbWUiOjE2OTE2ODI5MDQsImlkcCI6ImxvY2FsIn0.D6QnlUrrXrAon0fME5KaxSTTOPGlW_6caBMRYqVUIQmUfzqzefHGDeaBd55oDC6ybKOXf70g7vxWCYFbGcqL7gRr7keY-CNRlT4RP2zCc-M04XSHSZcXLN5YjszHMT2kSgUcSId3B3HKOszr37y-KH7fEqGF1PiQleqIblPJQOi5pWSs_j8egQzk2iSPECwUuAeZZJVdAfc2y7asGPYpO9RKW1QfwNkdSV9ELtNidl4aTwg4Bx0y1b280hI_Y-MHKYKuUxLQRQXRfFCOa4ffBXGmYFOLFVLkHKlELeOA10jDT1h034mbz66jAf3z8NEPxSRFvPzwTvNVi8vi3n7uaQ&post_logout_redirect_uri=https%3A%2f%XXX-XXX-XXX.XXXX%2f%23%2fdashboard)

2.However after  logout URL is redirect to  below URL 
Request URL: https://xxxx-xxx.xxxxxx/Account/Logout?logoutId=CfDJ8KeJvJ3vjAtJiOZw-c4yHVV4AEjAQlQJVsB6hKjPoxIFLSFIWfC7FnSq064432G9g2j53evBFL-J-uPcdjf2IegCCLtKiae16jXWCamr0GFub41mAEMHq-F3w3kzRuetoImvOYtysOuPU1Lm1HzV1-XB5Y45JQwXWPpBuciXgZhB3hrCZD9yRrmgjiXZOj-tKT3OeIFFFvO2myPO0kUJd-8bfONi7PMqvDNDb3ZOwm2YLmR70MjxDIuWhJjh2XpkuQ

3.logout URL redirects the user to Idp sign in URL  below is missing redirect Uri to the client

Request URL: [https://xxxx-xxx.xxxxxx/Account/Login?ReturnUrl=%2fAccount%2fLogout%3FlogoutId%3DCfDJ8KeJvJ3vjAtJiOZw-c4yHVV4AEjAQlQJVsB6hKjPoxIFLSFIWfC7FnSq064432G9g2j53evBFL-J-uPcdjf2IegCCLtKiae16jXWCamr0GFub41mAEMHq-F3w3kzRuetoImvOYtysOuPU1Lm1HzV1-XB5Y45JQwXWPpBuciXgZhB3hrCZD9yRrmgjiXZOj-tKT3OeIFFFvO2myPO0kUJd-8bfONi7PMqvDNDb3ZOwm2YLmR70MjxDIuWhJjh2XpkuQ](https://xxxxx-xxx.xxxxxx/Account/Login?ReturnUrl=%2fAccount%2fLogout?logoutId%3DCfDJ8KeJvJ3vjAtJiOZw-c4yHVV4AEjAQlQJVsB6hKjPoxIFLSFIWfC7FnSq064432G9g2j53evBFL-J-uPcdjf2IegCCLtKiae16jXWCamr0GFub41mAEMHq-F3w3kzRuetoImvOYtysOuPU1Lm1HzV1-XB5Y45JQwXWPpBuciXgZhB3hrCZD9yRrmgjiXZOj-tKT3OeIFFFvO2myPO0kUJd-8bfONi7PMqvDNDb3ZOwm2YLmR70MjxDIuWhJjh2XpkuQ)

4.when user submits credential, redirect user to below login URL with redirect Uri

Request URL: [https://xxxx-xxx.xxx.xxx.xxx-xxxxxxx/Account/Login?ReturnUrl=%2fconnect%2fauthorize%2fcallback%3Fresponse_type%3Dcode%26client_id%3DGPELFrontEnd%26state%3DODNqdTlKclpOVEZhQVdsT3VXbFNIRFZRbDk5WWQ2YkdDN0dVaVFUTUp2UjVL%26redirect_uri%3Dhttps%253A%252F%252https%3A%2f%XXX-XXX-XXX.XXXX%2f%23%2fdashboard%26scope%3Dopenid%2520profile%2520offline_access%26code_challenge%3D9zNIEiL5QurTB69NINMG9HMTICWeOAI6Z8jgq7_9jNk%26code_challenge_method%3DS256%26nonce%3DODNqdTlKclpOVEZhQVdsT3VXbFNIRFZRbDk5WWQ2YkdDN0dVaVFUTUp2UjVL%26audience%3Dhttps%253A%25](https://xxxx-xxx.xxxxxx/Account/Login?ReturnUrl=%2fconnect%2fauthorize%2fcallback?response_type%3Dcode%26client_id%3DGPELFrontEnd%26state%3DODNqdTlKclpOVEZhQVdsT3VXbFNIRFZRbDk5WWQ2YkdDN0dVaVFUTUp2UjVL%26redirect_uri%3Dhttps%253A%252F%252Fhttps%3A%2f%XXX-XXX-XXX.XXXX%2f%23%2fdashboard%26scope%3Dopenid%2520profile%2520offline_access%26code_challenge%3D9zNIEiL5QurTB69NINMG9HMTICWeOAI6Z8jgq7_9jNk%26code_challenge_method%3DS256%26nonce%3DODNqdTlKclpOVEZhQVdsT3VXbFNIRFZRbDk5WWQ2YkdDN0dVaVFUTUp2UjVL%26audience%3Dhttps%253A%252F%252Fxxxx-xxxxxxx%252F%26prompt%3Dlogin%26suppressed_prompt%3Dlogin)

Any help or suggestions to solve this issue. Thank you!

**Comment by josephdecock** [comment] 2023-08-22 20:32
The initial request to the endsession endpoint followed by a redirect to the account/logout page is normal. It looks like the problem is originating at that point, when your logout page redirects to the login page. Your logout page is UI code under your control, so its hard to know why exactly it decided to redirect to account login. You should make sure that the logout page allows anonymous access (`[AllowAnonymous]`) and doesn't try to issue an authentication Challenge.

**Comment by josephdecock** [comment] 2023-08-30 21:29
Any update here? Can we close this issue?

**Comment by josephdecock** [comment] 2023-09-08 17:01
Closing, but feel free to reopen if necessary.

**Closed by josephdecock** 2023-09-08 17:01 UTC
Labels: IdentityServer, question
