### ISSUE TITLE
Dynamic Identity Provider

### ISSUE THREAD

**Issue by AnBz03** [DuendeSoftware/Support#809] opened 2023-08-01 07:49 UTC
concerning the dynamic identity provider in the quickstart there is a mistake concerning the allowed identity provider for each client

            if (client.IdentityProviderRestrictions != null && client.IdentityProviderRestrictions.Any())
            {
            providers = providers.Where(provider => client.IdentityProviderRestrictions.Contains(provider.AuthenticationScheme)).ToList();
            }
you need to fix the condition in order to become 
  providers = providers.Where(provider => ! client.IdentityProviderRestrictions.Contains(provider.AuthenticationScheme)).ToList();

**Comment by josephdecock** [comment] 2023-08-04 19:21
Duplicate of #806

**Closed by josephdecock** 2023-08-04 19:21 UTC
Labels: IdentityServer
