### ISSUE TITLE
Role base authorization and authentication

### ISSUE THREAD

**Issue by NamanGajjar26** [DuendeSoftware/Support#708] opened 2023-06-02 08:36 UTC
We are using aspnetidentity, how to authorized controller and/or method in mvc web client and web Api (>net Framework 4.8)

**Comment by josephdecock** [comment] 2023-06-02 18:54
This is a pretty big topic. Some beginning resources to help you get started:

- [Microsoft's Docs](https://learn.microsoft.com/en-us/aspnet/web-api/overview/security/authentication-and-authorization-in-aspnet-web-api) on Web API authentication and authorization]
- More [guides from microsoft ](https://learn.microsoft.com/en-us/aspnet/mvc/overview/security/) on mvc security
- [Our sample](https://github.com/DuendeSoftware/Samples/tree/main/various/clients/Owin) showing how to get perform basic operations with an Owin host

**Comment by NamanGajjar26** [comment] 2023-06-08 11:44
I Tried Owin Samples but getting same Authorization 401 error.

**Comment by josephdecock** [comment] 2023-06-14 14:57
Can you go into more detail please? Are you running the latest code from the sample repo without changes and getting 401 errors? If so, when and where are they occurring, specifically? What do you see in the logs?

**Comment by NamanGajjar26** [comment] 2023-06-20 09:11
I am using same method without any changes still same error 401

**Comment by NamanGajjar26** [comment] 2023-06-21 10:58
My project in Identity server in .net core mvc ,Web application in .net Framework 4.8 and Api in .net Framework 4.8

**Comment by josephdecock** [comment] 2023-06-26 22:23
I believe this is a duplicate of #705, so I'll close and continue the conversation there.

**Closed by josephdecock** 2023-06-26 22:23 UTC
Labels: IdentityServer, question
