### ISSUE TITLE
Issues with azure application Gateway

### ISSUE THREAD

**Issue by kamicoder** [DuendeSoftware/Support#1094] opened 2024-02-01 14:15 UTC
**Which version of Duende IdentityServer are you using?**
Duende IdentityServer v6

**Which version of .NET are you using?**
dotnet 6

**Describe the bug**
We use an Implicit flow with reference token. The client is written in Angular 2 with "angular-oauth2-oidc"
All works fine, but when we protect ours apps behind an azure Application Gateway, several rules block IdentityServer :
-  Randomly on logout, logoutId has too many special characters : 942430 : Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (12) 
- On login, ReturnUrl is encoded twice : 920230 : Multiple URL Encoding Detected
- On login, cookies with SQL comment : 942440 : SQL Comment Sequence Detected
-  On login during an azure AD connection : 942450 : SQL Hex Encoding Identified.

**Expected behavior**
We want to activate all rules to secure our apps

**Comment by josephdecock** [comment] 2024-02-09 03:20
Unfortunately, this is a known issue in ASP.NET's OIDC implementation. The problem is that the values that are being flagged by the gateway are all data protected using ASP.NET data protection, and the data protection process sometimes includes the special characters that set off these rules. Microsoft/the ASP.NET team doesn't intend to change their cryptographic implementation details to fix this problem - which is actually very reasonable, as data protection is extremely widely used and changing it would be very impactful. There isn't a good way for IdentityServer to mitigate the problem, as we rely on this infrastructure from ASP.NET. And the rules in the gateway are generally sensible rules too, so I wouldn't expect them to relax the rules either. The only thing to do is to change the configuration of the WAF to add the necessary exceptions.

For more info from the ASP.NET team, see their issue here: https://github.com/dotnet/aspnetcore/issues/4589.

**Comment by kamicoder** [comment] 2024-02-09 07:24
Hello, Ok for the cryptographic issue, we will add some exceptions.
However, i think the issue "ReturnUrl is encoded twice" isn't an  "ASP.NET cryptographic issue".
Do you need more information for this?

**Comment by josephdecock** [comment] 2024-02-09 15:26
For the double encoding, that's working as designed. The reason we need that is that there are 2 redirects, and we need to persist the url parameter through the first one.

**Comment by josephdecock** [comment] 2024-02-18 19:31
Is anything further needed on this issue, or should we close it?

**Comment by kamicoder** [comment] 2024-02-19 06:49
It's OK for me.
Thanks for your reply.

**Closed** 2024-02-19 06:49 UTC
Labels: IdentityServer, question
