### ISSUE TITLE
License Key in Dev Environment

### ISSUE THREAD

**Issue by bhammed** [DuendeSoftware/Support#1105] opened 2024-02-08 23:33 UTC
**Which version of Duende IdentityServer are you using?**  6.1.1

**Which version of .NET are you using?**

**Describe the bug**

I installed UI templates and couldn't run the Duende project because of an error about license. This is in Dev environment and for learning purpose. I also noticed that a reference was made to a License file in the root but I don't have that.

**To Reproduce**
Install Duende server 6.1.1
Install UI template

Steps to reproduce the behavior.

**Expected behavior**

I expected the project to run; displaying the IdentityServer interface

**Log output/exception with stacktrace**
![image](https://github.com/DuendeSoftware/Support/assets/47109829/c82c2858-d911-4c31-9031-c25595347354)

```
data
```

**Additional context**

**Comment by josephdecock** [comment] 2024-02-09 00:47
The cause of this problem is a mismatch between UI template version and IdentityServer Versions.

We added a class in the most recent release of IdentityServer that allows the front page ui to say what the license status is. This is purely informational, but it doesn't exist in the older version of IdentityServer that you have installed.

You can solve this by using our latest templates, by upgrading to IdentityServer 7, or by removing the part of the UI that displays license info.

**Comment by josephdecock** [comment] 2024-02-18 20:05
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment] 2024-03-07 14:41
Closing due to inactivity, but feel free to reopen if necessary.

**Closed by josephdecock** 2024-03-07 14:41 UTC
Labels: IdentityServer, question
