### ISSUE TITLE
Consider aborting refresh token process when request is canceled

### ISSUE THREAD

**Issue by geoffroybraun** [DuendeSoftware/Support#815] opened 2023-08-03 07:25 UTC
Using .Net 7 and DuendeServer 6.2.0, I'm facing an issue from an SPA. When requesting a refresh token using the endpoint `connect/token`, it might happen the request is canceled. Unfortunately, the server does not abort the process and keep invalidating the current refresh token before generating a new one. This lead to a `Bad request` response when retrying to refresh a token because, for the server, it has already been consumed.

Here a sequence that can lead to the issue:

* authenticate an end-user
* refresh the token but cancel the request before getting the response
* refresh the same token
* a `Bad request` response is received

I believe providing a cancellation token to the `ProcessAsync` method of the `TokenEndpoint` class can be a solution, as it would be usable within the refresh token renewal process by simply checking if the token has been canceled before going further.

Please let me know if something is not clear, cheers!

**Comment by AndersAbel** [comment] 2023-08-04 21:23
Adding a cancellation token would indeed mitigate the problem in those cases where the request is cancelled before the old token has been marked as expired. However, there could be cases where the request runs to completion on the server side but the client still do not get the response due to e.g. a late client-side abortion or a net work issue. So while a cancellation token would make the situation better, it would not completely solve it.

The request token rotation is prone to errors, both for browser and server based client applications. For browser based applications where the tokens are handled by the browser, the OAuth2 security best current practice mandates refresh token rotation.

Our recommended architecture for browser based applications is to use the BFF, Backend For Frontend, pattern. With that, the browser based application's authentication and token handling is moved to the server side. Once being server side, the client can keep a secret and be a confidential client. And for confidential clients, refresh token rotation is not required. This is a much more reliable approach as it completely removes the need for handling token rotation.

Do you have any further details to share about when this is happening? Based on the problems you are facing, to what extent do you think that adding a cancellation token would solve the issue?

**Comment by geoffroybraun** [comment] 2023-08-07 12:50
Hi @AndersAbel ! 

First of all, thank you for the perfectly answer. The cancellation token suggestion was a very basic one, the first thing we had in mind when trying to reproduce the issue on the server-side, so I completely understand this does not entirely solve the issue.

Here are a few more details about our issue with refresh tokens:
* Our OpenID client is an Angular SPA, which uses `authorization_code` flows to authenticate an end-user.
* All flows are handled by the Angular [angular-auth-oidc-client](https://npmjs.com/package/angular-auth-oidc-client) in version 15.0.2.
* This library performs http calls to the `/connect/token` endpoint to check the current user's access token is stil valid.
* However, users might not use their browser or even their laptop for minutes or hours. Therefore, the browser seems to enter a _sleeping mode_ which cancels requests after less than a second (we have a lot of AppInsights traces with that behavior).
* If the refresh token request has been canceled by the browser, the token is still invalidated and refreshed by the server.
* Finally, when refreshing the old token, because the new one has never been received by the browser, it is considered invalid, as it has already been refreshed.

Please let me know if tyou need further information. Cheers!

**Comment by josephdecock** [comment] 2023-08-07 21:36
I agree with Anders, that the BFF pattern is our first choice/recommendation for browser based applications. However, we know that there are lots of existing applications like yours that perform the OIDC handshake in the browser and it isn't always easy to make architectural changes. So, our refresh token infrastructure contains configuration options and extensibility points that allow you to have more control over the behavior of refresh tokens. In particular, you can add custom code that will decide if you want to use a refresh token after it has been consumed. We describe this in detail in our docs [here](https://docs.duendesoftware.com/identityserver/v6/tokens/refresh/#rotation) (see especially the section on accepting consumed tokens). 

Typically, what I've needed to do in the past is allow a consumed token to be used for a short time after it is consumed. Usually, that resolves the problems that I see with consumed tokens, because most of the problems I've seen are caused by transient network outages. In that case, your customization can just say "If the token was consumed in the last n minutes, it can still be used" (where n is some small number, like 5). I'm less familiar with this "sleeping mode" that you're describing, which might be harder to allow for (if indeed users are sending and then immediately canceling requests for hours). If your front-end code (or the libraries you're using) are doing that, it will be very hard to solve this from the IdentityServer side. Your best option in that case is to fix the angular application so that it stops sending and then canceling token requests.

**Comment by AndersAbel** [comment] 2023-08-09 08:39
Thanks @geoffroybraun for providing more context. The situation you describe is just further proof that the concept of refresh token rotation is brittle. Even with server side applications we have seen that using refresh token rotations is prone to race conditions resulting in tokens incorrectly being invalidated and the user logged out. Trying to be permissive on token reuse for legitimate users while still providing protection against attackers is extremely difficult, if not impossible.

Philippe de Ryck has en excellent [article](https://www.pingidentity.com/en/resources/blog/post/refresh-token-rotation-spa.html) on the security implications on tokens in the browser and why using the BFF pattern to move the tokens to the backend is recommended.

As Joe points out, it is possible to lax the refresh token reuse protection. But doing that as much as would be required to cover the sleep scenario essentially invalidates the protection given by refresh token rotation completely. Then you might as well switch off refresh token rotation completely to not get a false sense of security. But none of these are good solutions from a security standpoint - migrating to a BFF is the right way to solve this problem.

**Comment by josephdecock** [comment] 2023-08-30 21:46
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment] 2023-09-08 17:02
Closing, but feel free to reopen if necessary.

**Closed by josephdecock** 2023-09-08 17:02 UTC
Labels: IdentityServer, feature request, investigating
