### ISSUE TITLE
Question on Cors Database Values

### ISSUE THREAD

**Issue by OblivionSY** [DuendeSoftware/Support#491] opened 2023-02-08 00:35 UTC
**Which version of Duende IdentityServer are you using?**
6.1.4

**Which version of .NET are you using?**
6.0.13

**Describe the bug**

![image](https://user-images.githubusercontent.com/3511993/217397964-5a57854a-67ae-4c36-8f28-5424f714109b.png)
If cors code is added like the above, does this override any cors configuration in the `ClientCorsOrigins` table? Should this be completely ripped out and all configuration added to that table? The current implementation in the screenshot seems to be the worst of all worlds. The docs talk about the `ICorsPolicyService`  (https://docs.duendesoftware.com/identityserver/v6/tokens/cors/) which would appear to be the better way to add cors specifically, but before ripping it out and trying it would be great to have a yes/no if that was the correct approach?

To clarify, if all cors are moved into `ClientCorsOrigin` table, is that sufficient and will they be picked up automatically (if that manual cors code is removed)

Many thanks

**Comment by josephdecock** [comment] 2023-02-08 01:57
Adding a policy like this doesn't override the cors configuration in the clientCorsOrigins table. You don't need to define a policy like this unless you have your own custom endpoints in the identity server host that require CORS configuration. A policy like this won't ever be applied to the protocol endpoints that IdentityServer's middleware provides. The ICorsPolicyService provides a way to have customized logic determine if an origin should be allowed for CORS. For the most common/straightforward scenario, where you are simply configuring a list of allowed origins, you don't need to implement ICorsPolicyService. Putting all the allowed origins into the ClientCorsOrigin table should be all that you need to do.

**Comment by OblivionSY** [comment] 2023-02-08 16:58
Thank you for the reply. Unless I put the website into this cors section, I get a cors block when calling the token endpoint from the javascript (nuxt auth) website. Is there anything else I need to check to ensure it is configured. 
![image](https://user-images.githubusercontent.com/3511993/217597391-5dc7c12a-64c0-407b-9c0d-663bc60b23f3.png)
this is the cors table and the last one is the site
![image](https://user-images.githubusercontent.com/3511993/217593482-6eff6126-ffa3-4eb7-9f8d-1cbb419e7727.png)
this is the cors error I get. The cors site on the table is exactly the same as the referrer (except the referrer has the trailing slash)

Is there anything needed to the integration of IDS6? Here is how it is currently configured:
![image](https://user-images.githubusercontent.com/3511993/217599050-e9c3a413-b462-42d7-a27a-46b584fc9719.png)

Thanks for your assistance

**Comment by josephdecock** [comment] 2023-02-08 18:49
This looks like it is configured correctly.

> Unless I put the website into this cors section, I get a cors block

Sorry, I'm a little confused by this. You do need to put the origin into the ClientCorsOrigins table, and I would expect that without it, browsers would prevent you from making cross origin requests to IdentityServer.

**Comment by OblivionSY** [comment] 2023-02-08 19:14
Sorry for not being clear. Even with that domain/origin listed in the cors table in the database, it won't work unless I directly add it as a cors policy in the startup method. 

So ID#3 in the database screenshot is the correct origin listed in the table. However, when my js app is making a request, it can go through the authentication part, I enter username and password etc, but when it then tries to exchange and get the actual token, the cors issue is hit and it gets stuck in a loop requesting more codes, with a cors error reported on each request.

So, I wondered if that code block in startup was overriding the normal behaviour of IDS6 and disabling cors values set in the database. 

Hope that makes sense.

**Comment by josephdecock** [comment] 2023-02-08 19:31
Hmm, that seems strange. If you keep everything as simple as possible and only put the origins into the db, do you see anything in identityserver's logs? The CosPolicyProvider should Debug level messages that might help.

**Comment by OblivionSY** [comment] 2023-02-09 16:43
I removed the cors stuff from the startup and pushed the code to our test server. I then setup a local instance of our NUXT.js app and got it to authenticate against the test auth server. I could replicate the loop for auth code request. Adding the ClientCorsOrigins record then made the loop stop. However, I think there is bug.

To try and replicate the error, I change the Origin value and used a different port, so instead of https://localhost:44323, I used https://localhost:44325. The loop returned (as expected) I then changed the ClientId of the cors origin and **the loop still went away** so it doesn't matter what ClientId I use, so long as my https://localhost:44323. If I change the port again, the loop returns, irrespective of what clientId is entered.

Not sure it helps explain the production issue, but certainly an anomaly. Providing I can setup the services to use that client origins table in test, I will push it live and compare during downtime at the weekend.

**Comment by josephdecock** [comment] 2023-02-09 16:50
Sorry, but it's not totally clear from this what the bug is. I'm getting lost in the details of all the changes that you made. Is it possible that client configuration was cached and that made it seem like your changes weren't being respected?

**Comment by OblivionSY** [comment] 2023-02-09 17:27
I don't think it is cached. If I set:- invalid origin- invalid clientIdIt causes the loop, cors errorIf I set:- valid origin- invalid clientIdIt works. I works literally 1 second and breaks out the loop it is stuck in. So the update to origin is read immediately. Hope that is clearer (v hard to articulate tech stuff at times)

**Comment by josephdecock** [comment] 2023-02-09 17:48
Oh, I think I'm understanding - you seem to be expecting that when you register origins for a client id, only that client id will be able to use that origin. That's not how it works - when CORS makes its pre-flight requests, there's no way to know which client id will subsequently be used in the actual request. The CORS origin will be allowed if it is in the table at all.

**Comment by OblivionSY** [comment] 2023-02-09 18:15
Ok, I only spotted that behaviour as changing client ID seemed easier than testing changing the origin. 

I just republished the **cors code in startup** and actually it has **broken again**. The values in the cors client table are now not being used/working. It seems the answer is to have it removed, but it goes against what was said earlier about it not having any effect. Does it have the same policy name? `CorsPolicy` by any chance?

**Comment by josephdecock** [comment] 2023-02-09 19:15
The cors policy name defaults to "Duende.IdentityServer", and is configurable with `options.Cors.CorsPolicyName`.

**Comment by OblivionSY** [comment] 2023-02-09 20:11
Ok, not sure what is causing it then.

As soon as I add `services.AddCors` with the configuration options and call `app.UserCors("CorsPolicy")` the built in cors configured in the database stops working. Clearly the correct solution is to rip out the cors stuff in startup and configure in the db, so I will do that. Would be nice to know why it stops it working or why both don't combine. Thanks for your help.

**Comment by josephdecock** [comment] 2023-02-10 18:45
If in the end you have something that works, great! But there is always the possibility that you stumbled onto a bug. If you want to pursue that, are you able to reproduce the issue in a minimal sample? Maybe just create a new project from our templates, put in the cors policy in the way that breaks, and we can take a look. Or if you're satisfied with how things are working, we can just close this issue.

**Comment by OblivionSY** [comment] 2023-02-10 19:33
I think the repo steps would literally be take your working version of IDS, add cors section into startup and try connecting with a nuxt app (maybe any js would also work) on the auth_code flow. I will try and make a repo this week, but if you have an environment setup, maybe just add that cors definition into the startup and see if it still allows the js request on the token endpoint. I did redeploy last night without the cors section and the live authentication is now working as expected, having moved those cors configuration into the cors origin table. It was upgraded from v4, so maybe something is lingering there too.

**Comment by OblivionSY** [comment] 2023-02-13 22:02
Hello,

Here is the shorter Configure method:
```
public void Configure( IApplicationBuilder app )
        {
            InitializeIdentityServerDatabase( app );
            if ( Environment.IsDevelopment() )
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            app.UseStaticFiles();
            app.UseHttpsRedirection();
            app.UseCookiePolicy();
            app.UseRouting();
            app.UseCors( "CorsPolicy" );
            app.UseIdentityServer();
            app.UseAuthorization();
            app.UseEndpoints( endpoints =>
             {
                 endpoints.MapDefaultControllerRoute();
             } );
        }
```

and here is the full startup class (with the commented out cors code at the end of the section)

```
    public class Startup
    {
        public IWebHostEnvironment Environment { get; }
        public IConfiguration Configuration { get; }
        public Startup( IWebHostEnvironment environment, IConfiguration configuration )
        {
            Environment = environment;
            Configuration = configuration;
        }

        public void ConfigureServices( IServiceCollection services )
        {
            services.AddControllersWithViews();
            services.Configure<IISServerOptions>( iis =>
             {
                 iis.AuthenticationDisplayName = "Windows";
                 iis.AutomaticAuthentication = false;
             } );

            services.RegisterBaseRepositories();
            services.AddScoped<IBaseDbContext>( x => x.GetRequiredService<ApplicationDbContext>() );

            var connectionString = Configuration.GetConnectionString( "AuthConnection" );
            var migrationAssembly = typeof( ApplicationDbContext ).GetTypeInfo().Assembly.GetName().Name;

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            var builder = services.AddIdentityServer( options =>
                 {
                     options.Events.RaiseErrorEvents = true;
                     options.Events.RaiseInformationEvents = true;
                     options.Events.RaiseFailureEvents = true;
                     options.Events.RaiseSuccessEvents = true;
                 } )
                .AddAspNetIdentity<ApplicationUser>()
                .AddProfileService<DVProfileService>()
                .AddConfigurationStore( options =>
                 {
                     options.ConfigureDbContext = b =>
                         b.UseSqlServer( connectionString,
                             sql => sql.MigrationsAssembly( migrationAssembly ) );
                 } )
                .AddOperationalStore( options =>
                {
                    options.ConfigureDbContext = b =>
                        b.UseSqlServer( connectionString,
                            sql => sql.MigrationsAssembly( migrationAssembly ) );
                } );
            AddCertificate( builder );

            services.AddAuthentication()
            .AddGoogle( "Google", "Google", options =>
             {
                 options.ClientId = Configuration["ExternalProviders:Google:ClientId"];
                 options.ClientSecret = Configuration["ExternalProviders:Google:ClientSecret"];
                 options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme; // or IdentityConstants.ExternalScheme
                 options.Events = new OAuthEvents
                 {
                     OnRedirectToAuthorizationEndpoint = context =>
                     {
                         if ( context.Properties.Items.ContainsKey( "hd" ) )
                         {
                             var domain = context.Properties.Items["hd"];
                             context.Response.Redirect( context.RedirectUri + "&hd=" + System.Net.WebUtility.UrlEncode( domain ) );
                         }
                         return Task.CompletedTask;
                     },
                 };
             } )
            .AddFacebook( "Facebook", options =>
             {
                 options.ClientId = Configuration["ExternalProviders:Facebook:ClientId"];
                 options.ClientSecret = Configuration["ExternalProviders:Facebook:ClientSecret"];
                 options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
             } );

            // For each file in folder
            List<Saml2Provider> saml2Providers = new List<Saml2Provider>();
            DirectoryInfo d = new DirectoryInfo( "Saml2Configs" );
            FileInfo[] Files = d.GetFiles( "*.json" );

            foreach ( FileInfo file in Files )
            {
                using ( StreamReader r = new StreamReader( $"Saml2Configs/{file.Name}" ) )
                {
                    string json = r.ReadToEnd();
                    saml2Providers.Add( JsonConvert.DeserializeObject<Saml2Provider>( json ) );
                }
            }

            // Add the Saml 2 authentication
            foreach ( var saml2_provider in saml2Providers )
            {
                if ( saml2_provider.Active )
                {
                    services.AddAuthentication()
                        .AddSaml2( saml2_provider.Name, options => //saml2_provider.Name,
                    {
                        var ownId = "saml2/" + saml2_provider.Name;
                        options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                        options.SPOptions.EntityId = new EntityId( ownId );
                        options.SPOptions.ModulePath = "/Saml2/" + saml2_provider.Name; //Set the path for the meta data, and possibly return url for the provider

                        if ( !string.IsNullOrWhiteSpace( saml2_provider.MetaXML ) )
                        {
                            EntityDescriptor entityDescriptor = MetadataLoader.LoadIdp( $"Saml2Configs/{saml2_provider.MetaXML}" );
                            options.IdentityProviders.Add( new IdentityProvider( entityDescriptor.EntityId, options.SPOptions )
                            {
                                MetadataLocation = $"Saml2Configs/{saml2_provider.MetaXML}", //also can be url if desired
                            } );
                        }
                        else
                        {
                            options.IdentityProviders.Add(
                                new IdentityProvider( new EntityId( saml2_provider.IdentityProvider ), options.SPOptions )
                                {
                                    LoadMetadata = true,
                                    Binding = Sustainsys.Saml2.WebSso.Saml2BindingType.HttpRedirect
                                } );

                            options.SPOptions.ServiceCertificates.Add( new X509Certificate2( saml2_provider.ServiceCertificates ) );
                        }
                    } );
                }
            }

            services.AddScoped<IProfileService, DVProfileService>();
            services.AddDvBaseServices();
            services.AddMailings( Configuration );
            services.AddAutoMapper( typeof( BaseMapperProfiles ), typeof( RegistrationMapperProfiles ) );
            services.AddScoped<AccountContext>();
            services.AddScoped<IUserCreationService, UserCreationService>();
            services.AddScoped<IExternalCallbackService, ExternalCallbackService>();
            services.AddSingleton<IDSFactory>();
            services.ConfigureNonBreakingSameSiteCookies();

            //services.AddCors( options =>
            //{
            //    options.AddPolicy( "CorsPolicy",
            //        builder => builder.WithOrigins(
            //            urls.DigiRegBackEnd, urls.DigiRegFrontEnd,
            //            urls.DigiAskFrontEnd, urls.DigiAskBackEnd,
            //            // urls.DigiRegPortalBackEnd, urls.DigiRegPortalFrontEnd,
            //            "sso.test.brookes.ac.uk" )
            //        .AllowAnyMethod()
            //        .AllowAnyHeader()
            //        .AllowCredentials() );
            //} );
        }`

**Comment by brockallen** [comment] 2023-02-16 14:48
I don't see anything in there that shows or explains why the CORS config for the IdentityServer endpoints should not be working. Are you sure you have the origins in the DB as origins and not full URLs?

Also, I do see that your additional CORS config would also run on each request, so that explains why when you add a blanket and permissive policy that it would run, this allowing anything.

**Comment by OblivionSY** [comment] 2023-02-17 22:52
Yes, definitely checked the urls and they were not full Urls. The database values works perfectly, providing I don't define a cors section in the app start up.

**Comment by brockallen** [comment] 2023-02-17 23:21
> providing I don't define a cors section in the app start up.

Oh, maybe we missed this subtle point -- you say our DB CORS stuff works if you don't do your own CORS settings?

Ah, in that case, move your call to `UseCors` after the call to `UseIdentityServer` and see if that changes things.

**Comment by OblivionSY** [comment] 2023-02-20 23:49
Just for completeness, I did as you suggested, and it does now work. Any cors implementation must go after the call to AddIdentityServer. I will make a PR for the docs to add a line for this.

**Comment by brockallen** [comment] 2023-02-21 14:22
Ok, interesting that it did work. Thanks for the docs PR.

**Closed by brockallen** 2023-02-21 14:22 UTC
Labels: IdentityServer, question
