### ISSUE TITLE
Hitting .well-known/openid-configuration endpoint leads to memory leak

### ISSUE THREAD

**Issue by bhosale-ajay** [DuendeSoftware/Support#1397] opened 2024-09-10 17:36 UTC
**Which version of Duende IdentityServer are you using?**
7.0.6

**Which version of .NET are you using?**
8.0

**Describe the bug**
If hit /.well-known/openid-configuration multiple times it leads to memory leak.
Server is configured as follows

```
.Services
        .AddIdentityServer(options => {
              // set license keys, login, and logout urls etc
        })
       .AddInMemoryCaching()
       .AddConfigurationStore(options =>
        {
              //
        })
        .AddConfigurationStoreCache()
        .AddOperationalStore(options =>
        {
               //
        })
        .AddInMemoryIdentityResources(IdentityConfig.IdentityResources)
        .AddInMemoryApiScopes(IdentityConfig.Scopes)
        .AddInMemoryApiResources(IdentityConfig.Resources)
        .AddInMemoryClients(IdentityConfig.GetClients(fullBaseUrl, snowBaseUrl, snowSecretValue))
        .AddProfileService<CustomProfileService>();
```

**To Reproduce**

Steps to reproduce the behavior.
- Set up identity and fetch the wellknown endpoints.

**Expected behavior**
No memory leak should be observed.

Kindly let me know if there is any to way cache the output, and why adding  `AddInMemoryCaching` is not sufficient.

**Comment by bhosale-ajay** [comment] 2024-09-11 17:04
Considering everything else is same, if there are two endpoints within same asp .net project

1. /.well-known/openid-configuration

2. /ping which just returns a "pong" as response

If 10,000 non-concurrent requests made then mem usage looks like below

![image](https://github.com/user-attachments/assets/6135ce4f-6b77-418c-8c9f-3b48cdc21f2a)

**Comment by AndersAbel** [comment] 2024-09-16 11:37
Thanks for sharing these details. We have another issue that we are working on that gives timeouts on the discovery endpoint. I wounder if this could actually be the same issue. The memory leakage could be an early indication that something is wrong and then it would eventually freeze.

Could you please check your dependencies according to the notes in https://github.com/DuendeSoftware/Support/issues/1361#issuecomment-2352570891?

**Comment by bhosale-ajay** [comment] 2024-09-16 12:56
We do not have dependency on "Azure.Extensions.AspNetCore.DataProtection.Keys", But have dependency on "Azure.Identity" (1.12.0) and "Azure.Core" (1.41.0).
Do note that our services run on Docker image mcr.microsoft.com/dotnet/aspnet:8.0.3-alpine3.19-amd64

**Comment by bhosale-ajay** [comment] 2024-09-16 13:10
Our configurations are not dynamic. Is it possible to cache the response? The current code prepares /.well-known response by adds lots of entries to a Dictionary<string, object> and then serializing it to Json.

**Comment by AndersAbel** [comment] 2024-09-17 08:57
> We do not have dependency on "Azure.Extensions.AspNetCore.DataProtection.Keys", But have dependency on "Azure.Identity" (1.12.0) and "Azure.Core" (1.41.0). Do note that our services run on Docker image mcr.microsoft.com/dotnet/aspnet:8.0.3-alpine3.19-amd64

The issue is in Azure.Core version 1.41.0 and prior, could you please try updating Azure.Core to 1.42.0? There is o new `Azure.Identity` package that forces the dependency to be updated, so you would have to add a direct reference to `Azure.Core` version 1.42.0 to your project.

**Comment by bhosale-ajay** [comment] 2024-09-18 14:26
Updated to Azure Core 1.43, and no changes to memory consumption. My worry is that memory is not getting released.

![image](https://github.com/user-attachments/assets/ba4d4762-626e-4db1-8785-48f04b561c64)

**Comment by damianh** [comment] 2024-11-21 15:32
Hi @bhosale-ajay , a quick update, we are attempting to reproduce this internally. Could you kindly share your DataProtection setup? Are you using KeyVault / BlobStorage? Thanks.

**Comment by damianh** [comment] 2024-11-25 17:07
> Our configurations are not dynamic. Is it possible to cache the response? The current code prepares /.well-known response by adds lots of entries to a Dictionary<string, object> and then serializing it to Json.

I think we can do some optimisation here alright but not sure there's a memory leak.

Been doing some tests and I see memory growth when hammering `.well-known/openid-configuration` however it tops out at ~1GB (an interesting round number) and GC kicks in:

![Image](https://github.com/user-attachments/assets/380481fc-3e8d-494f-83b1-121e0eca299b)

This is with `<ServerGarbageCollection>true</ServerGarbageCollection>`. My understanding is that with this setting, memory usage will increase depending on amount available to the system. The process continues like this with no indications of further memory growth/leakage.

To compare, I ran the same test with `<ServerGarbageCollection>false</ServerGarbageCollection>` (aka "workstation" GC):

![Image](https://github.com/user-attachments/assets/5b7875c3-4888-43a6-acb0-7c108d9493e1)

Here memory topped out at 68MB and maintains it it. Obviously the GC is doing more work here managing the heap.

It's looking like to me that the memory leak is just normal memory growth experienced with `ServerGarbageCollection` set to true.

Thoughts?

**Comment by bhosale-ajay** [comment] 2024-11-27 15:30
In our setting the `ServerGarbageCollection` is not set. Are you testing this on a pod, or local machine? The problem is more visible when running the service on a pod.

**Comment by bhosale-ajay** [comment] 2024-11-27 15:36
This is screen shot from profiler, when running locally and hitting the wellknown endpoint. As you can see GC working on periodic basic, but unmanaged memory keep climbing.

Here load testing started around 7m mark. The first jump was before 6m mark was only for a single request. I can share more details if needed.

![Image](https://github.com/user-attachments/assets/f6c37436-f025-4142-8310-853dc85e69fa)

**Comment by damianh** [comment] 2024-11-28 14:13
I'm testing on a local machine. We don't have k8s pods setup but I don't think such is necessary - I'm seeing the memory growth too, but it reaches a limit. The process is not crashing and nor am I experiencing `OutOfMemoryExceptions`.

`ServerGarbageCollection` is true by default [in AspNet Core applications](https://learn.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-8.0#workstation-gc-vs-server-gc).

According to the docs, it may be more performant to use Workstation GC [with containerised apps](https://learn.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-8.0#gc-using-docker-and-small-containers).

To validate the thesis, could you please configure your app to use Workstation GC [using these instructions](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector) to adjust the `runtimeconfig.json` of your publish app and report back the memory consumption. 

Thank you!

**Comment by bhosale-ajay** [comment] 2024-12-04 15:14
Some additional findings, we use NpgSql and AzureWorkloadIdentity,

```
.AddOperationalStore(options =>
        {
            options.ConfigureDbContext = optionsBuilder => { optionsBuilder.UseNpgsqlWithAzureWorkloadIdentity(connectionString); };
            OperationalStoreOptionsConfig.Configure(options);
        })
```

On every request to /wellknown endpoint, the `options.ConfigureDbContext` also gets called, anyway it can be cached?

**Comment by bhosale-ajay** [comment] 2024-12-04 16:49
After adding pooling to operation store, the memory consumption is stable.

```
        .AddOperationalStore(options =>
        {
            options.ConfigureDbContext = optionsBuilder => { optionsBuilder.UseNpgsqlWithAzureWorkloadIdentity(connectionString); };
            // This fixed the leak, without enablepooling, The DBConext was getting created on every request
            options.EnablePooling = true;
            OperationalStoreOptionsConfig.Configure(options);
        })
```

**Comment by damianh** [comment] 2024-12-04 20:03
@bhosale-ajay Fantastic that you got to the bottom of this!. I spent a good portion of the day setting up benchmarking around producing and serializing the discovery document based on the exception message in your previous post. 

I'm going to investigate why we have this set to `false` by default. 

As this appears resolved, I'll close this issue.

**Closed by damianh** 2024-12-04 20:03 UTC
Labels: IdentityServer, priority
