### ISSUE TITLE
Using Remote APIs with MS Graph - Token request and management

### ISSUE THREAD

**Issue by joelhaugen** [DuendeSoftware/Support#929] opened 2023-10-04 15:29 UTC
**Which version of Duende BFF are you using?** 2.1.1
**Which version of .NET are you using?** 6.0

I am using BFF to support an SPA that accesses a local API and the Microsoft Graph API using BFF Remote APIs. 

I am using Azure AD as the authority for the local API token with an AAD App Registration as the client. 
I use the standard .NET and BFF pipelines for getting and managing this token. I am using BFF's Entity Framework server side sessions It is working well. 

For Graph, I need both a token for using Graph delegated (that is, user) permissions and application permissions. 
To get a token with the user permissions, I need to send an OAuth request to the MS login endpoint with these parameters:

requested_token_use: on_behalf_of
grant_type: urn:ietf:params:oauth:grant-type:jwt-bearer
assertion: [the apps oidc token]
client_id: [azure app id]
client_secret; [secret]
scope: [graph user permissions]

For the token with application permissions, I need to send a standard OAuth client_credentials token request using the app registration id and secret and the scope https://graph.microsoft.com/.default.

For both, the token endpoint is https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token.

I have registered custom authentication schemes that use a custom authentication handler.  The remote API mappings have authorization policies that require these schemes. 

The handler's **HandleChallengeAsync** first checks for a signin using the oidc signin scheme. If not present, it issues a challenge for the oidc scheme.  Once I have an oidc signin, I use an **HttpClient** to send a token request for either the user permissions or applications permissions token, depending on the challenge scheme. For the user permissions token, I send the oidc token in the assertion parameter.  After I receive the token, I store the token in the **AuthenticationProperties** object and call **Context.SignInAsync**.  See code below.

This works well and I can access the graph api using my local api endpoints mapped to the remote graph api.

However, after about 30 minutes the Duende **UserAccessAccessTokenManagementService** determines the refresh token for the on-behalf-of token needs to be refreshed.
In the process of executing the refresh, I get a 500 internal error in  Duende.AccessTokenManagement.OpenIdConnect.UserTokenEndpointService.RefreshAccessTokenAsync when it
tries to get the OpenConnectIdConfiguration.

If I close all browser windows and reload the app, it will reissue the challenge and get a new token and create a new aps.net sign-in cookie and bff session.

Here is a verbose trace of the graph request and error:

[09:03:12 INFORMATION RequestId:8000028b-000c-fa00-b63f-84710c7967bb TraceId:6185f74935a50f8260cde6f75d800fae]
Microsoft.AspNetCore.Routing.EndpointMiddleware
Executing endpoint '/api/graph/user/{**catch-all}'

[09:03:12 VERBOSE RequestId:8000028b-000c-fa00-b63f-84710c7967bb TraceId:6185f74935a50f8260cde6f75d800fae]
Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService
Starting user token acquisition

[09:03:12 DEBUG RequestId:8000028b-000c-fa00-b63f-84710c7967bb TraceId:6185f74935a50f8260cde6f75d800fae]
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: graph-user was successfully authenticated.

[09:03:12 DEBUG RequestId:8000028b-000c-fa00-b63f-84710c7967bb TraceId:6185f74935a50f8260cde6f75d800fae]
Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService
Token for user ***************************** needs refreshing.

[09:03:12 DEBUG RequestId:8000028b-000c-fa00-b63f-84710c7967bb TraceId:6185f74935a50f8260cde6f75d800fae]
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: graph-user was successfully authenticated.

[09:03:12 VERBOSE RequestId:8000028b-000c-fa00-b63f-84710c7967bb TraceId:6185f74935a50f8260cde6f75d800fae]
Duende.AccessTokenManagement.OpenIdConnect.UserTokenEndpointService
Refreshing refresh token: ********************************************

[09:03:12 INFORMATION RequestId:8000028b-000c-fa00-b63f-84710c7967bb TraceId:6185f74935a50f8260cde6f75d800fae]
Microsoft.AspNetCore.Routing.EndpointMiddleware
Executed endpoint '/api/graph/user/{**catch-all}'

[09:03:12 ERROR TraceId:6185f74935a50f8260cde6f75d800fae]
Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /api/graph/user/me responded 500 in 6.2155 ms
System.InvalidOperationException: Unable to load OpenID configuration for configured scheme: Object reference not set to an instance of an object.
   at Duende.AccessTokenManagement.OpenIdConnect.OpenIdConnectConfigurationService.GetOpenIdConnectConfigurationAsync(String schemeName) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/OpenIdConnectConfigurationService.cs:line 66
   at Duende.AccessTokenManagement.OpenIdConnect.UserTokenEndpointService.RefreshAccessTokenAsync(UserToken userToken, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/UserTokenEndpointService.cs:line 58
   at Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService.RefreshUserAccessTokenAsync(ClaimsPrincipal user, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/UserAccessTokenManagementService.cs:line 144
   at Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService.<>c__DisplayClass7_0.<<GetAccessTokenAsync>b__0>d.MoveNext() in /_/src/Duende.AccessTokenManagement.OpenIdConnect/UserAccessTokenManagementService.cs:line 101
--- End of stack trace from previous location ---
   at Duende.AccessTokenManagement.OpenIdConnect.UserTokenRequestSynchronization.SynchronizeAsync(String name, Func`1 func) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/UserTokenRequestSynchronization.cs:line 23
   at Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService.GetAccessTokenAsync(ClaimsPrincipal user, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/UserAccessTokenManagementService.cs:line 114
   at Microsoft.AspNetCore.Authentication.TokenManagementHttpContextExtensions.GetUserAccessTokenAsync(HttpContext httpContext, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /_/src/Duende.AccessTokenManagement.OpenIdConnect/TokenManagementHttpContextExtensions.cs:line 35
   at Duende.Bff.HttpContextExtensions.GetManagedAccessToken(HttpContext context, TokenType tokenType, Boolean optional, UserTokenRequestParameters userAccessTokenParameters) in /_/src/Duende.Bff/Extensions/HttpContextExtensions.cs:line 75
   at Duende.Bff.DefaultAccessTokenRetriever.GetAccessToken(AccessTokenRetrievalContext context) in /_/src/Duende.Bff/General/DefaultAccessTokenRetriever.cs:line 53
   at Duende.Bff.Yarp.RemoteApiEndpoint.<>c__DisplayClass0_0.<<Map>b__0>d.MoveNext() in /_/src/Duende.Bff.Yarp/RemoteApiEndpoint.cs:line 87
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Duende.Bff.Endpoints.BffMiddleware.Invoke(HttpContext context) in /_/src/Duende.Bff/EndpointProcessing/BffMiddleware.cs:line 77
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext

Here is the code for my GraphAuthenticationHandler.
[GraphAuthenticationHandler.txt](https://github.com/DuendeSoftware/Support/files/12805085/GraphAuthenticationHandler.txt)

Here is how I register the schemes in the web app Program.cs.

 .AddCookie(GraphConstants.UserSignInScheme, options =>
 {
     options.Cookie.SameSite = SameSiteMode.None;
     options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
 })
 .AddScheme<GraphAuthenticationOptions, GraphAuthenticationHandler>(GraphConstants.UserChallengeScheme, "Graph-User", options =>
 {
     options.SignInScheme = GraphConstants.UserSignInScheme;
     options.OidcSignInScheme = AppBackendConstants.OidcSignInScheme;
     options.OidcChallengeScheme = AppBackendConstants.OidcChallengeScheme;
     options.SaveTokens = true;
 })
 .AddCookie(GraphConstants.AppSignInScheme, options => {
     options.Cookie.SameSite = SameSiteMode.None;
     options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
 })
 .AddScheme<GraphAuthenticationOptions, GraphAuthenticationHandler>(GraphConstants.AppChallengeScheme, "Graph-User", options => {
     options.SignInScheme = GraphConstants.AppSignInScheme;
     options.OidcSignInScheme = AppBackendConstants.OidcSignInScheme;
     options.OidcChallengeScheme = AppBackendConstants .OidcChallengeScheme;
     options.SaveTokens = true;
 });

Here is how I set the authoriozation policy for the remote apis using a RemoteApiSettings section in my appsettings.json.

if (settings.RemoteApiMappings != null)
{
    foreach (var remoteApi in settings.RemoteApiMappings)
    {
        var conventionBuilder = builder.MapRemoteBffApiEndpoint(remoteApi.LocalPath, remoteApi.ApiAddress);
        if (remoteApi.AuthorizationPolicy != null)
        {
            conventionBuilder.RequireAuthorization(remoteApi.AuthorizationPolicy.Name);
            conventionBuilder.WithOptionalUserAccessToken();
            if (remoteApi.AccessTokenSignInScheme != null || remoteApi.AccessTokenChallengeScheme != null)
            {
                var tokenParms = new BffUserAccessTokenParameters(remoteApi.AccessTokenSignInScheme, remoteApi.AccessTokenChallengeScheme);
                conventionBuilder.WithUserAccessTokenParameter(tokenParms);
            }
        }
        else
        {
            conventionBuilder
                .RequireAuthorization()
                .RequireAccessToken();
        }

    }
}

**Comment by AndersAbel** [comment] 2023-10-05 08:27
The Duende.AccessTokenManagement library makes a couple of assumptions to be able to automatically retrieve the configuration for the token server:
* There is an OpenIdConnect scheme registered that is configured with the token server.
* The challenge scheme is set to the OpenIdConnect scheme.

The custom handler breaks these assumptions. That results in a null reference when OpenID Connect options cannot be resolved.

The configuration is retrieved by an implementation of `IOpenIdConnectConfigurationService`. You can replace the default implementation by calling `services.AddTransient<IOpenIdConnectConfigurationService, YourCustomOpenIdConnectConfigurationService>()` before the call to `services.AddBff()`.

**Comment by joelhaugen** [comment] 2023-10-09 14:15
I created a custom IOpenIdConnectConfigurationService that will look for a named OpenIdConnectClientConfiguration in the application configuration where the name matches the current challenge scheme. If found, it will return that configuration; otherwise, it will use the Duende service.  This appears to have fixed the issue.

My custom service:
public class OpenIdConnectConfigurationService : IOpenIdConnectConfigurationService
{
    private readonly Duende.AccessTokenManagement.OpenIdConnect.OpenIdConnectConfigurationService _duendeService;
    private readonly IOptions<UserTokenManagementOptions> _userAccessTokenManagementOptions;
    private readonly IOptionsMonitor<OpenIdConnectOptions> _oidcOptionsMonitor;
    private readonly IAuthenticationSchemeProvider _schemeProvider;
    private readonly IOptionsMonitor<OpenIdConnectClientConfiguration> _clientConfiguration;

    public OpenIdConnectConfigurationService(
       IOptions<UserTokenManagementOptions> userAccessTokenManagementOptions,
       IOptionsMonitor<OpenIdConnectOptions> oidcOptionsMonitor,
       IAuthenticationSchemeProvider schemeProvider,
       IOptionsMonitor<OpenIdConnectClientConfiguration> clientConfiguration
       )
    {
        _userAccessTokenManagementOptions = userAccessTokenManagementOptions;
        _oidcOptionsMonitor = oidcOptionsMonitor;
        _schemeProvider = schemeProvider;
        _clientConfiguration = clientConfiguration;
        _duendeService = new Duende.AccessTokenManagement.OpenIdConnect.OpenIdConnectConfigurationService(_userAccessTokenManagementOptions, _oidcOptionsMonitor, _schemeProvider);
        _clientConfiguration = clientConfiguration;
    }

    public Task<OpenIdConnectClientConfiguration> GetOpenIdConnectConfigurationAsync(string? schemeName = null)
    {
        //Check if a custom configuration exists for this scheme.
        if (schemeName != null)
        {
            var configuration = _clientConfiguration.Get(schemeName);
            //If a named configuration was not found a default object will be returned with all its properties set to default values.
            //If the Authority property is not empty, assume we have a valid named configuration for this scheme.
            if (configuration.Authority != string.Empty) return Task.FromResult(configuration); 
        }

        return _duendeService.GetOpenIdConnectConfigurationAsync(schemeName);
    }
}

Adding the service:
 builder.Services.AddTransient<IOpenIdConnectConfigurationService, Custom.OpenIdConnectConfigurationService>()

Creating the name configuration options:
 var configureGraphOpendIdClientConnectConfiguration = (OpenIdConnectClientConfiguration configuration) => {
      configuration.Authority = $"https://login.microsoftonline.com/{graphSettings.TenantId}";
      configuration.ClientId = settings.Client.Id;
      configuration.ClientSecret = builder.Configuration.GetClientSecret(settings.Client.Id);
      configuration.TokenEndpoint = $"https://login.microsoftonline.com/{graphSettings.TenantId}/oauth2/token";
      configuration.HttpClient = new HttpClient();
  };
  builder.Services.Configure(GraphConstants.UserChallengeScheme, configureGraphOpendIdClientConnectConfiguration);
  builder.Services.Configure(GraphConstants.AppChallengeScheme, configureGraphOpendIdClientConnectConfiguration);

**Comment by AndersAbel** [comment] 2023-10-17 11:20
Happy to hear that the problem is solved. Can we go on and close this issue?

**Comment by joelhaugen** [comment] 2023-10-17 18:33
The issue with the OpenIdConnectConfigurationService is resolved. But I’m still having an issue getting get my client credentials token for my Azure app to renew.  Are there tools in Dunde.Bff that I can use to manage this?  It’s not an OpenIdConnect token; just an OAuth token. Or should I register the scheme using AddOAuth()?

**Comment by joelhaugen** [comment] 2023-10-18 19:55
Thank you.  I was able to add some expired token handling in my custom authentication handler, so I’m good.
If you have not already, you may close my original issue.

**Closed** 2023-10-19 09:39 UTC
Labels: BFF, question
