### ISSUE TITLE
CSP Reported When unsafe-inline removed from style-src

### ISSUE THREAD

**Issue by dallasbeek** [DuendeSoftware/Support#1122] opened 2024-02-16 21:54 UTC
**Which version of Duende IdentityServer are you using?**
version 7.0.1

**Which version of .NET are you using?**
Net 8

**Describe the bug**
CSP violation after removing unsafe-inline from style-src

When signing out from my client application the browser throws a csp-violation

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**
Sign out from third party application without CSP

No CSP violations

**Log output/exception with stacktrace**

CSP Report
```
[
	{
		"age": 59029,
		"body": {
			"blockedURL": "inline",
			"disposition": "enforce",
			"documentURL": "https://{DuendeIdentityServer}/connect/endsession/callback?endSessionId=CfDJ8OtfYPUVRwFMrpnHMtKKNT......",
			"effectiveDirective": "style-src-elem",
			"lineNumber": 1,
			"originalPolicy": "default-src 'self'; script-src 'self' www.google.com www.gstatic.com; style-src 'self'; img-src 'self' data:; font-src 'self'; frame-src 'self' www.google.com; frame-ancestors https://{DuendeIdentityServer} https://{MyApplication}; block-all-mixed-content; upgrade-insecure-requests; report-to csp-endpoint",
			"referrer": "",
			"sample": "",
			"sourceFile": "https://{DuendeIdentityServer}/connect/endsession/callback",
			"statusCode": 200
		},
		"type": "csp-violation",
		"url": "https://{DuendeIdentityServer}/connect/endsession/callback?endSessionId=CfDJ8OtfYPUVRwFMrpnHMtKKNT.......",
		"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
	}
]
```

**Additional context**

[https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Endpoints/Results/EndSessionCallbackResult.cs](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDuendeSoftware%2FIdentityServer%2Fblob%2Fmain%2Fsrc%2FIdentityServer%2FEndpoints%2FResults%2FEndSessionCallbackResult.cs&data=05%7C02%7Cdallas%40musl.com%7C8c9697d71bad4cb94d9b08dc2f389d0a%7Cae5bf548f55c4739b3fff87b097eba71%7C0%7C0%7C638437167426334074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=3qi0AIu2IKOP2IWO4xcogvayP5tdi%2FxJ09WcdRdvvz8%3D&reserved=0)
 
Line 88
sb.Append("<!DOCTYPE html><html><style>iframe{{display:none;width:0;height:0;}}</style><body>");
 
Is the culprit.  I’m not sure what the proper fix would be, just letting you know.

**Comment by josephdecock** [comment] 2024-02-18 21:23
@AndersAbel, IIRC you recently made some improvements to the CSP headers (or maybe just investigated a similar issue).

**Comment by AndersAbel** [comment] 2024-02-19 22:25
The default CSP Header for the end session callback is

```
Content-Security-Policy:
default-src 'none'; style-src 'sha256-e6FQZewefmod2S/5T11pTXjzE2vn3/8GRwWOs917YE4='; frame-src https://client.example.com
```

where the `frame-src` is calculated based on the front channel logout notification URLs to be called. This is a very strict CSP that still allows the inline style.

Could it be that you accidentally overwrite the CSP we generate?

**Comment by dallasbeek** [comment] 2024-02-20 21:18
I sure was. Reordered my security headers to follow authentication and authorization in my startup and added logic to my content security header to not insert one if it's already set.

**Comment by AndersAbel** [comment] 2024-02-21 14:56
Looks like the problem is solved then? Can we go ahead and close this issue?

**Closed** 2024-03-05 15:18 UTC
Labels: IdentityServer, question
