### ISSUE TITLE
Your license for Duende IdentityServer only permits 1 number of issuers

### ISSUE THREAD

**Issue by d-manford** [DuendeSoftware/Support#1023] opened 2023-12-04 18:11 UTC
**Which version of Duende IdentityServer are you using?**

Identity Version 6 (latest version) Starter Edition

**Which version of .NET are you using?**
N/A

**Describe the bug**

We have a public app gateway (reverse-proxy) using 1 hostname/FQDN for login attempts (e.g. login.domainname.com) and the private hostname/FQDN on the identity server on the backend (e.g. login.cloutplatform.com). Logins are proxied to the front-end gateway using the public name and terminated there. The gateway then establishes the backend connection to the Identity server using the cloud platform hostname/FQDN.

We receive the below log message after login.

Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: ["https://login.domainname.com/identity","https://login.cloudplatform.net/identity"]. This might be due to your server being accessed via different URLs or a direct IP and/or you have reverse proxy or a gateway involved. This suggests a network infrastructure configuration problem, or you are deliberately hosting multiple URLs and require an upgraded license.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

We believe we have removed all references to the private/FQDN of our cloud platform and are only now using the public hostname/FQDN on the app gateway. However, we are still concerned that if there is code out there that may present the private URL. As a result, we are concerned we may receive the error again or that our installation may become non-functional. We are hesitant to release into production without assurances that this will not cause any problems. Can you confirm or advise on how to proceed or offer assurance there won't be any issues?

Thank you,

**Comment by d-manford** [comment] 2023-12-06 22:12
Hello,
Do we have any updates here? We have a pending deadline for a release and would like to get confirmation on the above.
Thank you

**Comment by leastprivilege** [comment] 2023-12-07 10:50
> ["https://login.domainname.com/identity","https://login.cloudplatform.net/identity"]
> We believe we have removed all references to the private/FQDN of our cloud platform and are only now using the public hostname/FQDN

This warning message means that you have indeed clients that use both domain names to access the OIDC provider. Since the hostname has a special meaning in the OIDC protocol, this is not recommended and may lead to further problems down the line.

You can get rid of the warning by setting a static issuer name in the options, but this will not get rid of the root cause.

**Comment by d-manford** [comment] 2023-12-08 23:50
Hello,

Thank you for the reply. In the interest of clarity, let me ask a follow up question. We are trying to be precise as we have a pending production deployment and do not want to experience unknown problems afterwards.

Our existing architecture for Identity login is the following:

-	Application Gateway/Reverse Proxy server accepts inbound requests for login to Public Endpoint (https:// login.publicdomainname.com).
-	TLS Traffic is terminated there. App Gateway/Reverse Proxy server then establishes TLS connection with the Backend Application (Identity App server) with Destination backend URL (https://login.privatecloudplatform.net)
-	While the above request is being processed the Request Header for “X-Forwarded-Host” value is rewritten to the variable {var_host} so that the Destination Backend Application receives the same Host Header as the initial public endpoint request. 

Do you see anything about this architecture that might cause issues or is not supported under the Duende Server? Are you familiar with other customers doing something similar? We are trying to ensure we have not left anything to chance or in an unsupported configuration for Duende. Can you further advise if this goes against best practice or is or isn’t recommended?

Thank you!

**Comment by leastprivilege** [comment] 2023-12-09 11:59
> Do you see anything about this architecture that might cause issues or is not supported under the Duende Server?

No - this is pretty idiomatic.

Still *something* seems to access the login server directly using the internal host name. That's what the log message indicates.

**Comment by lorddev** [comment] 2024-01-12 13:58
> You can get rid of the warning by setting a static issuer name in the options, but this will not get rid of the root cause.

@leastprivilege Like this?

```
"IdentityServerOptions": {
   "IssuerUri": "https://www.example.org"
}
```

I tried this and it didn't work. Is there a special syntax to get it to read from config?

**Comment by brockallen** [comment] 2024-01-15 14:41
You will have to configure the options manually: https://docs.duendesoftware.com/identityserver/v6/reference/options/

**Comment by lorddev** [comment] 2024-01-17 17:38
> You will have to configure the options manually: https://docs.duendesoftware.com/identityserver/v6/reference/options/

This seems to have solved it.

**Comment by AndersAbel** [comment] 2024-01-18 11:22
@d-manford Is this issue solved for you too? Can we close it?

**Comment by jesslilly** [comment] 2024-01-24 13:15
I am getting the same error message in my logs, but I do not have a reverse proxy set up.  The names of the web servers and the Identity Server are the names listed:

2024-01-22 15:29:21.3244|ERROR|Duende.License|Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 3. The issuers used were: https://web02.company.org/, https://account.company.org/, https://web03.company.org/

**Comment by jesslilly** [comment] 2024-01-28 13:36
No, just one @AndersAbel

**Comment by AndersAbel** [comment] 2024-01-28 18:43
@jesslilly The logs indicate that your IdentityServer has processed requests on all three host names.

if that is not intentional, you might want to review your infrastructure level setup to ensure that IdentityServer is only responding to one host name.

**Comment by josephdecock** [comment] 2024-02-08 23:19
Is anything further needed on this issue, or should we close it?

**Comment by jesslilly** [comment] 2024-02-13 14:29
I don't think anything is resolved yet, so can we keep it open?  The 2 extra servers listed are web servers, not identity servers.  So they are consumers only.

**Comment by jesslilly** [comment] 2024-02-13 17:49
Should I try the same solution?  It seems like it is only masking the problem.  This seems like an Identity Server bug to me.

**Comment by josephdecock** [comment] 2024-02-18 21:20
If you specify the issuer in the options, then IdentityServer will always use that issuer. If you don't, IdentityServer will infer the issuer, based on the incoming request. IdentityServer tracks in memory which issuers it has used, and verifies that if you use multiple issuers, your license allows that. So, the log messages mean that somehow requests have been handled by your identity server that used all 3 hosts. 

It is always possible that there is a bug we don't know about, but validating the issuer is code that is exercised by basically every request to every IdentityServer implementation. 

One way to quickly check is to see if requests to https://web02.company.org/.well-known/openid-configuration or https://web03.company.org/.well-known/openid-configuration return your IdentityServer discovery document. Could you try that for us please?

**Comment by jesslilly** [comment] 2024-02-20 21:46
Thank you so much!  I appreciate you digging into this!  Great idea as well.

Building the full URL and hitting /.well-known/openid-configuration in Edge:

1. web03 - HTTP ERROR 404
2. web02 - ERR_CONNECTION_RESET - I don't quite understand this.
3. account - responds with beautiful JSON document.

Where do we go from here?

**Comment by josephdecock** [comment] 2024-02-21 18:56
My recommendation is to set the issuer in the options, and add some sort of logging and monitoring in case those requests with unexpected hosts come in somehow. Hopefully more details will be illuminating.

**Comment by jesslilly** [comment] 2024-02-21 19:35
OK

**Comment by JohnYii** [comment] 2024-03-05 00:58
I am only getting this warning (only permit 1 number of issuers) whenever ASPNETCORE_ENVIRONMENT=Production, along with a bunch of other strange behaviors that I don't see whenever ASPNETCORE_ENVIRONMENT=Staging in our non-prod environments. Is there a list of everything that is different with IdentityServer for Production vs Staging?

**Comment by AndersAbel** [comment] 2024-03-05 15:14
IdentityServer does not change behaviour based on the environment. Do you have any differences in the configuration of your environments?

(To be clear, there is one slight change: For the redistribution license the license error logging is changed in production.)

**Comment by AndersAbel** [comment] 2024-03-20 11:25
Looks like this long lived thread is now completely resolved so I'm closing it.

**Closed by AndersAbel** 2024-03-20 11:25 UTC
Labels: IdentityServer, question

**Comment by jesslilly** [comment] 2024-09-24 19:21
The error has mysteriously gone away.  I did upgrade from IdentityServer 6.1.5 to 6.1.8 recently....  🤔

**Comment by jesslilly** [comment] 2024-10-02 20:01
OMG I found the error again.

2024-10-02 10:54:13.5478|ERROR|Duende.License|Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: a, b, c.

This is happening only on a server where I have 2 instances of Identity Server!  I have DEV and TEST on the same server.

**Comment by AndersAbel** [comment] 2024-11-04 13:25
@jesslilly If you still receive the error I think we should have a look at your setup to find out why you get license validations logged. Can you please mail me at anders@duendesoftware.com to coordinate?
