### ISSUE TITLE
OIDC login flow stuck in /connect/token Ok 200

### ISSUE THREAD

**Issue by uverik** [DuendeSoftware/Support#622] opened 2023-04-19 16:36 UTC
We have an issue that some users are experiencing during the login flow, and this is causing us a big impact at the business level.

Specifically in the login-callback step, the last step that performs the flow is a POST 200 Ok to subd.domain.com/connect/token and the user is left in a gray screen in which the flow no longer continues. 

The thing is that it only happens in some very specific devices (that we know for the moment with Windows 7, 10 and 11) and from those devices they can no longer log in to the client with any other user or browser. 

Anyone encountered any similar cases?
Anyone could please help us?

**Comment by josephdecock** [comment] 2023-04-20 15:15
When this problem happens, do you see any errors or warnings in the identity server logs? It sounds like this is happening in production, so you may need to temporarily increase log verbosity. Are you able to see the response from the token endpoint? Does it include the tokens you were expecting?

Can you provide more details about the application? How is it implemented, and in particular how is the OIDC flow implemented?

**Comment by uverik** [comment] 2023-04-20 15:40
Hi @josephdecock 
do you see any errors or warnings in the identity server logs? No
Are you able to see the response from the token endpoint? Yes
Does it include the tokens you were expecting? Yes it includes the access_token, expires_in, id_token, scope and token_type all of them informed correctly.

Can you provide more details about the application? How is it implemented, and in particular how is the OIDC flow implemented? Yes, the application is running Duende IdentityServer. Attached the OIDC Flow:
`function _loginByToken() {
                var q = $q.defer();
                authentication.getAuthManager().signinRedirectCallback().then(function (){
                    authentication.getAuthManager().getUser().then(function (user){
                        var token = user.access_token;
                        $timeout.cancel(loginAlternativeTimer);
                        vm.showLoginAlternative = false;
                        LoginService.signInBearer(token).catch(function (){
                            q.reject();
                        });
                    }, function(e){
                        console.error(e);
                        q.reject();
                    }).catch(function (e){
                        console.error(e);
                        q.reject();
                    });
                }, function(e){
                    console.error(e);
                    q.reject();
                }).catch(function (e){
                    console.error(e);
                    q.reject();
                });
                return q.promise;
            }`

**Comment by josephdecock** [comment] 2023-04-20 16:07
Since IdentityServer is authenticating the user correctly and producing the tokens that you expect, I think it is pretty clear that this is a bug in your client application code - that is, in the javascript code. It does seem very weird to me that after this occurs, users can't log in even from other browsers. I can't see how that is even possible. Are you able to reproduce that? What happens in detail, especially in terms of protocol requests, when you switch browsers?

**Comment by uverik** [comment] 2023-04-21 06:09
@josephdecock 

We are just as surprised. We have over 500 users with multiple devices accessing the same server and application on a daily basis (going through exactly the same login flow) and we have only detected 4 devices where this casuistry happens to them.

At the moment we have not been able to reproduce the case on any of our ~200 devices.

What exactly happens is that it affects 4 devices, from which in the login-callback step, when logging in, the flow stops at a POST 200 Ok to https://sdomain.domain.com/connect/token and no longer continues.

Of the 4 devices we have identified the O.S. of 3, and they are Windows 7, 10 and 11, and on those devices they cannot login with any user in any browser or in incognito mode.
The most curious thing is that from another device of the same make and model, with the same O.S. and configurations and connected to the same network, any user can log in without any problem.

We have reviewed the Duende Identityserver (BackEnd) and OIDC (FrontEnd) code and have not detected any error logs.

**Comment by uverik** [comment] 2023-04-27 14:38
@josephdecock Add that we are using the official library (https://github.com/IdentityModel/oidc-client-js) but as it is archived it is no longer allowed to open new issues. Perhaps we may or should use another library?

**Comment by josephdecock** [comment] 2023-05-01 15:27
Yes, oidc-client-js is archived and no longer developed or supported. It was forked by the community into a typescript version which I believe is still actively maintained. You could try switching to that (though we don't officially endorse it). Another possibility is that these users might have blocked the javascript that posts back to the application. Maybe your users have installed a browser plugin that is breaking things for them by doing that sort of blocking. There's not a lot we can do without an ability to reproduce the problem though, sorry.

**Comment by uverik** [comment] 2023-05-02 08:56
Ok, so we're going tot test and give feedback.
Thanks @josephdecock

**Comment by josephdecock** [comment] 2023-05-11 14:23
Sounds good, I'll close this issue for now, but please feel free to reopen if necessary!

**Closed by josephdecock** 2023-05-11 14:23 UTC
Labels: IdentityServer, question
