### ISSUE TITLE
Deadlock occurs on the Introspect endpoint

### ISSUE THREAD

**Issue by VijayKaravadra** [DuendeSoftware/Support#51] opened 2022-05-06 07:00 UTC
**Which version of Duende IdentityServer are you using?**
v6.1.0-preview.3

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
Introspect endpoint sometimes generates the deadlock in the database.

**To Reproduce**
Invoke the introspect endpoint multiple times.

**Expected behavior**
Introspect endpoint should return the reference token details.

**Log output/exception with stacktrace**

```
An exception occurred while iterating over the results of a query for context type '"Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext"'."
""Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 65) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](AAsyncCallContext`1 context)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:f1324620-6a10-4f87-abf8-940d9b91ef1e
Error Number:1205,State:51,Class:13"
```

**Additional context**

This issue started after upgrading to the Duende IdentityServer v6.1.0-preview.3.

**Comment by brockallen** [comment] 2022-05-06 13:49
Can you reproduce this with any of our samples? I tried and I cannot.

**Comment by leastprivilege** [comment] 2022-06-12 06:59
any update?

**Comment by brockallen** [comment] 2022-06-17 12:18
Closing. If you still have issues, feel free to reopen.

**Comment by VijayKaravadra** [comment] 2022-06-23 09:15
Hello @brockallen @leastprivilege,

We're getting two deadlock errors.

1. On the Introspect endpoint, it has a select and a delete operation on the PersistedGrants table which conflicts.
Please refer to the below deadlock trace for this.

```
<deadlock>
 <victim-list>
  <victimProcess id="process2b63a06bc28" />
 </victim-list>
 <process-list>
  <process id="process2b63a06bc28" taskpriority="0" logused="0" waitresource="KEY: 36:72057594048151552 (599b0862b5ac)" waittime="3561" ownerId="699646498" transactionname="SELECT" lasttranstarted="2022-05-05T15:59:17.203" XDES="0x2b27b38fbe8" lockMode="S" schedulerid="4" kpid="976" status="suspended" spid="65" sbid="0" ecid="0" priority="0" trancount="0" lastbatchstarted="2022-05-05T15:59:17.203" lastbatchcompleted="2022-05-05T15:59:17.203" lastattention="1900-01-01T00:00:00.203" clientapp="Core Microsoft SqlClient Data Provider" hostname="identity-provider-service-7f5bf5874d-z2lv9" hostpid="939" loginname="service-mssql-staging-idp" isolationlevel="read committed (2)" xactid="699646498" currentdb="36" currentdbname="IdentityProvider" lockTimeout="4294967295" clientoption1="671088672" clientoption2="128056">
   <executionStack>
    <frame procname="adhoc" line="1" stmtstart="48" stmtend="514" sqlhandle="0x02000000d297291fb10f4b605faeceb8c167f7a7dd36f8ce0000000000000000000000000000000000000000">
unknown    </frame>
    <frame procname="unknown" line="1" sqlhandle="0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000">
unknown    </frame>
   </executionStack>
   <inputbuf>
(@__key_0 nvarchar(200))SELECT [p].[Id], [p].[ClientId], [p].[ConsumedTime], [p].[CreationTime], [p].[Data], [p].[Description], [p].[Expiration], [p].[Key], [p].[SessionId], [p].[SubjectId], [p].[Type]
FROM [PersistedGrants] AS [p]
WHERE [p].[Key] = @__key_0   </inputbuf>
  </process>
  <process id="process2b634ed5468" taskpriority="0" logused="820" waitresource="KEY: 36:72057594048544768 (fff931320b6b)" waittime="3560" ownerId="699646497" transactionname="user_transaction" lasttranstarted="2022-05-05T15:59:17.200" XDES="0x2b59c618428" lockMode="X" schedulerid="4" kpid="5204" status="suspended" spid="51" sbid="0" ecid="0" priority="0" trancount="2" lastbatchstarted="2022-05-05T15:59:17.200" lastbatchcompleted="2022-05-05T15:59:17.200" lastattention="1900-01-01T00:00:00.200" clientapp="Core Microsoft SqlClient Data Provider" hostname="identity-provider-service-7f5bf5874d-z2lv9" hostpid="939" loginname="service-mssql-staging-idp" isolationlevel="read committed (2)" xactid="699646497" currentdb="36" currentdbname="IdentityProvider" lockTimeout="4294967295" clientoption1="673185824" clientoption2="128056">
   <executionStack>
    <frame procname="adhoc" line="2" stmtstart="56" stmtend="146" sqlhandle="0x02000000c8abfe2fb5b458113c08b268f73fb0b177869e610000000000000000000000000000000000000000">
unknown    </frame>
    <frame procname="unknown" line="1" sqlhandle="0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000">
unknown    </frame>
   </executionStack>
   <inputbuf>
(@p0 bigint)SET NOCOUNT ON;
DELETE FROM [PersistedGrants]
WHERE [Id] = @p0;
SELECT @@ROWCOUNT;

   </inputbuf>
  </process>
 </process-list>
 <resource-list>
  <keylock hobtid="72057594048151552" dbid="36" objectname="IdentityProvider.dbo.PersistedGrants" indexname="PK_PersistedGrants" id="lock2b05ae7e880" mode="X" associatedObjectId="72057594048151552">
   <owner-list>
    <owner id="process2b634ed5468" mode="X" />
   </owner-list>
   <waiter-list>
    <waiter id="process2b63a06bc28" mode="S" requestType="wait" />
   </waiter-list>
  </keylock>
  <keylock hobtid="72057594048544768" dbid="36" objectname="IdentityProvider.dbo.PersistedGrants" indexname="IX_PersistedGrants_Key" id="lock2b51a737980" mode="S" associatedObjectId="72057594048544768">
   <owner-list>
    <owner id="process2b63a06bc28" mode="S" />
   </owner-list>
   <waiter-list>
    <waiter id="process2b634ed5468" mode="X" requestType="wait" />
   </waiter-list>
  </keylock>
 </resource-list>
</deadlock>
```

2. It occurs on the ServerSideSessions table. From the exception message 'Exception removing expired sessions: "Transaction (Process ID 208) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction."' looks like it is logged from [ServerSideSessionCleanupHost](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs) class.
Please refer to the below deadlock trace for this.

```
<deadlock>
	<victim-list>
		<victimProcess id="process1ac111f9848"/>
	</victim-list>
	<process-list>
		<process id="process1ac111f9848" taskpriority="0" logused="0" waitresource="KEY: 10:72057594048413696 (06b684c08d4f)" waittime="4635" ownerId="12345375618" transactionname="SELECT" lasttranstarted="2022-06-14T21:22:36.447" XDES="0x194e83e2188" lockMode="S" schedulerid="14" kpid="6852" status="suspended" spid="208" sbid="0" ecid="0" priority="0" trancount="0" lastbatchstarted="2022-06-14T21:22:36.447" lastbatchcompleted="2022-06-14T21:22:36.453" lastattention="1900-01-01T00:00:00.453" clientapp="Core Microsoft SqlClient Data Provider" hostname="identity-provider-service-7c5b944579-dm44m" hostpid="939" loginname="service-mssql-prod-idp" isolationlevel="read committed (2)" xactid="12345375618" currentdb="10" currentdbname="IdentityProvider" lockTimeout="4294967295" clientoption1="671088672" clientoption2="128056">
			<executionStack>
				<frame procname="adhoc" line="1" stmtstart="24" stmtend="518" sqlhandle="0x02000000dba3210a7ca540a253fc0a0a1bf92b56378076430000000000000000000000000000000000000000">  unknown    </frame>
				<frame procname="unknown" line="1" sqlhandle="0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000">  unknown    </frame>
			</executionStack>
			<inputbuf>  (@__p_0 int)SELECT TOP(@__p_0) [s].[Id], [s].[Created], [s].[Data], [s].[DisplayName], [s].[Expires], [s].[Key], [s].[Renewed], [s].[Scheme], [s].[SessionId], [s].[SubjectId] FROM [ServerSideSessions] AS [s] WHERE [s].[Expires] &lt; GETUTCDATE() ORDER BY [s].[Id]   </inputbuf>
		</process>
		<process id="process1b6762f7088" taskpriority="0" logused="236" waitresource="KEY: 10:72057594048610304 (fa10b750388e)" waittime="4635" ownerId="12345375616" transactionname="user_transaction" lasttranstarted="2022-06-14T21:22:36.447" XDES="0x1c133c44428" lockMode="X" schedulerid="22" kpid="11100" status="suspended" spid="239" sbid="0" ecid="0" priority="0" trancount="2" lastbatchstarted="2022-06-14T21:22:36.447" lastbatchcompleted="2022-06-14T21:22:36.447" lastattention="1900-01-01T00:00:00.447" clientapp="Core Microsoft SqlClient Data Provider" hostname="identity-provider-service-7c5b944579-s7n4k" hostpid="939" loginname="service-mssql-prod-idp" isolationlevel="read committed (2)" xactid="12345375616" currentdb="10" currentdbname="IdentityProvider" lockTimeout="4294967295" clientoption1="673185824" clientoption2="128056">
			<executionStack>
				<frame procname="adhoc" line="2" stmtstart="50" stmtend="146" sqlhandle="0x020000000a2cf82cd565b857276263fbb9efdb6a42387a170000000000000000000000000000000000000000">  unknown    </frame>
				<frame procname="unknown" line="1" sqlhandle="0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000">  unknown    </frame>
			</executionStack>
			<inputbuf>  (@p0 int)SET NOCOUNT ON; DELETE FROM [ServerSideSessions] WHERE [Id] = @p0; SELECT @@ROWCOUNT;     </inputbuf>
		</process>
	</process-list>
	<resource-list>
		<keylock hobtid="72057594048413696" dbid="10" objectname="IdentityProvider.dbo.ServerSideSessions" indexname="PK_ServerSideSessions" id="lock1bdad0fba00" mode="X" associatedObjectId="72057594048413696">
			<owner-list>
				<owner id="process1b6762f7088" mode="X"/>
			</owner-list>
			<waiter-list>
				<waiter id="process1ac111f9848" mode="S" requestType="wait"/>
			</waiter-list>
		</keylock>
		<keylock hobtid="72057594048610304" dbid="10" objectname="IdentityProvider.dbo.ServerSideSessions" indexname="IX_ServerSideSessions_Expires" id="lock1bb9e4d3680" mode="S" associatedObjectId="72057594048610304">
			<owner-list>
				<owner id="process1ac111f9848" mode="S"/>
			</owner-list>
			<waiter-list>
				<waiter id="process1b6762f7088" mode="X" requestType="wait"/>
			</waiter-list>
		</keylock>
	</resource-list>
</deadlock>  

```

**Comment by VijayKaravadra** [comment] 2022-06-27 06:33
@brockallen 

> On the Introspect endpoint, it has a select and a delete operation on the PersistedGrants table which conflicts.

In our service, we didn't set up "EnableTokenCleanup" IdentityOption. So, it's false by default. So, I don't think it could be an issue.

> It occurs on the ServerSideSessions table

I want to run these on multiple nodes. Do you see any potential fixes?

**Comment by brockallen** [comment] 2022-06-27 12:53
> I want to run these on multiple nodes. Do you see any potential fixes?

Well, there's nothing to fix, per-se. One node has completed the work. So we could look at ignoring the exception. BUt then anyone who does want to see it won't. Can you handle this in a logging filter?

**Comment by VijayKaravadra** [comment] 2022-06-27 13:14
@brockallen 

> On the Introspect endpoint, it has a select and a delete operation on the PersistedGrants table which conflicts.

In our service, "EnableTokenCleanup" IdentityOption is disabled. But, according to the Duende code when clearing server-side sessions, it also clears tokens. So, there are chances that this deadlock occurs during the server-side session clean-up only.

> It occurs on the ServerSideSessions table

We can handle this in the logging filter if we are sure that this error is from two background job operations only. What if there are two operations, first one is the clean up job and the second one a manual invocation of SessionManagementService.RemoveSessionsAsync? We are also invoking this session clean-up method in some scenarios.

**Comment by brockallen** [comment] 2022-06-28 16:39
@VijayKaravadra How often is this happening? A lot or just every once in a while? It looks like a fairly low level deadlock due to locks being taken on two different indices. Given the EF Core abstraction level our code is working at, this is very hard for our logic to control or influence. One idea on the background cleanup logic, the idea there would be to introduce a serializable transaction around all of that code... but that I'd worry we might escalate the row locks to table locks causing the normal operation to degrade. Another idea would be for our code to catch all `DbException`s on just the delete operations and build re-try logic, with the hope that this is infrequent. I'm not thrilled about either approach, thus my question as to how often you see this.

Also, @AndersAbel has some SqlServer specific ideas you could try specifically for your environment to see if they help. I'll let him chime in.

**Comment by AndersAbel** [comment] 2022-06-28 20:17
What I think is happening on scenario 1, the Introspect endpoint is.

1. Invocation 1 of introspect endpoint reads the token by key (this involves multiple substeps, but not relevant here)
2. Invocation 1 of introspect endpoint finds reference token being expired and calls delete, by id.
 a. A transaction is opened on the SQL server for the deletion.
 b. The row in the table (PK_PersistedGrants) is locked.
3. Invocation 2 of introspection endpoint reads the token by key
 a. An implicit transaction is opened on the SQL server to ensure an atomic, consistent read.
 b. The found row in IX_PersistedGrants_Key is locked and the id is extracted.

2c. Invocation 1 of introspect endpoint tries to lock the corresponding row in IX_PeristedGrants_Key to delete it. But it is locked by 3b, so it waits.
3c. Invocation 2 of introspect endpoint tries to lock the correspodning row in the table (PK_PersistedGrants) for reading the rest of the column values. But it is locked by 2b, so it waits.

And we have a deadlock.

A proposed solution is to alter the IX_PersistedGrants_Key to include all the rest of the columns, see https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-indexes-with-included-columns?view=sql-server-ver16. If I'm right, it will remove step 3c and thus eliminate the dead-lock. It should also improve performance as all the data can be retrieved from just the index and not have to read the table.

Scenario 2 is similar, but since this is invoked by a scheduled service I think the solution is rather to try to avoid multiple invocations on the same time.

**Comment by brockallen** [comment] 2022-06-28 20:42
> A proposed solution is to alter the IX_PersistedGrants_Key ...

But just to be clear, this would be a custom approach for your database only, and not something we'd be offering to support in IdentityServer itself (mainly because we're written to the EF Core abstraction level for the database).

**Comment by VijayKaravadra** [comment] 2022-07-05 13:49
@brockallen @AndersAbel

I tried updating the IX_PersistedGrants_Key index, but the PersistedGrantDbContext & The PersistedGrants entity are there in Duende's Code so there is not any way for me to update this index as we're using the code first approach only and not touching the tables without EF Core. 

Looks like it could be fixed from the Duende index definition only.

**Comment by brockallen** [comment] 2022-07-05 14:10
For the background processing -- one thing to try is to reduce the count by setting the ServerSideSessions.RemoveExpiredSessionsBatchSize option. Not sure if this is a long term fix, but it would be interesting to try.

Also, we never got a reply to you on the question "How often is this happening?"

**Comment by VijayKaravadra** [comment] 2022-07-06 04:51
@brockallen @AndersAbel 

We'll try fixing it by SQL.

> "How often is this happening?"

1. ServerSideSessions - Only one occurrence so far.
2. PersistedGrants - This happens once on average 10 days.

**Comment by brockallen** [comment] 2022-07-15 17:09
@VijayKaravadra Just to follow up on this... I spent a good deal of time trying to reproduce the deadlock you describe. In the end, I was unable to, but I came close (timeouts not deadlocks) if I can set the default isolation level to repeatable read. Is anything like that being configured in your environment?

**Comment by brockallen** [comment] 2022-07-22 16:39
@VijayKaravadra -- anything else to add to this thread? At this point, not sure what else to offer without more info.

**Comment by VijayKaravadra** [comment] 2022-07-25 04:49
@brockallen We've applied two fixes on our end and reviewing if we encounter any deadlocks. 

1. Added covering index in PersistedGrants table.
2. Updated RemoveExpiredSessionsBatchSize from 100 to 50.

We didn't encounter a single deadlock after the suggested fixes.

**Closed** 2022-07-25 14:48 UTC
Labels: IdentityServer, question
