### ISSUE TITLE
 IDX20803: Unable to obtain configuration from Identity Server

### ISSUE THREAD

**Issue by RamakrishnaPathuri** [DuendeSoftware/Support#866] opened 2023-09-03 09:42 UTC
**Which version of Duende IdentityServer are you using?**
6.3.2
**Which version of .NET are you using?**
6.0

**Describe the bug**
An unhandled exception occurred while processing the request.
InvalidOperationException: IDX20803: Unable to obtain configuration from identity server, Every request C:\home\site\wwwroot\keys\is-signing-key-424C520FADD99BF834B6A5B7B51C24C4.json'  sign -in key getting changed
IOException: IDX20807: Unable to retrieve document from: 'https://authapi-dev.azurewebsites.net/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
Date: Sun, 03 Sep 2023 09:52:34 GMT
Server: Microsoft-IIS/10.0
Transfer-Encoding: chunked
X-Powered-By: ASP.NET
Content-Type: text/plain; charset=utf-8
}', HttpResponseMessage.Content: 'System.IO.FileNotFoundException: Could not find file 'C:\home\site\wwwroot\keys\is-signing-key-14D4EC52873EC4C40B8DE5B93AD16239.json'.
File name: 'C:\home\site\wwwroot\keys\is-signing-key-14D4EC52873EC4C40B8DE5B93AD16239.json'
![image](https://github.com/DuendeSoftware/Support/assets/12637614/9728a0d4-4218-48f0-819b-d5051c396c7f)

**Expected behavior**

 Able to open the well-known/openid-configuration  , but getting an issue with keys are not saving in in app after deployed the code to azure service.

**Log output/exception with stacktrace**

FileNotFoundException: Could not find file 'C:\home\site\wwwroot\keys\is-signing-key-701BB32879B5E055AEA4FEE8ABBABA1D.json'.
Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(string fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
Microsoft.Win32.SafeHandles.SafeFileHandle.Open(string fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, long preallocationSize)
System.IO.Strategies.OSFileStreamStrategy..ctor(string path, FileMode mode, FileAccess access, FileShare share, FileOptions options, long preallocationSize)
System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, string path, FileMode mode, FileAccess access, FileShare share, int bufferSize, FileOptions options, long preallocationSize)
System.IO.StreamWriter.ValidateArgsAndOpenPath(string path, bool append, Encoding encoding, int bufferSize)
System.IO.File.WriteAllText(string path, string contents, Encoding encoding)
Duende.IdentityServer.Services.KeyManagement.FileSystemKeyStore.StoreKeyAsync(SerializedKey key) in FileSystemKeyStore.cs
Duende.IdentityServer.Services.KeyManagement.KeyManager.CreateAndStoreNewKeyAsync(SigningAlgorithmOptions alg) in KeyManager.cs
Duende.IdentityServer.Services.KeyManagement.KeyManager.CreateNewKeysAndAddToCacheAsync() in KeyManager.cs
Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysInternalAsync() in KeyManager.cs
Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysAsync() in KeyManager.cs
Duende.IdentityServer.Services.KeyManagement.AutomaticKeyManagerKeyStore.GetValidationKeysAsync() in AutomaticKeyManagerKeyStore.cs
Duende.IdentityServer.Services.DefaultKeyMaterialService.GetValidationKeysAsync() in DefaultKeyMaterialService.cs
Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(string baseUrl, string issuerUri) in DiscoveryResponseGenerator.cs
Duende.IdentityServer.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context) in DiscoveryEndpoint.cs
Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in IdentityServerMiddleware.cs
Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in IdentityServerMiddleware.cs
Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in MutualTlsEndpointMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in DynamicSchemeAuthenticationMiddleware.cs
Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in BaseUrlMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by josephdecock** [comment] 2023-09-05 15:02
This error is occurring when IdentityServer is attempting to write its signing key to the file system. The exception says "Could not find file", but my guess is that the issue is that your server process lacks permissions to access the directory that IdentityServer is trying to write to. 

It's important that the keys are persisted on the filesystem in a way that will be persistent and shared between all of your IdentityServer instances, so you'll need some sort of file storage that meets those requirements in your environment.

Then, you configure IdentityServer to persist keys to the appropriate place by setting `IdentityServerOptions.KeyManagement.KeyPath`:

```cs
        var identityServer = builder.Services.AddIdentityServer(options =>
            {

                options.KeyManagement.KeyPath = "/path/to/your/shared/key/storage";
```

**Comment by RamakrishnaPathuri** [comment] 2023-09-05 17:12
Azure App Service: Cannot create directories and write to filesystem when deployed using Azure DevOps
More Details Check below Url
https://tomasherceg.com/blog/post/azure-app-service-cannot-create-directories-and-write-to-filesystem-when-deployed-using-azure-devops

**Comment by josephdecock** [comment] 2023-09-05 21:40
Okay, this sounds like an issue in your deployment pipelines. If you're going to use automatic key management, you can 
- store the keys on the filesystem - in which case your deployed environment will have to have permissions to write to a shared persistent disk somewhere
- store the keys on a database using our EntityFramework based implementation of the key store
- implement the key store yourself

For more details, [see our docs](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/automatic_key_management/#key-storage).

**Comment by josephdecock** [comment] 2023-09-20 21:11
Any update here? Can we close this issue?

**Comment by RamakrishnaPathuri** [comment] 2023-09-24 09:34
Close the ticket ,

Thanks for support

**Closed** 2023-09-24 12:04 UTC
Labels: IdentityServer, question
