### ISSUE TITLE
Correlation Cookie Problem

### ISSUE THREAD

**Issue by galvesribeiro** [DuendeSoftware/Support#736] opened 2023-06-21 02:45 UTC
**Which version of Duende IdentityServer are you using?**

Identity Server: 6.2.0

**Which version of .NET are you using?**

.Net 7

**Describe the bug**

We're getting `Correlation failed` and sometimes `'{CorrelationCookieName}' cookie not found.`

The authentication is configured as follow:

```csharp
builder.Services.AddAuthentication()
    .AddApple(opt =>
    {
        builder.Configuration.Bind($"{Constants.APP_NAME}:Apple", opt);
        opt.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

        opt.PrivateKey = (keyId, ct) =>
        {
            var privateKey = builder.Configuration[$"{Constants.APP_NAME}:Apple:PrivateKey"]!.ToString();
            
            return Task.FromResult(privateKey.AsMemory());
        };

        opt.GenerateClientSecret = true;
    })
    .AddGoogle(opt =>
    {
        builder.Configuration.Bind($"{Constants.APP_NAME}:Google", opt);
        opt.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
    })
    .AddFacebook(opt =>
    {
        builder.Configuration.Bind($"{Constants.APP_NAME}:Facebook", opt);
        opt.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
    });
```

And Identity Server like this:

```csharp
builder.Services.AddIdentityServer(options =>
{
    options.LicenseKey = builder.Configuration[$"{Constants.APP_NAME}:LicenseKey"];
})
.UseCustomGrants()
.AddOperationalStore()
.AddConfigurationStore()
.AddConfigurationStoreCache()
.AddAspNetIdentity<CIIdentity>();
```

Can you guys spot what we are missing in regards to the configuration? There is not Cookie-specific configuration in our code, so it should all be whatever is the default. 

That is essentially preventing people from authenticate.

**Log output/exception with stacktrace**

```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 52
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 28
   at <REDACTED>.JWKSResponseHeaderMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/<REDACTED>.Host/JWKCacheMiddleware.cs:line 28
   at Program.<>c.<<<Main>$>b__0_21>d.MoveNext() in /home/vsts/work/1/s/src/<REDACTED>.Host/Program.cs:line 308
--- End of stack trace from previous location ---
   at <REDACTED>.ExceptionHandlerMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/<REDACTED>/ExceptionHandlerMiddleware.cs:line 27
```

**Additional context**

We also noticed that it happens way more often with Google signing rather than Facebook or Apple.

Thank you! I really appreciate any insights.

**Comment by josephdecock** [comment] 2023-06-26 19:32
This looks like the same issue as https://github.com/DuendeSoftware/Support/issues/348. Probably you're seeing this exception in your logs because users are clicking the back button after login. The problem is that the correlation cookie used by the login process is consumed by that process, so clicking the back button goes back through the flow without the cookie. You can't prevent the browser from having the authorize call in its history, so the back button is going to take the user back through the flow. And the correlation cookie will be destroyed during the original login, so correlation will always fail.

To handle the error, add something like this to the oidc options in your client app:

options.Events.OnRemoteFailure = async ctx =>
{
    if(ctx.Request.Path == options.CallbackPath)
    {
        var authResult = await ctx.HttpContext.AuthenticateAsync(IdentityServerConstants.DefaultCookieAuthenticationScheme);
        if(authResult.Succeeded)
        {
            ctx.HandleResponse();
            ctx.Response.Redirect("/");
        }
    }
};

You could also look at the exception message for "Correlation failed.", but I prefer this style because I don't like to rely on a string in an exception that I don't control. Unfortunately, the correlation failure exception is not a specific type of exception that you can handle either.

**Comment by josephdecock** [comment] 2023-07-06 02:44
Is anything further needed on this issue, or should we close it?

**Comment by galvesribeiro** [comment] 2023-07-06 03:27
Hey @josephdecock sorry for the delay. 

Yeah, we were investigating the case but I'm not entirely sure it is because the user is bookmarking or pressing back at the login page. The reason being, out Identity Server and explicitly used on a mobile game. So they essentially open the IdP login screen from an authorization url generated by the game. The callback is straight to the app-specific schema/url so there is no way for the user to bookmark it not make much sense they press back since they only login once and after that we use refresh tokens.

Also it is important to note that this happens 99% of the time specifically with Google login. 

<img width="733" alt="image" src="https://github.com/DuendeSoftware/Support/assets/4714040/c25c2dd6-6b39-46b2-8648-c6c73bb69379">

<img width="755" alt="image" src="https://github.com/DuendeSoftware/Support/assets/4714040/34985809-1675-4c30-bf84-cc0605db7e2a">

I'm not convinced this is a bookmark or back button issue. We have 152k occurrences in a week...

<img width="414" alt="image" src="https://github.com/DuendeSoftware/Support/assets/4714040/4897d971-2735-48c8-9b10-85029a3700a3">

**Comment by josephdecock** [comment] 2023-07-09 03:54
I agree, 152k warnings in a week seems very suspicious, and given that this is happening in a mobile app, the back button is probably not involved either.

Another possibility is that cookie sizes limits might be exceeded. Many platforms limit the amount of cookie data - apple has a 4k overall limit for example - and then cookies start getting discarded by the browser. It's possible that login with google somehow sets more state in its cookies, making those cookies more likely to exceed 4k. 

Are you able to sign in with google in your own testing? Or are you getting complaints from users who can't log in?

**Comment by galvesribeiro** [comment] 2023-07-18 16:42
Hey @josephdecock  sorry for the delay. Lost that message.

I wasn't able to replicate it myself with my account, but that shouldn't mean anything as users who had the problem sometimes can log in just fine. 

I also don't think it is a cookie size limit as if that was the case, multiple other products and companies would have that problem in Safari. I've digged in Auth0 forums/community and seems that nobody ever had that sort of issue on their end.

Also it is important to note that this happens not only on iOS. Android users, which has no Safari, also had that same problem.

**Comment by josephdecock** [comment] 2023-07-18 17:51
No problem @galvesribeiro. 

The cookie size limits are certainly a thing that we've seen in our consulting and support work before, so I wouldn't rule it out just because you're not finding a lot of information about it on some other forums. (Incidentally, are you look at the Auth0 forums because you're federating from IdentityServer to Auth0 or something like that? Or is it as another resource on the protocols?) Cookie size limits apply to most platforms - safari is the most restrictive of the widely used browsers, but other browsers _do_ have other limits.

That said, we can look at other potential causes as well. If you take a look at the way that the correlation cookie is [created by ASP.NET](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L24-L31), you can see that the correlation cookie is created with the samesite=none, secure, and httponly attributes. Is it possible that your user base has a large number of users (or contains users that make a large number of requests) with devices that wouldn't support those cookie attributes?

**Comment by galvesribeiro** [comment] 2023-07-18 18:13
I only use Auth0 as a reference as I was a long standing user of Auth0 on multiple companies I've worked with and I know some of them still use it and never had this problem (just checked with a former colleague).

Our user base right now is 54% Android / 46% iOS. I wouldn't think that the majority of the people using iOS are using Google for login as we have other Idps that are more likely to be used by this platform.

Nonetheless, even assuming that all failures are spread evenly, from our records, the 85%+ of the Android users are spread on Android 13, 12, 11. Which are the last 3 versions where Chrome supports same site cookies. On iOS, 90%+ of our users are on iOS 16.

**Comment by josephdecock** [comment] 2023-07-18 20:44
One other way that the correlation cookie could fail is that it has its own expiration of 15 minutes. So if users are logging in with google, but then not entering their credentials for 15 minutes, they would also cause this problem.

My suggestion for what to try next is to actually go back to my original suggestion of handling the remote failure. When this failure occurs, you can catch that event, and try to capture more contextual information about how the failure is occurring. 

Hopefully more data will make the nature of the failure clearer.

```
options.Events.OnRemoteFailure = async ctx =>
{
    if(ctx.Request.Path == options.CallbackPath)
    {

        var authResult = await ctx.HttpContext.AuthenticateAsync(IdentityServerConstants.DefaultCookieAuthenticationScheme);
        if(authResult.Succeeded)
        {
            // Add logging here - user is authenticated, but we don't have a correlation cookie

            ctx.HandleResponse();
            ctx.Response.Redirect("/");
        } else 
        {
            // Add more logging here - we have neither the correlation cookie, nor an authenticated user. Something else is going on. So dump all the context you can into the log
        } 
    }
};
```

**Comment by AndersAbel** [comment] 2023-07-26 12:04
@galvesribeiro Do you have any update on this?

**Closed** 2023-08-08 14:20 UTC
Labels: IdentityServer, question
