### ISSUE TITLE
IServerUrls.GetIdentityServerRelativeUrl returns incorrect URL when running IdentityServer at a subpath (prefix)

### ISSUE THREAD

**Issue by ldavisCEI** [DuendeSoftware/Support#1219] opened 2024-04-16 12:03 UTC
**Which version of Duende IdentityServer are you using?**
7

**Which version of .NET are you using?**
8

**Describe the bug**

Given IdentityServer is running at https://localhost:5001/server/
then `GetIdentityServerRelativeUrl` returns a URL of https://localhost:5001/server/server/connect/authorize/callback...
when passed the returnUrl (which in my case is /server/connect/authorize/callback...)

![image](https://github.com/DuendeSoftware/Support/assets/6639406/df1f0161-b28a-4d1e-b9af-b86fef4ce326)

**To Reproduce**

1. Complete https://docs.duendesoftware.com/identityserver/v7/quickstarts/2_interactive/
2. Update the launchSettings.json file for the IdentityServer project to include IIS Express options
```
{
	"profiles": {
		"SelfHost": {
			"commandName": "Project",
			"launchBrowser": true,
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			},
			"applicationUrl": "https://localhost:5001"
		},
		"IIS Express": {
			"commandName": "IISExpress",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			}
		}
	},
	"iisSettings": {
		"windowsAuthentication": false,
		"anonymousAuthentication": true,
		"iisExpress": {
			"applicationUrl": "http://localhost:47221/server/",
			"sslPort": 5001
		}
	}
}
```
3. Add IServerUrls to the constructor of IdentityServer\Pages\Account\Login\Index.cshtml.cs
![image](https://github.com/DuendeSoftware/Support/assets/6639406/15ca0f1f-711c-4588-bc41-1a72c66fdf91)
4. In the OnGet method of the same class add 
`var serverRelativeReturnUrl = this._serverUrls.GetIdentityServerRelativeUrl(returnUrl);`
5. Put a breakpoint after the added line
6. Update the Authority option in WebClient\Program.cs to be https://localhost:5001/server
7. Run IdentityServer (using IIS Express) and WebClient projects
9. The breakpoint should be hit and `serverRelativeReturnUrl` can be inspected.

**Expected behavior**

Calling `GetIdentityServerRelativeUrl` should return a URL without an extra /server. 
In my example, it should be https://localhost:5001/server/connect/authorize/callback...

**Comment by RolandGuijt** [comment] 2024-04-17 12:19
Thanks for this detailed information. We're investigating the issue and will come back to you.

**Comment by RolandGuijt** [comment] 2024-04-19 09:51
This looks like a bug. Thanks for letting us know.
I have created an issue in the IdentityServer repo [here](https://github.com/DuendeSoftware/IdentityServer/issues/1543). Please track the issue there because I'm closing this issue.

**Comment by RolandGuijt** [comment] 2024-04-19 12:12
After researching and talking to a peer I can confirm this is not a bug. 
The GetIdentityServerRelativeUrl method is not meant to work on returnUrls. It's purpose is to expand URLs like /account/logout to a full blown URL like https://demo.duendesoftware.com/account/logout. In fact, it is used internally to do just that.
A returnUrl isn't suitable for this because the subpath (/server in your case) is already included in the URL itself.

**Comment by ldavisCEI** [comment] 2024-04-22 10:31
Thank you, Roland, for researching this! We'll handle the returnUrl a different way.

**Comment by RolandGuijt** [comment] 2024-04-22 12:44
You're welcome!

**Closed by RolandGuijt** 2024-04-22 12:44 UTC
Labels: IdentityServer, question
