### ISSUE TITLE
facing issues in mapping the claims from token to context object in .net 3.1 app-Duende Identity server

### ISSUE THREAD

**Issue by ShailyTK** [DuendeSoftware/Support#73] opened 2022-05-30 05:08 UTC
We are upgrading identity server from   1.0.1 to Duende Identity Server in .net 6.0  

We are facing some challenges with the applications developed in netcoreapp3.1 which is client application for Duende Identity server.

1)When we pass the token to the netcoreapp3.1 application , the claims are not getting mapped in HttpContext. Also, the IsAuthenticated flag is coming as false.
We use IdentityServer 4.AccessTokenValidation   in the client application. With following as a configuration
"IdentityServer": {
        "Authority": https://localhost:5001/,
        "RequireHttpsMetadata": true,
        "APIBaseAddress": http://localhost:44352/,
        "ApiSecret": "xyz",
        "ApiName": "xyz"
    },

In the identity server we have following being set up
    builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
           .AddCookie(options =>
           {
               options.ExpireTimeSpan = TimeSpan.FromDays(Double.Parse(builder.Configuration.GetSection("Cookies").GetChildren().ToList().Where(x => x.Key == "ExpireTimeSpanDays").FirstOrDefault().Value));
               options.SlidingExpiration = true;
           });
            builder.Services.AddAuthentication(IdentityServerConstants.ExternalCookieAuthenticationScheme);

When I am passing token generated from old identity server , the claims are properly mapping to the httpcontext object. But with the token generated from Duende, the claims are not mapping.  Could you please recommend changes needed? Our Client applications are developed in .Net 3.1 , and are  API's, which further call dlls which are in old .net framework. Will the token generated from Duende work seamlessly with old .Net framework code using Microsoft.AspNetCore.Authentication(1.1.3).

**Comment by leastprivilege** [comment] 2022-05-30 11:56
This can have many potential reasons.. I would start by setting the highest log level in your token consumer to see why the token validation fails.

**Comment by ShailyTK** [comment] 2022-05-30 12:49
I debugged and checked , although I can get token details via 
var handler = new JwtSecurityTokenHandler();
var jwtSecurityToken = handler.ReadJwtToken(token); 


but   await _next.Invoke(context);  context doesn't have claims value mapped and the client api is a netcoreapp3.1 application .

![image](https://user-images.githubusercontent.com/106506707/170995382-5d9f9268-7fc0-4d1a-af1d-b8ee01a5f45a.png)

**Comment by leastprivilege** [comment] 2022-05-30 17:49
I would start by setting the highest log level in your token consumer to see why the token validation fails.

**Comment by ShailyTK** [comment] 2022-06-01 11:05
ok! For me token doesn't fails, it is unauthorized

I have all Client API's in .Net 3.1, do I need to upgrade them as well?
![image](https://user-images.githubusercontent.com/106506707/171390133-f39aad09-9a43-4acb-9e8e-823043e957c5.png)

**Comment by leastprivilege** [comment] 2022-06-01 11:08
OK - so I guess the very 1st question I should have asked is - why are you using our old package? Do you need to support reference tokens?

See here:
https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/


> ok! For me token doesn't fails, it is unauthorized

I still would expect some sort of logging that gives you more information on the root cause. Please enable logging.

**Comment by ShailyTK** [comment] 2022-06-01 13:22
We have our legacy applications which uses the old Identity server(1.0.1) with package IdentityServer4.AccessTokenValidation(2.7.0) dll.
So is Duende Token backward compatible with these applications? Or we need to upgrade the client applications as well?


log :-
{"@t":"2022-05-31T07:29:10.8240195Z","@m":"HTTP \"GET\" \"/api/investor/pe\" responded 401 with \"Unauthorized\" in 417.0000 ms","@i":"668af616","RequestMethod":"GET","RequestPath":"/api/investor/xxx","StatusCode":401,"StatusMessage":"Unauthorized","Elapsed":417,"UserName":"unknown","RequestContext":{"Headers":{"Accept":["text/csv"],"Accept-Encoding":["gzip, deflate, br"],"Authorization":["#### value hashed for security reasons ####"],"Host":["feeds-lime.dev.preqin.com"],"User-Agent":["PostmanRuntime/7.29.0"],"X-Forwarded-For":["xxx.xx.xxx.xx"],"X-Forwarded-Proto":["https"],"X-Forwarded-Port":["443"],"X-Amzn-Trace-Id":["Root=1-8886295c3c6-4d0599f36a9751a24e9076b8"],"Postman-Token":["333bd2e242f-bc47-48c3-9891-be53e71c6d4f"]},"Body":""},"RequestId":"444480000656-0001-fd00-b63f-84710c7967bb","SpanId":"|444fe76234f-48416f1229d679d1.","TraceId":"456fe76234f-48416f1229d679d1","ParentId":"","MachineName":"xxx-xxx-API-","EnvironmentUserName":"IIS APPPOOL\\xxxapi"}

**Comment by leastprivilege** [comment] 2022-06-02 08:12
The token is generally speaking backwards compatible. 

unauthorized means that token validation was not successful and thus the request is anonymous. It would be helpful to know why token validation failed.

**Comment by leastprivilege** [comment] 2022-06-12 06:54
any update?

**Comment by brockallen** [comment] 2022-06-17 12:19
Closing. If you still have issues, feel free to reopen.

**Closed by brockallen** 2022-06-17 12:19 UTC
Labels: question
