### ISSUE TITLE
Possibly Idsrv:session cookie create problem and redirect user back to sign-in page as User is not autheticated

### ISSUE THREAD

**Issue by dotnetstep** [DuendeSoftware/Support#1196] opened 2024-04-04 03:51 UTC
Which version of Duende IdentityServer are you using?
- 7.0.1

Which version of .NET are you using?
- dotnet 8

Recently I upgrade project to dotnet 8 and along with this I also updated to Identity Server 7.0.1. After this sometime I when I try to login, it keep back to sign-in page.

Overall flow is like following. 
- My application open and if user is not authenticated, it redirect to another application for login and we can consider this as Identity provider. On this page, It choose to use external provider and upon click on that it redirect to that Azure AD and authentication perform and it redirect to /connect/token endpoint and /signin-oidc. Problem I observed is following. 
- Sometime even successful login on external provider, identity server endpoint include "idsrv:session" with value ".".   ( This is I am 100% sure that if this cookie present with . value it keep redirect to same page till the point this cookie not part of response. Once this cookie not available in response from that point authentication works.)
- Above things happen multiple time and then suddenly it start working. ( So there is no clear step to reproduce issue)
- One another thing is that, this issue is more evident when working behind corporate proxy. If I try to use it without proxy, this is occur very less. 

-

**Comment by Zhy946644** [comment] 2024-04-09 02:13
Hello, has your problem been solved? I also encountered a similar problem. After successfully logging in from a third-party platform, I still returned to the login page during the callback, but this situation may occur.

**Comment by dotnetstep** [comment] 2024-04-09 04:44
@Zhy946644  Issue is not resolved for me yet. 

I did some investigation and found that when this happen CookieAuthenticationHandler log "Ticket expired". It has not clear reason why after certain trial it works. If Ticket expired then it may refresh it or something but it is not working. 

This issue is special to dotnet 8 and identity server7. My setup with IDS 6 and dotnet 6 works fine.

**Comment by Zhy946644** [comment] 2024-04-09 05:53
> @Zhy946644 Issue is not resolved for me yet.
> 
> I did some investigation and found that when this happen CookieAuthenticationHandler log "Ticket expired". It has not clear reason why after certain trial it works. If Ticket expired then it may refresh it or something but it is not working.
> 
> This issue is special to dotnet 8 and identity server7. My setup with IDS 6 and dotnet 6 works fine.

I summarized several situations that occurred. I found that other people had a similar situation of 'catch the exception and then jump to the homepage'. This is not a good method.......so there is still no better solution to this problem, right?
`Correlation failed.`  `Unable to unprotect the message.State.`  `A task was canceled.`

`OnRemoteFailure = async context => {

    if (context.Request.Path == options.CallbackPath)
    {
        var authResult = await context.HttpContext.AuthenticateAsync(IdentityServerConstants.DefaultCookieAuthenticationScheme);
        if (authResult.Succeeded)
        {
            context.HandleResponse();
            context.Response.Redirect("/");
        }
    }

    if (context.Failure != null)
    {
        if (context.Failure.Message.Contains("Correlation failed."))
        {
            context.HandleResponse();
            context.Response.Redirect("/");
        }
    }`

**Comment by AndersAbel** [comment] 2024-04-11 10:52
@dotnetstep Can you please share a more detailed description of the flow. A list of URLs hit/redirected between and the status code returned by each of them would do. Then indicate where in that flow that it fails.

@Zhy946644 Please open a separate issue. While your situation looks similar, my guess is that it's a different root cause.

**Comment by dotnetstep** [comment] 2024-04-11 11:59
I have tried to investigate it further. As of it turn out following thing. 

1. My frontend app ( MVC application) to redirect to IdentityServer App works fine.
2. IdentityServer to external provider and redirect to correct endpoint signin_aad. ( as per our configuration)
3. From here it redirect to connect/authorize/callback ( Probably this is identity server endpoint) and from here on sometime isuse comes and sometime not.
4. 
At one stage , it is saying following
AuthenticationScheme : idsrv was successfully authenticated. 

After sometime it is saying.
AuthenticationScheme : idsrv Ticket expired. 

Now when this happen it redirect to login page of identity server. 

Possible cause that I was thinking is that , in my case identityserver cookie idsrv configure with 2 second lifespan.  ( AddIdentityServer configuration in startup). Due to this it is possible that when it check firsttime it is valid but when it check again after some claim transformation and getting claim from external system, cookie become invalid. So ticket expired message.

I have check CookieAuthenticationHandler of aspnetcore repository. When it remove old key from store, there is some different in dotnet 6 and dotnet 8 branch. ( dotnet 8 set sessionkey null). Due to this it is might working fine in dotnet 6.

This is my observation and I am testing functionality with app.

**Comment by RolandGuijt** [comment] 2024-04-16 08:37
Thanks for the update. 2 seconds might be a bit too tight. 
Did the testing work out? If so, can we close the issue?

**Comment by dotnetstep** [comment] 2024-04-16 12:08
@RolandGuijt 

As of now, I think it is good to close. After increasing this timespan, I did not encounter this issue. 

Only thing that is hard to understand is that, same 2 seconds delay works without issue in dotnet 6. ( Not a single time it cause that issue.)

**Comment by RolandGuijt** [comment] 2024-04-16 13:06
Probably because of the change in the CookieAuthenticationHandler you already found yourself it takes a tad more processing time. I'm actually surprised by this myself because by the looks of it, the changes aren't too impactful.

**Closed by RolandGuijt** 2024-04-16 13:06 UTC
Labels: IdentityServer
