### ISSUE TITLE
System.OutOfMemoryException after about 12h

### ISSUE THREAD

**Issue by HStumpf** [DuendeSoftware/Support#694] opened 2023-05-26 08:34 UTC
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
6.0.306

**Describe the bug**
throws System.OutOfMemoryException  after circa 12h

After about 12 hours, an OutOfMemory error occurs.
Environment is:
Windows Server 2019 16 GigaByte Ram
IIS
dotnet 6 app on IIS
The error occurs since the update to the 6.2.0 version. 
We did not have the error with net 3.1 / ID4.
During the migration, only the database and code parts that are no longer supported or have changed were updated.

The Packages:
PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="6.2.0" 
PackageReference Include="Duende.IdentityServer.EntityFramework" Version="6.2.0" 
PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.11"
PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.0" 
PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.25.1" 
PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0" 
PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0" 

what further steps / examinations can we take?

**Comment by josephdecock** [comment] 2023-05-26 16:19
A couple of things have caused memory issues for our customers in the past:

Some old versions of System.IdentityModel.Tokens.Jwt library have a [memory leak issue](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1724).

AppInsights (if you're using it) has had memory leak issues in the past as well, for example, see [here](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1734)

Please try updating those dependencies (if you're using them) and let us know if that resolves the issue.

My other suggestion is to try to pinpoint the source of the memory leak - it could be our code, but it could also be something from Microsoft or even possibly your code. Microsoft has a guide to debugging memory leaks using performance counters [here](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak). You could try following that guide to instrument your application and determine where the memory leak is.

**Comment by HStumpf** [comment] 2023-06-01 09:21
Hello,

after i check this things - i inform you

Regards
Horst-Dieter

**Comment by HStumpf** [comment] 2023-06-15 07:33
Hi, 
today we start a api test with a duration of 26h.
I inform you in this ticket

Regards
Horst

**Comment by HStumpf** [comment] 2023-06-16 05:22
Hi,

We have taken various measures to reduce the problem:

- update the packages
- IIS recycle every 11h
- add a web application firewall

With these measures the error no longer occurred
We test it later without this settings, but i close the ticket here.
(I think the recycle should be disabled)

Thanks for your help

Regards
Horst

**Comment by HStumpf** [comment] 2023-06-16 05:23
Hi,

We have taken various measures to reduce the problem:

- update the packages
- IIS recycle every 11h
- add a web application firewall

With these measures the error no longer occurred
We test it later without this settings, but i close the ticket here.
(I think the recycle should be disabled)

Thanks for your help

Regards
Horst

**Comment by HStumpf** [comment] 2023-09-27 05:18
Hello,

Actually informtion:

Since 13.09.2023 - The leak now occurs every day

Now i have two memory dumps with about  6 Giga Byte.
Who can I send the link to for the download?

Regards
Horst-Dieter

**Comment by josephdecock** [comment] 2023-09-27 15:02
We're not able to accept memory dumps becvause we don't have the appropriate context to analyze them (your source code, the details of your implementation, customizations, environment, usage, etc). You need to analyze these memory dumps. If that analysis points to a memory leak in IdentityServer, please share that with us and we'll work to fix the bug. But these memory leaks could also be caused by your code, or your other dependencies (ASP.NET or random nuget packages).

**Comment by HStumpf** [comment] 2023-09-28 06:28
Hello,

Would you carry out the evaluation at the next higher support level?
If yes, which?

Regards
Horst-Dieter

**Comment by AndersAbel** [comment] 2023-10-19 08:51
Closing as this discussion has moved to a direct e-mail conversation.

**Closed by AndersAbel** 2023-10-19 08:51 UTC
Labels: IdentityServer, question

**Comment by TrevorChang-Advantech** [comment] 2024-02-26 03:29
i got the same issue, please please inform me if any update?

**Comment by AndersAbel** [comment] 2024-03-06 14:00
@TrevorChang-Advantech Please open a new issue with relevant details for your case.
