### ISSUE TITLE
BFF - Are all cookies session cookies?

### ISSUE THREAD

**Issue by adams141** [DuendeSoftware/Support#310] opened 2022-11-04 20:07 UTC
I have a webapi project with Angular front end. In my startup.cs I use 

```
.AddCookie("cookie", options =>
{
    options.ExpireTimeSpan = TimeSpan.FromHours(1);
```

but in the browser devtools, the cookies are still session cookies, and I'm prompted to log in again if I refresh the browser. Is there a way to have the cookies survive an F5?

Thanks

**Comment by josephdecock** [comment] 2022-11-05 01:57
The expire time span controls an expiration timestamp that is written inside the payload of the cookie. This is - by design - separate from the cookie header attributes that tell the browser how to handle the cookie. IOW, the cookie handler is designed to track expiration without needing to trust the browser. 

I'm a bit confused by what you're saying about refreshing the browser - do you mean to say that you're actually closing down the browser, losing the session cookie, and then starting the browser back up? The IsPersistent property of the AuthenticationProperties signals to the cookie handler that it should issue a cookie that will persist even if the browser is closed, if that's what you're looking for. The quickstart has example code showing how to do that:

https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Quickstarts/2_InteractiveAspNetCore/src/IdentityServer/Pages/Account/Login/Index.cshtml.cs#L107-L115

**Comment by adams141** [comment] 2022-11-05 03:12
Sorry I wasn't clear. By refresh, I just mean hit F5.

I'm testing moving an Angular/WebApi app from oidc Angular library to BFF. I can log into my app, but if I hit F5 at any point, I'm no longer logged into my app. Then I click my login button and am immediately logged back in, because Identity Server knows I'm logged in. It seems that the IdentityServer cookie is persistent, but the BFF cookie is not.

**Comment by josephdecock** [comment] 2022-11-05 12:22
That sounds really strange. Cookies don't normally disappear when you refresh the browser. To debug this problem, you need to look at the network traffic and see where the cookie is set and destroyed.

**Comment by josephdecock** [comment] 2022-11-13 12:21
Any update on this?

**Comment by josephdecock** [comment] 2022-11-22 22:58
Closing, but feel free to reopen if you need more help.

**Closed by josephdecock** 2022-11-22 22:58 UTC
Labels: BFF, question
