### ISSUE TITLE
Ability to disable proof of possession validation

### ISSUE THREAD

**Issue by szymsow** [DuendeSoftware/Support#995] opened 2023-11-16 15:32 UTC
**Which version of Duende IdentityServer are you using?**
6.3.5

**Describe the bug**
N/A

**Additional context**
After upgrading IdentityServer from 6.2.0 to 6.3.X, we encountered a proof of possession validation problem in our organization.

Not every time when using refresh tokens our system uses the mtls endpoint which causes cases where a refresh token generated from mtls cannot be used to refresh a jwt token [for this reason](https://github.com/DuendeSoftware/IdentityServer/blob/a4dc28e14de533a86a76bbf9c26e97f0b9a80381/src/IdentityServer/Validation/Default/TokenRequestValidator.cs#L722-L726).

Please consider adding an option to disable proofType validation.

Thank you for considering our request.

**Comment by AndersAbel** [comment] 2023-11-20 11:56
Can you please explain a bit more on what you are trying to achieve? Why would you want to use a refresh token acquired over mtls without mtls?

**Comment by szymsow** [comment] 2023-11-21 12:49
We are facing a case in which Component 1 directly contacts the IS component to generate a refresh token via mtls. However, the usage of this refresh token is carried out by Component 2, which connects through a proxy in the DMZ. As a result, the request to the IS component is made without mtls. For clarity, I've quickly added a diagram below.
![issue](https://github.com/DuendeSoftware/Support/assets/83670735/95d267da-7dc5-472d-b893-273764f903e3)

**Comment by AndersAbel** [comment] 2023-11-29 09:06
Thank you for the diagram.

My immediate response to solve the issue is to not use MTLS at all. The value of MTLS is that it strongly binds the refresh token to the client's cryptographical credentials. If you don't want that protection, it's better to not use MTLS at all.

The diagram also raises more questions about the design. A refresh token is a high value asset that should be kept at the client and only ever shared with the IdentityServer that issued it. What is the reason that you are sharing it with another component? There is also the use of the resource owner password grant which is generally deprecated. What is the reason to use that and not the authorization code flow?

**Comment by AndersAbel** [comment] 2023-12-11 09:51
Do you have any additional questions/comments on this or can we go ahead and close the issue?

**Closed** 2024-01-16 13:33 UTC
Labels: IdentityServer, question
