### ISSUE TITLE
Correlation failure for external login providers

### ISSUE THREAD

**Issue by asos-jasperdeluna** [DuendeSoftware/Support#1470] opened 2024-11-04 15:39 UTC
**Which version of Duende IdentityServer are you using?**
IdentityServer 7.0.6

**Which version of .NET are you using?**
.Net 8

**Describe the bug**
Correlation failure at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler during OIDC authentication. Authentication failure occurs during external provider (Facebook/Google) sign-in process with a "Correlation failed" error. The authentication middleware is unable to validate the correlation ID between the initial authentication request and the provider's callback.

Steps to reproduce the behavior.
Uncertain, we suspect users are waiting for >10 mins on login page or allowing the cookie to time out, then trying to log in which causes the "Correlation failed." exception. 

**Expected behavior**
We expect there to be some way to catch that exception

**Log output/exception with stacktrace**

```
Exception: Microsoft.AspNetCore.Authentication.AuthenticationFailureException
Message: Correlation failed.
Source: Microsoft.AspNetCore.Authentication
Error ID: 8299279

Stack Trace:
   at Microsoft.AspNetCore.Authentication.AuthenticationFailureException
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper+<HandleRequestAsync>d_6.MoveNext
   at Duende.IdentityServer.Version=7.0.6.0.Culture=neutral.PublicKeyToken=null

Additional Context:
- Type: Microsoft.AspNetCore.Authentication.AuthenticationFailureException
- Assembly: Duende.IdentityServer, Version=7.0.6.0
- Method: HandleRequestAsync
- InnermostMessage: Correlation failed.
- OuterId: 8299279
- SeverityLevel: Error

Parsed Exception Stack:
[{
    "outerId": "0",
    "message": "An error was encountered while handling the remote login.",
    "type": "Microsoft.AspNetCore.Authentication.AuthenticationFailureException",
    "id": "8299279"
},
{
    "outerId": "8299279",
    "message": "Correlation failed.",
    "type": "Microsoft.AspNetCore.Authentication.AuthenticationFailureException",
    "id": "40001287",
    "severityLevel": "Error"
}]

```

**Additional context**

**Comment by AndersAbel** [comment] 2024-11-05 09:56
This is really not a Duende Software specific issue but rather an issue with how the Microsoft remote authentication handlers work.

> Uncertain, we suspect users are waiting for >10 mins on login page or allowing the cookie to time out, then trying to log in which causes the "Correlation failed." exception.

This is a common cause of this problem, yes. Another reason could be browsers that aggressively blocks third party cookies (I'm looking at you Safari).

The best way to handle this exception is to catch it and retry the login with the same provider. If the user completed the sign in on the external provider, they will typically be single signed on. This will give a slight longer delay on login, but no error messages.

**Comment by AndersAbel** [comment] 2024-11-11 10:00
Looks like the issue is solved, so I'm closing it.

**Closed by AndersAbel** 2024-11-11 10:00 UTC
Labels: IdentityServer, question
