### ISSUE TITLE
IdentityServer generate JWT for different User

### ISSUE THREAD

**Issue by yosi-xtremax-com** [DuendeSoftware/Support#1101] opened 2024-02-06 05:44 UTC
We have bug in production environment that cannot be replicated in other environment, and we're not sure the root cause of the issue. I'm posting it here to see if there's any insight from the expert here on what might be the possible root cause, and what we can do to check/verify the probable root cause.

**Which version of Duende IdentityServer are you using?**
Duende.IdentityServer 6.1.1
Duende.IdentityServer.AspNetIdentity 6.1.1
Duende.IdentityServer.EntityFramework 6.1.1

**Which version of .NET are you using?**
net6.0

**Describe the bug**

We have been using the IdentityServer in our Production for 6 months with no issue about this (at least not reported), until we get a report on 29th January 2024 that they see another user's data in their dashboard.
After checking the log, apparently that user access the dashboard using JWT containing details of different user.

**To Reproduce**

We cannot reproduce this issue in another environment, and we have to turn the Production environment into maintenance, because of the security breach.

**Expected behavior**

JWT generated according to the user who logged in.

**Log output/exception with stacktrace**

The following log show: we update the user before sign-in, it show the correct user. (We update the user based on the claims from external authentication process). After that we sign-in the same 'user' object, the which shows log from CookieAuthenticationHandler and our custom ITicketStore storing the "AuthSessionStore".
```
2024-01-29 08:26:35.1077 [INFO] [656bf262-94f4-4b7f-a4bc-1bd3ff35ac6d] Xtremax.IdentityProvider.Controllers.AccountController User TANHU*****030F data updated successfully.
2024-01-29 08:26:35.1765 [INFO] [656bf262-94f4-4b7f-a4bc-1bd3ff35ac6d] Xtremax.Cache.RedisCacheClientServiceStack Start storing cache with key : AuthSessionStore-5090e271-e37b-4007-9ff7-a408c8f2fc9b
2024-01-29 08:26:35.1796 [INFO] [656bf262-94f4-4b7f-a4bc-1bd3ff35ac6d] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler AuthenticationScheme: Identity.Application signed in.
2024-01-29 08:26:35.1796 [INFO] [656bf262-94f4-4b7f-a4bc-1bd3ff35ac6d] Xtremax.Cache.RedisCacheClientServiceStack Successfully store cache with key: AuthSessionStore-5090e271-e37b-4007-9ff7-a408c8f2fc9b, time to live: 86399, total time for this process: 00:00:00.0030210
```
The response of the previous endpoint is to redirect user to Duende AuthorizeCallbackEndpoint. The log here show it retrieve the same ITicketStore key from the previous endpoint.
Here also there's another call to the custom ITicketStore to store again the same key.
```
2024-01-29 08:26:35.3487 [INFO] [] Xtremax.Cache.RedisCacheClientServiceStack Successfully retrieve cache with key: AuthSessionStore-5090e271-e37b-4007-9ff7-a408c8f2fc9b, total time for this process: 00:00:00.0000888
2024-01-29 08:26:35.3786 [INFO] [] Duende.IdentityServer.Hosting.IdentityServerMiddleware Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback
2024-01-29 08:26:35.4450 [INFO] [] Xtremax.Cache.RedisCacheClientServiceStack Start storing cache with key : AuthSessionStore-5090e271-e37b-4007-9ff7-a408c8f2fc9b
2024-01-29 08:26:35.4486 [INFO] [] Xtremax.Cache.RedisCacheClientServiceStack Successfully store cache with key: AuthSessionStore-5090e271-e37b-4007-9ff7-a408c8f2fc9b, time to live: 86399, total time for this process: 00:00:00.0035555
```
This is the endpoint that receive request from the generated JWT, it shows different user from previous log-in. We know that its from the same user because there's no other user activity at this time. (The traffic is quite low, we record about 20 user signin activity at the day, and the recorded log is early in the morning with no other user activity.
```
2024-01-29 08:26:53.8861 [INFO] [f8ae2d87-7721-46c5-8b40-6df193e06dd2, f8ae2d87-7721-46c5-8b40-6df193e06dd2] Xtremax.Cache.RedisCacheClientServiceStack Start storing cache with key : UserPermission/ABAYA***************A_720U/ 
```

**Additional context**

We use custom ITicketStore to store the authentication cookie.
```
public class CacheTicketStore : ITicketStore
{
    private const string KEY_PREFIX = "AuthSessionStore-";
    private readonly IAuthenticationTicketService _ticketService;
    private readonly ICacheClient _cacheClient;

    public CacheTicketStore(IAuthenticationTicketService ticketService, ICacheClient cacheClient)
    {
        _ticketService = ticketService;
        _cacheClient = cacheClient;
    }

    public async Task<string> StoreAsync(AuthenticationTicket ticket)
    {
        var guid = Guid.NewGuid();
        var key = KEY_PREFIX + guid;
        await RenewAsync(key, ticket);
        return key;
    }

    public Task RenewAsync(string key, AuthenticationTicket ticket)
    {

        _ticketService.Store(key, ticket);
        _storeCache(key, ticket);

        return Task.FromResult(0);
    }

    public Task<AuthenticationTicket> RetrieveAsync(string key)
    {
        var ticket = _DeserializeFromBytes(_cacheClient.Get<byte[]>(key));
        if (ticket == null)
        {
            ticket = _ticketService.Retrieve(key);
            if (ticket != null)
            {
                _storeCache(key, ticket);
			}
        }
        return Task.FromResult(ticket);
    }

    public Task RemoveAsync(string key)
    {
        _ticketService.Remove(key);
        _cacheClient.Clear(key);
        return Task.FromResult(0);
    }
    private static byte[] _SerializeToBytes(AuthenticationTicket source)
    {
        return TicketSerializer.Default.Serialize(source);
    }

    private static AuthenticationTicket _DeserializeFromBytes(byte[] source)
    {
        return source == null ? null : TicketSerializer.Default.Deserialize(source);
    }

    private void _storeCache(string key, AuthenticationTicket ticket, int defaultTtlSeconds = 3600)
    {
        var expiresUtc = ticket.Properties.ExpiresUtc;
		var ttlSeconds = defaultTtlSeconds;
        if (expiresUtc.HasValue)
        {
            ttlSeconds = (int) (expiresUtc.Value - DateTime.UtcNow).TotalSeconds;
        }

        _cacheClient.Store(key, _SerializeToBytes(ticket), ttlSeconds);
    }
}
```
This is the AuthenticationTicketService used in the ITicketStore implementation above.
```
public class AuthenticationTicketService : IAuthenticationTicketService
{
	private readonly IAuthRepository<XBaseIdentity.Entity.AuthenticationTicket> _ticketRepository;
	public AuthenticationTicketService(IAuthRepository<XBaseIdentity.Entity.AuthenticationTicket> ticketRepository)
	{
		_ticketRepository = ticketRepository;
	}

	public void Remove(string key)
	{
		var ticket = _ticketRepository.GetAll().Where(x => x.Key == key).FirstOrDefault();
		if (ticket != null)
		{
			_ticketRepository.Delete(ticket);
			_ticketRepository.SaveChanges();
		}
	}

	public Auth.AuthenticationTicket Retrieve(string key)
	{
			
		var ticket = _ticketRepository.GetAll().Where(x => x.Key == key && x.Ttl > DateTime.Now).FirstOrDefault();
		if (ticket == null)
		{
			return null;
		}
		else
		{
			return TicketSerializer.Default.Deserialize(ticket.Value);
		}
	}

	public void Store(string key, Auth.AuthenticationTicket ticket, int defaultTtlSeconds = 3600)
	{
		var ticketEntity = _ticketRepository.GetAll().Where(x => x.Key == key).SingleOrDefault();

		if (ticketEntity == null) {
			var ttl = ticket.Properties.ExpiresUtc;

			ticketEntity = new XBaseIdentity.Entity.AuthenticationTicket
			{
				Id = Guid.NewGuid(),
				Key = key,
				Value = TicketSerializer.Default.Serialize(ticket),
				Ttl = ttl.HasValue ? ttl.Value.UtcDateTime.ToLocalTime() : DateTime.Now.Add(TimeSpan.FromSeconds(defaultTtlSeconds)),
			};
			_ticketRepository.Insert(ticketEntity);
		}
		else
		{
			var ttl = ticket.Properties.ExpiresUtc;

			ticketEntity.Value = TicketSerializer.Default.Serialize(ticket);
			ticketEntity.Ttl = ttl.HasValue ? ttl.Value.UtcDateTime.ToLocalTime() : DateTime.Now.Add(TimeSpan.FromSeconds(defaultTtlSeconds));

			_ticketRepository.Update(ticketEntity);
		}

		_ticketRepository.SaveChanges();
	}

	public void RemoveExpired()
	{
		var tickets = _ticketRepository.GetAll().Where(x => x.Ttl <= DateTime.Now).ToList();
		foreach (var ticket in tickets)
		{
			_ticketRepository.Delete(ticket);
		}
		_ticketRepository.SaveChanges();
	}
}
```
EDIT 1: Add how we register the ITicketStore
The following code is called in Startup.cs ConfigureServices.
```
public static IServiceCollection ConfigureIdentityServerExternalCookie(this IServiceCollection services)
{
    var serviceProvider = services.BuildServiceProvider();
    var ticketStore = serviceProvider.GetService<ITicketStore>();
	var cookieOptions = serviceProvider.GetService<IdentityServerExternalCookieOptions>();

	services.ConfigureApplicationCookie(options =>
    {
        options.Cookie.Name = IdentityServerConstants.ExternalCookieAuthenticationScheme;
        options.SessionStore = ticketStore;
        options.ExpireTimeSpan = TimeSpan.FromSeconds(cookieOptions.ExpireTimeSpanSeconds);

    });
    services.ConfigureApplicationCookie(options =>
    {
        options.Cookie.Name = IdentityServerConstants.ExternalCookieAuthenticationScheme + "C1";
        options.SessionStore = ticketStore;
		options.ExpireTimeSpan = TimeSpan.FromSeconds(cookieOptions.ExpireTimeSpanSeconds);
	});
    services.ConfigureApplicationCookie(options =>
    {
        options.Cookie.Name = IdentityServerConstants.ExternalCookieAuthenticationScheme + "C2";
        options.SessionStore = ticketStore;
		options.ExpireTimeSpan = TimeSpan.FromSeconds(cookieOptions.ExpireTimeSpanSeconds);
	});

    return services;
}
```
EDIT 2: Add the IAuthRepository<XBaseIdentity.Entity.AuthenticationTicket> update implementation
```
public void Update(TEntity entity)
{
    EntityDbSet.Attach(entity);
    EntityDbSet.Update(entity);
}
```
EntityDbSet is a Microsoft.EntityFrameworkCore.DbSet

**Comment by yosi-xtremax-com** [comment] 2024-02-06 06:06
Can i confirm that the following code from Duende AuthorizeCallbackEndpoint will trigger the ITicketStore RenewAsync?
https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Endpoints/AuthorizeCallbackEndpoint.cs#L49
https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Services/Default/DefaultUserSession.cs#L206
https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Services/Default/DefaultUserSession.cs#L135

**Comment by yosi-xtremax-com** [comment] 2024-02-07 11:30
We're able to pin point the step where current user's session become wrong, thanks to Duende IdentityServer cookie idsrv.session.

After user sign-in in endpoint A called "Login", user will be redirected to Duende IdentityServer AuthorizeCallbackEndpoint, after that user will be redirected to JavaScript Client Oidc Callback.

We have record of the user's http request complete with the http request header which include request cookie.

- When user access AuthorizeCallbackEndpoint, it have request cookie idsrv.session=EC1B820DA60999011FED8E677D747E27, which was set by endpoint A.
- When user access JavaScript Client Oidc Callback, the request cookie changed into idsrv.session=75FA2A38AB444D56C17E6CAAAFB3ACE2
- This idsrv.session value 75FA2A38AB444D56C17E6CAAAFB3ACE2 actually belong to another user that signed-in hours before current user sign-in.

My question is what process that happen inside AuthorizeCallbackEndpoint that modify the idsrv.session, and what input determine the idsrv.session? Considering the HTTP request that hit AuthorizeCallbackEndpoint already have correct idsrv.session value.

**Comment by josephdecock** [comment] 2024-02-07 21:45
Thanks for getting in touch. We definitely take an issue like this quite seriously.

There are a few possibilities:
- There could be a bug in your AuthenticationTicketStore or AuthenticationTicketService. Especially since there is both a store and a cache involved, its possible that there could be inconsistencies between the two systems if one fails and the other succeeds, or if multiple concurrent requests (a write and a read at the same time) its possible that the write would be partly done during the read and the store and the cache would be inconsistent.
- There's also some subtleties in the ASP.NET ticket store abstraction that you're implementing. Notably, if you sign in on top of an existing session, the same key will be used with a new ticket. I would validate that your implementation handles that edge case correctly. See [here](https://github.com/dotnet/aspnetcore/issues/22135) for more details on that.
- Speaking of the ticket store abstraction, Microsoft ASP.NET is what actually invokes the RenewAsync method in the ITicketStore, not IdentityServer. There's quite a bit of logic in the ASP.NET handler about when exactly Renew is called:
   - https://github.com/dotnet/aspnetcore/blob/e07adfec59003776702370fe2091e731a323c67f/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L342
   - https://github.com/dotnet/aspnetcore/blob/e07adfec59003776702370fe2091e731a323c67f/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L264
- There could be something wrong with the second login request that somehow its authentication cookie didn't survive throughout the process.
- There could be a bug in the client application related to how it is storing tokens.

**Comment by yosi-xtremax-com** [comment] 2024-02-08 06:13
Hi @josephdecock , Thank you for your response and detailed explanations.

Based on the application log and http request log, I can confirm that when user's browser call AuthorizationCallbackEndpoint, it still use the correct cookie (idsrv.session, and idsrv.external which trigger the custom ITicketStore RetrieveAsync with correct key, the same key as when user signed-in).

Since the AuthorizationCallbackEndpoint return the wrong response cookie for idsrv.session, and this cookie is derived from the authentication cookie, that means my custom ITicketStore RetrieveAsync return the wrong ticket which belong to another user. Is my understanding correct?

With this new information, we can eliminate the following points that you mention right?
- There could be something wrong with the second login request that somehow its authentication cookie didn't survive throughout the process.
- There could be a bug in the client application related to how it is storing tokens.
- There could be some odd browser extension that tries to "restore tabs" that brings back old state, including the old cookie.

**Comment by yosi-xtremax-com** [comment] 2024-02-08 06:29
Hi @josephdecock ,
Another thing, regarding this statement:

> There could be a bug in your AuthenticationTicketStore or AuthenticationTicketService. Especially since there is both a store and a cache involved, its possible that there could be inconsistencies between the two systems if one fails and the other succeeds, or if multiple concurrent requests (a write and a read at the same time) its possible that the write would be partly done during the read and the store and the cache would be inconsistent.

It only apply on read and write inconsistency on the same key right? While in this case, a key return the value of another key.

**Comment by AndersAbel** [comment] 2024-02-16 21:42
We're closing this issue, as further analysis continued through our consulting services. At this time, we don't have reason to think that this issue was caused by a bug in IdentityServer.

**Closed as completed by AndersAbel** 2024-02-16 21:42 UTC
Labels: IdentityServer, question
