### ISSUE TITLE
Cryptographic exception when using Auth0 paswordless identity provider

### ISSUE THREAD

**Issue by eugene-rebedailo** [DuendeSoftware/Support#443] opened 2023-01-12 11:13 UTC
**Which version of Duende IdentityServer are you using?**
6.0.4

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
An exception is thrown when trying to sign in using external OAuth provider (Auth0). After having gone through the sign-in process in Auth0 (using paswordless authentication + MFA), when returning to the identity server and calling the following endoint:
/federation/<scheme>/signin, a cryptographic exception is thrown.

**To Reproduce**
- Setup Auth0 application with paswordless sign-in
- Register oidc authentication provider within the identity server to use the Auth0 sign-in
- Try to sign-in using this provider

**Expected behavior**
User successfully signs into the application through the Auth0 provider.

**Log output/exception with stacktrace**
```
System.Security.Cryptography.CryptographicException:
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore (Microsoft.AspNetCore.DataProtection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect (Microsoft.AspNetCore.DataProtection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect (Microsoft.AspNetCore.DataProtection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Duende.IdentityServer.Infrastructure.DistributedCacheStateDataFormatter.Unprotect (Duende.IdentityServer, Version=6.0.4.0, Culture=neutral, PublicKeyToken=null: /_/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs:101)
   at Duende.IdentityServer.Infrastructure.DistributedCacheStateDataFormatter.Unprotect (Duende.IdentityServer, Version=6.0.4.0, Culture=neutral, PublicKeyToken=null: /_/src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs:83)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ReadPropertiesAndClearState (Microsoft.AspNetCore.Authentication.OpenIdConnect, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler+<HandleRemoteAuthenticateAsync>d__19.MoveNext (Microsoft.AspNetCore.Authentication.OpenIdConnect, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

**Additional context**
Our setup has two Auth0-based identity providers. One of them is regular login-password and another one is paswordless(email). The regular login-password one seems to work without an issue.

**Comment by josephdecock** [comment] 2023-01-12 17:51
You need to specify distinct CallBackPaths in the options of your authentication schemes, because the Microsoft OpenIdConnect handler gets distinct data protection keys each time it is registered as a authentication scheme. 

The handler data protects the state parameter it sends to auth0. Then when auth0 returns to your application at the CallBackPath, it tries to unprotect that state value. The problem is, the schemes have conflicting callback paths, so the call back is being handled by the wrong scheme, which has the wrong data protection key.

**Comment by josephdecock** [comment] 2023-01-13 16:12
Thanks Eugene - I was assuming that you were were statically configuring the identity providers, but if you're using dynamic providers, then what I said doesn't apply.

If you're seeing that auth0 is changing the state that would definitely cause this problem, and is an auth0 bug. Unfortunately, there isn't really any viable workaround that I can see. I think you're going to have to raise the issue with auth0.

**Comment by josephdecock** [comment] 2023-01-18 03:08
Okay, great. I'll go ahead and close this issue for now then, but feel free to reopen it if there are further developments that need more discussion.

**Closed by josephdecock** 2023-01-18 03:08 UTC
Labels: IdentityServer, question
