### ISSUE TITLE
Server-side sessions cleanup generates null reference exception if no sessions existed

### ISSUE THREAD

**Issue by nikriaz** [DuendeSoftware/Support#420] opened 2022-12-24 11:49 UTC
**Which version of Duende IdentityServer are you using?**
6.2.0

Doesn't seem to affect functionality, but pollutes the log.

`[ERR] Microsoft.Extensions.DependencyInjection.ServerSideSessionCleanupHost Exception removing expired sessions: "Object reference not set to an instance of an object."`

**Comment by josephdecock** [comment] 2022-12-27 17:11
Thanks for the bug report! So far, I haven't been able to reproduce this - can you please post the full stack trace?

Thanks!

**Comment by nikriaz** [comment] 2022-12-30 11:09
Sorry for asking but is there a simple way to do that? I mean you handled this exception and this handling is in a source for me now. 

But I think the error cause is a simple one. It is here:

```
                    var sessions = await serverSideTicketStore.GetAndRemoveExpiredSessionsAsync(options.ServerSideSessions.RemoveExpiredSessionsBatchSize, cancellationToken);
                    found = sessions.Count;
```

`GetAndRemoveExpiredSessionsAsync` will return null if nothing found, and the Count causes an exception.

**Comment by josephdecock** [comment] 2023-01-04 22:57
No problem, @nikriaz, you're right - there probably isn't a good way to get the full stack trace since the host is catching the exception. Are you using the default implementation of the `ServerSideTicketStore`?

**Comment by nikriaz** [comment] 2023-01-05 09:16
Yes, default

**Comment by josephdecock** [comment] 2023-01-05 15:38
Also, one thing that might help is if you could turn up the logging level all the way and then send logs from when this error occurs. Thanks!

**Comment by josephdecock** [comment] 2023-01-06 02:15
Actually, thinking about this some more, we should be logging the full exception, not just the Message. I've created a [PR](https://github.com/DuendeSoftware/IdentityServer/pull/1117) to do that. 

Reading the source it is very unclear where the null reference is coming from - if you're right that sessions.Count is the source of the problem, it is very unclear to me how sessions can be null. Could you p,lease copy the cleanup host class into your solution and make the same change there so that we can get a full stack trace? Would be a big help - thanks in advance!

**Comment by nikriaz** [comment] 2023-01-06 07:46
It looks like db connection or scope get disposed and `ServerSideTicketStore.GetAndRemoveExpiredSessionsAsync` cannot be even invoked. I do not really understand why. Please have a look if it already helps. 

[expired_sessions_exception.log](https://github.com/DuendeSoftware/Support/files/10358442/expired_sessions_exception.log)

**Comment by nikriaz** [comment] 2023-01-06 12:25
You're getting another logger instance inside this method from the scope factory while it's not required and it shouldn't be disposed. Unlikely but maybe it causes some weird DI behavior with this earlier disposing of required transient services?

**Comment by josephdecock** [comment] 2023-01-06 17:06
Okay, thanks for all this. The logs are good to have, but don't completely answer our questions. I think the best way to solve this will be for you to try making the change to the cleanup host's logging and then see if you can reproduce the error but get a stack trace too. Thanks!

**Comment by nikriaz** [comment] 2023-01-08 08:31
I'm not entirely sure how it works but when I added this class to my solution, even though VisualStudio IntelliSense warned me that there is version conflict and locally added class will have precedence, unfortunately it does not and the class from NuGet reference is still effective. I was also unable to override the method because it's not suitable for that. I learned that it seems it's not that easy and  it looks like the only option is to add the whole IdS to my solution or build and replace NuGet package locally, seems a bit overwhelming for this task.  Maybe I didn't understand something and you meant something else? I also tried to spin up Serilog.Exceptions but no luck, seems `ex.Message` effectively kills all details. 

However, during this experiments I learned that the error does not occur on the local dev machine but only when published on IIS.  Maybe it will help? I also noticed that cancellation token will never reach this `RunAsync` method even though `StopAsync ` isn't actually called before error occurs so it's not a reason for the error. I also do not entirely understand the reason for two `GetAndRemoveExpiredSessionsAsync` and their consequent execution. I feel that the reason is somewhere here. I think it's already obvious that the reason that `serverSideTicketStore` gets disposed so maybe it isn't worth efforts to try further to get error details in `RunAsync`

**Comment by josephdecock** [comment] 2023-01-13 16:43
The PR that will log the full exceptions in the host has been merged. Could you please try to reproduce the problem with the 6.3 preview release which will include that fix? If you do, then we can hopefully get a full stack trace and much more easily track down this issue.

The preview release is published to a different nuget feed. To get it, add the following nuget.config to your project:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="Duende IdentityServer CI" value="https://www.myget.org/F/duende_identityserver/api/v3/index.json" />
    </packageSources>
</configuration>
```

**Comment by nikriaz** [comment] 2023-01-13 19:59
Will do, thanks. However, looking closer to the` ServerSideSessionCleanupHost` class I should admit it's suboptimal. It's a little bit brutal to fire and forget the own method from the DI class to the separate thread and then get a DI scope from there. I've seen very similar unexplainable errors with with a pattern of this kind.  Would you consider to straighten it and add to this preview first?

Just replace `IHostedService `to `BackgroundService`, get rid of `Task.Factory.StartNew` and all content from StartAsync and StopAsync with all these tricky things with cancellation token, and move  content of `StartInternalAsync` to the `ExecuteAsync`. Cancellation token in the `RunAsync` is not required as it has no chance to get there.

**Comment by josephdecock** [comment] 2023-01-18 02:47
Thanks for the suggestions, and we will consider making changes, but we'd really like to be able to reproduce the issue or at least have a stack trace from you so that we know when we do make changes that we're fixing your issue.

**Comment by nikriaz** [comment] 2023-01-21 01:19
Here we go. Hopefully, it will help. Please share your findings if you can, very curious.

[error_json.log](https://github.com/DuendeSoftware/Support/files/10471252/error_json.log)

**Comment by josephdecock** [comment] 2023-01-25 17:15
Thanks very much for the stack trace @nikriaz! It shows that the issue is caused by the use of the http context from this cleanup job. I've created an issue to keep track this (see above).

**Comment by josephdecock** [comment] 2023-01-25 21:53
We've done some investigation and see that the problem happens when the issuer is missing from the ticket stored in the server side session store. That can happen when users log in a second time over top of an existing session. We have a fix in our pipelines for that problem now. The next patch release, coming out later this week, will include the fix. Please test it out and let us know if that resolves your issues.

**Comment by nikriaz** [comment] 2023-02-01 19:40
Happy to report that since 6.3.0-alpha0.11 was installed, I have no this error anymore, as well as no new bugs were noticed. Great job, thank you very much!

**Comment by josephdecock** [comment] 2023-02-02 03:41
Thanks a lot for testing the alpha build!

**Closed** 2023-02-02 03:42 UTC
Labels: IdentityServer, bug report

**Comment by nikriaz** [comment] 2023-02-08 16:48
Unfortunately, it's not end of the story. 

I have a 30-minutes access token lifetime and longer-life refresh token. I do not use one-time refresh tokens.  I use your client's BFF-built-in token management capabilities to get new access token using refresh token in my own handler which syncs access token lifetime with cookie expiration and gets updated access token on-the-fly during API calls. Unfortunately, it doesn't work anymore. It seems like my refresh tokens somehow get invalidated now during this updating calls, and instead of background update, a client should be authorized manually again. Actually, server-side session control is not effective anymore because client always should be re-authorized before server-side session gets a chance to be over. 

It will take some time and efforts to debug new conditions but maybe something already come to your mind what could be wrong, and whether it's related to last changes with server-side stores or maybe other changes incorporated into this alpha-build? 

Maybe it's already known and I do not need to debug it.
