### ISSUE TITLE
Bug while implementing duende.IdentityServer with .NET 7 

### ISSUE THREAD

**Issue by erjain** [DuendeSoftware/Support#360] opened 2022-11-27 19:13 UTC
**Which version of Duende IdentityServer are you using?**
6.2.0
**Which version of .NET are you using?**
7.0
**Describe the bug**
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Duende.IdentityServer.Services.DefaultSessionCoordinationService -> λ:Duende.IdentityServer.Stores.IServerSideSessionStore.
 ---> Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'Duende.IdentityServer.Stores.IServerSideSessionStore' returned null.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
[19:05:57 INF] Configuring web host (Identity.API)...
[19:06:18 INF] Applying migrations (Identity.API)...
[19:06:25 INF] Migrating database associated with context PersistedGrantDbContext
[19:06:32 INF] Migrated database associated with context PersistedGrantDbContext
[19:06:32 INF] Migrating database associated with context ApplicationDbContext
[19:06:35 INF] Migrated database associated with context ApplicationDbContext
[19:06:35 INF] Migrating database associated with context ConfigurationDbContext
[19:06:39 INF] Migrated database associated with context ConfigurationDbContext
[19:06:39 INF] Starting web host (Identity.API)...
[19:06:40 INF] Starting Duende IdentityServer version 6.2.0+d923c6c10f11013223f6998059c20f2ac26ba44a (.NET 7.0.0)
[19:06:40 WRN] You do not have a valid license key for the Duende software. This is allowed for development and testing scenarios. If you are running in production you are required to have a licensed version. Please start a conversation with us: https://duendesoftware.com/contact
[19:06:40 INF] Using the default authentication scheme Identity.Application for IdentityServer
[19:06:41 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
[19:06:41 WRN] No XML encryptor configured. Key {190e9a2d-9a29-4bd8-aab9-acba8d250ff9} may be persisted to storage in unencrypted form.
Hosting environment: Development
Content root path: /app
Now listening on: http://0.0.0.0:80
Application started. Press Ctrl+C to shut down.
[19:06:52 ERR] An unhandled exception has occurred while executing the request.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Duende.IdentityServer.Services.DefaultSessionCoordinationService -> λ:Duende.IdentityServer.Stores.IServerSideSessionStore.
 ---> Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'Duende.IdentityServer.Stores.IServerSideSessionStore' returned null.
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at lambda_method1037(Closure, Object, HttpContext, IServiceProvider)
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.eShopOnContainers.Services.Identity.API.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in C:\Tarun\github\erjain\dotnet-architecture\eShopOnContainers\src\Services\Identity\Identity.API\Startup.cs:line 131
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
[19:06:52 ERR] An unhandled exception has occurred while executing the request.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Duende.IdentityServer.Services.DefaultSessionCoordinationService -> λ:Duende.IdentityServer.Stores.IServerSideSessionStore.
 ---> Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'Duende.IdentityServer.Stores.IServerSideSessionStore' returned null.
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at lambda_method1037(Closure, Object, HttpContext, IServiceProvider)
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.eShopOnContainers.Services.Identity.API.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in C:\Tarun\github\erjain\dotnet-architecture\eShopOnContainers\src\Services\Identity\Identity.API\Startup.cs:line 131
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
[19:06:52 ERR] An unhandled exception has occurred while executing the request.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Duende.IdentityServer.Services.DefaultSessionCoordinationService -> λ:Duende.IdentityServer.Stores.IServerSideSessionStore.
 ---> Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'Duende.IdentityServer.Stores.IServerSideSessionStore' returned null.
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at lambda_method1037(Closure, Object, HttpContext, IServiceProvider)
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.eShopOnContainers.Services.Identity.API.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in C:\Tarun\github\erjain\dotnet-architecture\eShopOnContainers\src\Services\Identity\Identity.API\Startup.cs:line 131
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
[19:06:54 ERR] An unhandled exception has occurred while executing the request.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Duende.IdentityServer.Services.DefaultSessionCoordinationService -> λ:Duende.IdentityServer.Stores.IServerSideSessionStore.
 ---> Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'Duende.IdentityServer.Stores.IServerSideSessionStore' returned null.
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at lambda_method1037(Closure, Object, HttpContext, IServiceProvider)
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.eShopOnContainers.Services.Identity.API.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in C:\Tarun\github\erjain\dotnet-architecture\eShopOnContainers\src\Services\Identity\Identity.API\Startup.cs:line 131
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
[19:06:54 ERR] An unhandled exception has occurred while executing the request.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Duende.IdentityServer.Services.DefaultSessionCoordinationService -> λ:Duende.IdentityServer.Stores.IServerSideSessionStore.
 ---> Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'Duende.IdentityServer.Stores.IServerSideSessionStore' returned null.
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at lambda_method1037(Closure, Object, HttpContext, IServiceProvider)
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.eShopOnContainers.Services.Identity.API.Startup.<>c.<<Configure>b__5_0>d.MoveNext() in C:\Tarun\github\erjain\dotnet-architecture\eShopOnContainers\src\Services\Identity\Identity.API\Startup.cs:line 131
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

**Additional context**

**Comment by josephdecock** [comment] 2022-11-28 17:12
This error means that the server side session store can't be resolved by the DI system. Why that is the case depends on which implementation of the server side session store you have registered. We have a default in memory server side session store (used for testing/demos/etc), but I see some references to EntityFramework in the logs above, so I suspect you are either using the Entity Framework based server side session store or your own implementation of IServerSideSessionStore. Our docs [here](IServerSideSessionStore) describe that in a bit more detail. Can you please take a look at that and then explain in more detail how you're using server side sessions and in particular which implementation of IServerSideSessionStore you're using?

**Comment by erjain** [comment] 2022-11-28 19:59
Hi @josephdecock, thank you so much for responding, the link mentioned seems to be incorrect.

**Comment by josephdecock** [comment] 2022-11-28 21:57
Sorry about that, here's the correct link:
https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/

**Comment by erjain** [comment] 2022-11-29 08:50
I followed this link, but was not able to conclude what I did wrong, here is the implementation: https://github.com/erjain/eShopOnContainers/tree/net7-duende/src/Services/Identity/Identity.API

**Comment by josephdecock** [comment] 2022-11-29 14:47
Okay, looks like you're using the builtin EF implementation of the server side session store. 

I have a couple ideas:

1. Maybe there is a broader issue with your services in DI. You could try commenting out the [call to AddServerSideSessions](https://github.com/erjain/eShopOnContainers/blob/net7-duende/src/Services/Identity/Identity.API/Startup.cs#L62) to see if the issue is only with server side sessions.
2. Maybe the issue is related to autofac. I don't usually use autofac these days - are you able to disable it in favor of the built in DI container (at least temporarily)?

**Comment by erjain** [comment] 2022-11-29 18:47
I also tried to do that but still got the same error. Not sure where I missed it, but it seems I messed up with some configuration. And worst I am not able to debug it via breakpoint. Any help would be appreciated.

**Comment by josephdecock** [comment] 2022-11-30 22:34
Identity Server's signing keys get encrypted and decrypted using microsoft's data protection feature. Data protection manages its own encryption key separately from the signing key that IdentityServer uses. The data protection keys can cause problems if you have a key stored in your signing key store, but try to decrypt it without the data protection key that encrypted it..

There are several ways that this can occur:

1. In load balanced environments, every instance of IdentityServer needs to share signing keys, and you need to configure data protection to do so. Microsoft has extension docs here.
2. Signing keys could be generated in a (local) development environment and then accidentally included into the build output.
3. Data protection creates keys isolated by application name automatically. If you don't specify a name, the content root path of the application will be used. But, beginning in .NET 6.0 Microsoft changed how they handle the path, which can cause data protection keys to break. Their docs on the problem are here, including a work-around where you de-normalize the path.

**Comment by josephdecock** [comment] 2022-12-01 00:00
Oh, shoot, my links are missing above.

I meant to send you to this page of the MS docs:

https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0#setapplicationname

That linked section discusses the path normalization problem, and the rest of the document starting at the beginning goes into detail about ways you can share keys in load balanced scenarios.

**Comment by josephdecock** [comment] 2022-12-10 06:17
Closing this issue, but feel free to open a new issue as needed.

**Closed by josephdecock** 2022-12-10 06:17 UTC
Labels: IdentityServer, question

**Comment by bvandermeide** [comment] 2023-10-31 06:56
@josephdecock, @brockallen, @erjain - Hope this helps not only @erjain, but others using Autofac as DI of choice

## **The following solution worked for me:**
Register a delegate for construction that uses the `IServiceProvider` to resolve all other parameters, while allowing `null` for those indicating nulls are allowed

````cs
builder.Services.AddScoped<ISessionCoordinationService>(x =>
  new DefaultSessionCoordinationService(
    x.GetRequiredService<IdentityServerOptions>(),
    x.GetRequiredService<IPersistedGrantStore>(),
    x.GetRequiredService<IClientStore>(),
    x.GetRequiredService<IBackChannelLogoutService>(),
    x.GetRequiredService<ILogger<DefaultSessionCoordinationService>>(),
    null)); // <-- specifying null as Autofac resolution treats x.GetRequiredService & x.GetService the same
````

## Root Cause

I ran into the same error after switching from Microsoft's default DI provider to Autofac as the DI provider of choice.

When using Autofac as the DI framework of choice, know that is behaves differently in DI injection.  Its implementation of `IServiceProvider`'s method of `x.GetService<...>()` expects a constructor exists where all params can be resolved as if each param is to be resolved as `x.GetRequiredService<...>()` was called. 

This is unlike Microsoft's DI that when `x.GetService<...>()` is called will provide `null` values for constructor params allowing nulls when none can be resolved.

Not a bug of Duende, but a (IMHO) bug / feature by design in Autofac

Autofac throws an `Autofac.Core.DependencyResolutionException` because, by default, **there is no `IServerSideSessionStore` registered when you call `builder.Services.AddIdentityServer(...)`.**

It will only register an `IServerSideSessionStore` if the Duende framework consumer decides to enable server side session management features and requires a Business level license to Duende to use

````cs
builder.Services
  .AddIdentityServer(...)
  .AddServerSideSessions() // most likely, but wrong, response a dev will attempt when reacting to the DI error
````

I do not think the correct guidance / nor your intent is to drive users to use the ServerSideSession management features because of Autofac config issues, but rather to **correctly configure the DI to work with Duende as Duende is designed to behave**.

Duende's `DefaultSessionCoordinationService` constructor specifically expresses that the parameter for `IServerSideSessionStore` is nullable

````cs
public DefaultSessionCoordinationService(
    IdentityServerOptions options,
    IPersistedGrantStore persistedGrantStore,
    IClientStore clientStore,
    IBackChannelLogoutService backChannelLogoutService,
    ILogger<DefaultSessionCoordinationService> logger,
    IServerSideSessionStore serverSideSessionStore = null) // <-- here
{
...
}
````

**Comment by AndersAbel** [comment] 2023-11-01 15:08
Thanks @bvandermeide for the additional context and explanation.
