### ISSUE TITLE
Identity Server is redirecting to /Account/Login page instead of continuing its flow

### ISSUE THREAD

**Issue by SriramaDanturthi** [DuendeSoftware/Support#283] opened 2022-10-19 22:04 UTC
**Which version of Duende IdentityServer are you using?**
6.1.5
**Which version of .NET are you using?**
6.0.7
**Describe the bug**
Some times  After successful login its redirecting to /Account/Login instead of the  of continuing its flow and redirect to the redirect_uri provided on the request.

**To Reproduce**

[Steps to reproduce the behavior.]

https://locahost/identityprovider/Account/Login?ReturnUrl=%2Fidentityprovider%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dlocalhost-test%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%253A4430%252Fsignin-oidc%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520test-module%2520offline_access%2520test-api%26code_challenge%3Dpz_9S6pnzf2vUPLtmv_T5HIUSovU0vMo1CWD4VGZ2K4%26code_challenge_method%3DS256%26nonce%3D638018126608710366.ZTRkM2JmNzctOTY4MC00M2I4LWI0YTUtMzM4MTZmMTBlZjMwNDk3MmYyNDgtMzIyNy00MTQyLWEzN2YtNDJlYzc5ODNhNzU2%26state%3DCfDJ8GomdTPc4IdHo-wUyOoJngGYbom9HbRjiNrLGFIG1C9vT5URPrfYy4-k84gc3uoIaO0coruYq3sM5sM6-841L4EpMwqOJiKid3iAYO7Lddbz1HRgCnxRou1nlFdpcuIwAPJPyrrtc7OINESB2JM4tt9HG9BSqBsvPYNoobgXYsnnXikGl43yN9ru0buzRwXLGxg4Pk5snoaVpkizo_cC4gPpaH0MhwUMb0MxW57wBGKZ7-dgBqcQi084ucH1XG7IZdEBKmVaQ0QGM8DqrN-om1ZokQMmteOlR6kaSn68xTNj5URQCU2UzXXmaZVkPGR67cBdy4dNOwDSTKCQLplkXg389mBMLXR--6B-_ApiImPowj-5Xuf5lMhYBHSR4W6bkbZ6PAweW-7qDP-NKq8sGHo%26x-client-SKU%3DID_NETSTANDARD2_0%26x-client-ver%3D6.10.0.0)

**Expected behavior**
It should redirect tot eh supplied redirect_rui

**Log output/exception with stacktrace**

Start authorize request protocol validation
[DBG] client configuration validation for client localhost-test succeeded.
[DBG] Checking for PKCE parameters
[DBG] Calling into custom validator: Duende.IdentityServer.Validation.DefaultCustomAuthorizeRequestValidator
[DBG] client configuration validation for client localhost-test succeeded.
```
data
```

**Additional context**

this is happening after signout / if the users session is expired / if we remove the cookies manually

**Comment by SriramaDanturthi** [comment] 2022-10-21 11:54
In the debug logs I found an error saying antiforgery token is invalid and then redirecting to this login screen instead of error screen not sure why its not redirecting to error screen. what we have to do to redirect to error screen

**Comment by brockallen** [comment] 2022-10-21 14:10
If the problem is with anti-forgery, then that's more of a general ASP.NET Core issue. I've seen this sort of thing in the past -- do you have multiple tabs open trying to login in several? In any event, I doubt it's something we'd be able to change or affect in IdentityServer.

**Comment by SriramaDanturthi** [comment] 2022-10-21 14:57
yes i do have multiple tabs open and trying to login on them

**Comment by brockallen** [comment] 2022-10-21 15:10
> yes i do have multiple tabs open and trying to login on them

This might explain it. It's a well-known issue with anti-forgery in ASP.NET Core. You'd have to search their issue tracker for more information, but my recollection is that they do not intend to change how that works.

**Comment by brockallen** [comment] 2022-10-25 20:12
Closing. If you still have issues, feel free to reopen.

**Closed by brockallen** 2022-10-25 20:12 UTC
Labels: IdentityServer, question
