### ISSUE TITLE
Microsoft.EntityFrameworkCore.Update.SaveChangesFailed IN /connect/authorize/callback

### ISSUE THREAD

**Issue by beyondnagatani** [DuendeSoftware/Support#1028] opened 2023-12-06 01:42 UTC
**Which version of Duende IdentityServer are you using?**

6

**Which version of .NET are you using?**

6

**Describe the bug**

Microsoft.EntityFrameworkCore.Update.SaveChangesFailed IN /connect/authorize/callback

**To Reproduce**

unknown

**Log output/exception with stacktrace**

- EventName
`Microsoft.EntityFrameworkCore.Update.SaveChangesFailed`

- FormattedMessage
```
An exception occurred in the database while saving changes for context type 'Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

- CategoryName
`Microsoft.EntityFrameworkCore.Update`

- OriginalFormat
`An exception occurred in the database while saving changes for context type '{contextType}'.{newline}{error}`

- RequestPath
`/connect/authorize/callback`

- contextType
`Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext`

- error
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

**Additional context**

Startup.cs

```
var migrationAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
services.AddIdentityServer(options =>
{
    options.KeyManagement.Enabled = true;

    options.KeyManagement.RotationInterval = TimeSpan.FromDays(30);

    options.KeyManagement.PropagationTime = TimeSpan.FromDays(2);

    options.KeyManagement.RetentionDuration = TimeSpan.FromDays(7);

    options.KeyManagement.DeleteRetiredKeys = false;

    options.LicenseKey = Configuration.GetConnectionString("identityLicenseKey");
})
    .AddOperationalStore(
        options => options.ConfigureDbContext = b => b.UseSqlServer(
        Configuration.GetConnectionString("dbWrite"), opt => opt.MigrationsAssembly(migrationAssembly))
    )
    .AddInMemoryIdentityResources(new IdentityResource[]
    {
        new IdentityResources.OpenId(),
        new IdentityResources.Profile(),
    })
    .AddInMemoryApiScopes(new ApiScope[]
    {
        new ApiScope(IdentityServerConstants.LocalApi.ScopeName),
    })
    .AddInMemoryClients(Configuration.GetSection("Clients"))
    .AddRedirectUriValidator<RedirectUriValidator>()
    .AddAspNetIdentity<User>()
    .AddProfileService<ProfileService>();
```

Is it safe to say that this is similar to the previous problem, but that there is nothing wrong with this case too?
https://github.com/DuendeSoftware/Support/issues/942

We have confirmed that this error occurs only occasionally and does not affect users.

**Comment by josephdecock** [comment] 2023-12-11 22:03
My best guess is that rare task cancellation exceptions are caused by incoming http requests being aborted, but it is hard to say in this case with total certainty, because we can't see from the call stack where in IdentityServer this is happening. Since you say it isn't impacting users and is rare, I think you don't really need to worry about it.

But one way that you could investigate further if you are interested, would be to try replacing the `ICancellationTokenProvider` in the DI system with the `NoneCancellationTokenProvider`. This provider is the abstraction we use to get the cancellation tokens. The default provider looks at the actual request to get its cancellation token, but the None provider just always returns an empty token. We usually only use this for testing purposes, but you could try it out and see if that prevents the issue. It's generally better to use the default provider and actually cancel the database operation when the incoming request is aborted, as this can decrease load on the data store. As a short term experiment, I think it would be fine though.

**Comment by AndersAbel** [comment] 2024-01-16 12:21
@beyondnagatani Do you have any updates or more questions on this? If not, I'd like to close the issue.

**Comment by josephdecock** [comment] 2024-01-29 17:12
Closing, but feel free to reopen if necessary.

**Closed by josephdecock** 2024-01-29 17:12 UTC
Labels: IdentityServer, question
