### ISSUE TITLE
AKM is creating a new key every time App Pool is recycled

### ISSUE THREAD

**Issue by dasdeviprasad** [DuendeSoftware/Support#397] opened 2022-12-13 16:24 UTC
**Which version of Duende IdentityServer are you using?**
6.1.3

**Which version of .NET are you using?**
.net core 6

**Describe the bug**
AKM (Automatic key Management) is creating a new key every time the APP Pool is recycled, the resources using the old key are not able to validate the new access token.

**To Reproduce**
Recycle the app pool and it creates a new key in [Keys] table, it does not respect the KeyManagement.RotationInterval property value.

**Expected behavior**
The new key should be generated only when the KeyManagement.RotationInterval time is met, not when the App Pool is recycled. The resources who are using the key won't have any idea about the new key and they start invalidating the new tokens.

Is there a way we can stop it from happening?

**Comment by josephdecock** [comment] 2022-12-13 16:49
Are you getting data protection failures in the logs ("The key {xxxx} was not found in the key ring")? Anything else in the logs? Can you describe your deployment environment in a bit more detail (in particular, are you load balanced, and if so, how are you sharing data protection keys across instances?). Which implementation of ISigningKeyStore are you using?

**Comment by dasdeviprasad** [comment] 2022-12-13 18:28
Thank you Joseph for your response.

1. Application log: Mainly getting these two errors.
    - Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
    - The key {XXX} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
3. Deployment: Only one instance of the application is running, hence no load balancer.
4. Not using any custom implementation of ISigningKeyStore. For operational data, Entity Framework for SQL server is used.

Please let me know if you need any other details.

**Comment by josephdecock** [comment] 2022-12-13 19:20
The reason IdentityServer is creating a new key is that it isn't able to decrypt the old key. What is clear is that data protection is failing to unprotect your signing key material. What is less clear is why that would be associated with recycling the app pool. 

After you recycle the app pool and a new key is generated, are you able to use that key? You should see it in discovery - if you go to .well-known/openid-configuration/jwks on your identity server, the keys you see there will have kid properties which you should be able to correlate back to your keys in the database, And if you generate tokens, the header should include that kid as well. Does that all work until you recycle the app pool?

**Comment by dasdeviprasad** [comment] 2022-12-13 19:56
Yes, after app pool recycle, the new key is updated in the JWKS config end-point but the issue is Resource APIs have already cached the old key and there is no propagation time given to the resource API. So, Identity has started generating token signed with the new key which resources are unaware of and still using the old key to validate the token.

Is there a reason why the IdentityServer is unable to decrypt the old key. We have to added any custom code to Key management, we are using the default mechanism with the following config.

`options.KeyManagement.KeyPath = KeyStoragePath;
options.KeyManagement.RotationInterval = TimeSpan.FromDays(KeyRotationInterval); // A new key is created every X days.
options.KeyManagement.PropagationTime = TimeSpan.FromDays(KeyPropagationTime); // A new key s announced X days in advance in discovery.
options.KeyManagement.RetentionDuration = TimeSpan.FromDays(KeyRetentionDuration);`

Are we missing any configuration which will help us fix this?

**Comment by josephdecock** [comment] 2022-12-13 20:48
Do you have any data protection configuration (a call like `builder.Services.AddDataProtection()`?

**Comment by dasdeviprasad** [comment] 2022-12-13 22:16
No, we do not have it.

**Comment by josephdecock** [comment] 2022-12-14 15:34
Yes, I would try adding data protection configuration. By default, data protection tries to infer things about its environment and automatically determines where keys are stored, as described here: https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-7.0. There are basically 4 possibilities:

1. Azure Apps automatically synchronize keys across machines
2. Local Development stores keys in the user profile
3. IIS stores keys in the windows registry. Access to the keys in the registry is controlled with an ACL so that only the worker process can access the keys, and the keys are encrypted at rest with DPAPI
4. Otherwise, keys are lost after restarting the app

Since you're hosted in IIS, my first thought is about ways that option 3 could go wrong - there might be some sort of permissions problem where your worker process isn't able to get what it needs from the registry, or use DPAPI. Or maybe, somehow data protection is failing to understand that you're hosted in IIS and you're actually in option 4. It's hard to know for sure, so I would probably just take control of where data protection keys are persisted. There are many options, see the docs here for the full details: https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0.

The other thing I would do is set the application name. Data protection creates isolated encryption keys separated by application name. It defaults to using the file system path to the application. This causes issues if you change physical details about your hosting. Also, if you ever need to horizontally scale, each instance must set the same application name. I don't think the application name is the cause of your problem right now, but if you're setting up the data protection configuration, I would include that to prevent future difficulties.

**Comment by josephdecock** [comment] 2023-01-04 22:24
Any update here? Can we close this issue?

**Comment by josephdecock** [comment] 2023-01-15 18:05
Closing, but feel free to reopen if necessary.

**Closed by josephdecock** 2023-01-15 18:05 UTC
Labels: IdentityServer, question
