### ISSUE TITLE
License Configuration Issue: Authentication Error

### ISSUE THREAD

**Issue by ssssuuunnnn** [DuendeSoftware/Support#878] opened 2023-09-08 03:21 UTC
**Which version of Duende IdentityServer are you using?**
v6

**Describe**

Hello,

I would like to inquire about the configuration of the license.

I followed the configuration instructions provided at this URL (https://docs.duendesoftware.com/identityserver/v6/fundamentals/license_key/), but after following the steps in the quickstarts for my program development, I placed the license in HostingExtensions.cs. 

However, I am still seeing the error message "[DBG] AuthenticationScheme: Identity.Application was not authenticated." in the system log.

Could you please clarify if this error is related to the license configuration? If so, how can I resolve it?

Thank you.

<img width="1369" alt="截圖 2023-09-08 上午11 18 42" src="https://github.com/DuendeSoftware/Support/assets/130637296/76dffdc2-010c-4033-a934-43569bb6a817">

**Comment by josephdecock** [comment] 2023-09-08 18:12
The IdentityServer license is not the cause of this problem. The licensing system is designed to only add warnings to the logs, not disrupt functionality. That log message might not even be an error - it might just be a debugging message saying that an anonymous request was received by your server. Depending on that context that might be what you expect. Are you seeing any other symptoms?

**Comment by josephdecock** [comment] 2023-09-20 13:50
Any update here? Or should we just close the issue?

**Comment by ssssuuunnnn** [comment] 2023-09-21 01:30
Thank you for your reply. We understand the cause of the problem.

**Closed** 2023-09-25 08:29 UTC
Labels: IdentityServer
